# Drug profile dataset — harm-reduction facts compiled from NIDA, DEA, EMCDDA, WHO, TripSit & Erowid
# streetPrice values are regional estimates ("~" = varies widely). Verify locally.

DRUGS = [
# ---------------- OPIOIDS ----------------
dict(slug="heroin", name="Heroin", aliases=["Dope", "H", "Smack", "Sugar brown", "Brown", "Junk"],
 category="opioids", schedule="Schedule I (US)",
 appearance="White/off-white powder (US) or brown base powder ('sugar brown'); black tar (Mexico)",
 effects=["Rapid intense euphoria ('rush')", "Warmth, heavy limbs", "Pain relief, drowsiness ('nodding')"],
 risks=["Extremely addictive — physical dependence in weeks", "Overdose: breathing slows or stops", "Unknown strength + fentanyl contamination"],
 overdoseSigns=["Unresponsive, pinpoint pupils", "Breathing <8/min or gurgling", "Blue/gray lips and fingernails"],
 streetPrice="~$10–$40 per bag; prices vary by region",
 legalStatus="Illegal — Schedule I in the US; Class A (UK); controlled everywhere listed",
 lastUpdated="2026-09-12", sources=["NIDA","DEA","EMCDDA"]),

dict(slug="fentanyl", name="Fentanyl", aliases=["Apache", "China Girl", "Dance Fever", "Tango & Cash"],
 category="opioids", schedule="Schedule II (US, pharmaceutical)",
 appearance="White powder, pressed pills, counterfeit oxycodone — often invisible when mixed into other drugs",
 effects=["Extreme euphoria", "Drowsiness", "Pain relief"],
 risks=["Respiratory depression", "Addiction in days", "2 mg (~a few grains) can be fatal"],
 overdoseSigns=["Pinpoint pupils", "Slow or stopped breathing", "Blue lips, limp body"],
 streetPrice="~$20–$40 per counterfeit pill",
 legalStatus="Felony possession in all US states; analogues prosecuted under the Federal Analogue Act",
 lastUpdated="2026-09-12", sources=["NIDA","DEA","CDC"]),

dict(slug="fentanyl-hcl", name="Fentanyl HCl (powder)", aliases=["Fent HCl", "China White (sold as)"],
 category="opioids", schedule="Schedule II / analogue prosecutions (US)",
 appearance="Fine white crystalline powder, indistinguishable from other white powders",
 effects=["Same as fentanyl — opioid euphoria, sedation"],
 risks=["Lab-purity powder is far stronger than street mixes", "Weighing errors are fatal", "Cross-contaminates everything it touches"],
 overdoseSigns=["Pinpoint pupils", "Respiratory arrest", "Cyanosis (blue skin)"],
 streetPrice="~$60–$120/gram wholesale equivalent; highly variable",
 legalStatus="Illegal to possess without prescription; trafficking = federal felony",
 lastUpdated="2026-09-12", sources=["DEA","NIDA"]),

dict(slug="acetylfentanyl", name="Acetylfentanyl", aliases=["ACE", "Acetyl fent"],
 category="opioids", schedule="Schedule I (US, 2015)",
 appearance="White/tan powder, sometimes sold as 'synthetic heroin' or pressed into pills",
 effects=["Fentanyl-like opioid effects, shorter acting"],
 risks=["~5–15× weaker than fentanyl but still deadly at gram-level mistakes", "Frequent cause of cluster overdoses"],
 overdoseSigns=["Pinpoint pupils", "Slow breathing", "Loss of consciousness"],
 streetPrice="~$25–$60/g where found",
 legalStatus="Schedule I in the US; banned/controlled in EU, UK, Canada, Australia",
 lastUpdated="2026-09-12", sources=["DEA","EMCDDA","UNODC"]),

dict(slug="furanylfentanyl", name="Furanylfentanyl (Fu-F)", aliases=["Fu-F", "FUF"],
 category="opioids", schedule="Schedule I (US, 2018)",
 appearance="White/yellowish powder or pressed tablets",
 effects=["Opioid euphoria and sedation, slower onset than fentanyl"],
 risks=["Linked to hundreds of fatal overdoses 2016–2018", "Potency similar to fentanyl"],
 overdoseSigns=["Respiratory depression", "Unconsciousness", "Miosis (pinpoint pupils)"],
 streetPrice="~$20–$50/g (residual availability)",
 legalStatus="Schedule I (US); controlled in EU/UK/Canada/Australia",
 lastUpdated="2026-09-12", sources=["DEA","EMCDDA","NPS-AD"]),

dict(slug="methoxyacetylfentanyl", name="Methoxyacetylfentanyl", aliases=["MAF"],
 category="opioids", schedule="Schedule I (US, 2018)",
 appearance="White/off-white powder",
 effects=["Powerful opioid sedation and euphoria"],
 risks=["Potency comparable to or exceeding fentanyl", "Tiny dosing errors fatal"],
 overdoseSigns=["Pinpoint pupils", "Slow/stopped breathing", "Blue lips"],
 streetPrice="Rare; ~$30–$80/g where found",
 legalStatus="Schedule I (US); controlled across EU, UK, Canada, Australia",
 lastUpdated="2026-09-12", sources=["DEA","EMCDDA"]),

dict(slug="etonitazene", name="Etonitazene", aliases=["Etazene", "EZ"],
 category="opioids", schedule="Schedule I (US, 2023)",
 appearance="White/yellow/off-white powder, pills, or e-liquid for vaping",
 effects=["Intense opioid euphoria at microgram doses"],
 risks=["~10–25× fentanyl potency", "Active at sub-milligram doses — nearly impossible to dose safely"],
 overdoseSigns=["Immediate respiratory depression", "Unresponsiveness", "Pinpoint pupils"],
 streetPrice="~$40–$100/g (equivalent to millions of doses)",
 legalStatus="Schedule I (US, 2023); controlled/prohibited in EU, UK, Canada, Australia",
 lastUpdated="2026-09-12", sources=["DEA","EMCDDA","WHO-UNODC"]),

dict(slug="isotodesnitazene", name="Isotodesnitazene", aliases=["Iso", "ISO"],
 category="opioids", schedule="Emerging — prosecuted as analogue (US); banned in several EU states",
 appearance="White/yellow powder, often mixed into heroin or counterfeit pills",
 effects=["Euphoria, heavy sedation — nitazene-class opioid"],
 risks=["Fentanyl-level or greater potency", "Driving a new wave of overdose clusters since 2022"],
 overdoseSigns=["Pinpoint pupils", "Slow breathing", "Blue lips"],
 streetPrice="~$30–$70/g where found",
 legalStatus="Analogue Act prosecutions (US); scheduled in DE/UK/others — check locally",
 lastUpdated="2026-09-12", sources=["EMCDDA","DEA","NPS-AD"]),

dict(slug="oxymorphone", name="Oxymorphone (Opana 40 mg)", aliases=["Opana", "OM", "Pink"],
 category="opioids", schedule="Schedule II (US)",
 appearance="Pink/octagonal ER tablets (Opana 40 mg); white IR tablets",
 effects=["Strong pain relief, euphoria, sedation"],
 risks=["High addiction potential", "Crushing ER tablets caused IV abuse epidemics and was withdrawn in US"],
 overdoseSigns=["Pinpoint pupils", "Respiratory depression", "Loss of consciousness"],
 streetPrice="~$30–$65 per 40 mg tablet (diverted)",
 legalStatus="Rx-only, Schedule II; felony without prescription",
 lastUpdated="2026-09-12", sources=["FDA","DEA","NIDA"]),

dict(slug="morphine-60mg", name="Morphine 60 mg", aliases=["M60", "MS Contin", "Miss Emma"],
 category="opioids", schedule="Schedule II (US)",
 appearance="Round ER tablets imprinted 60 (purple/orange by brand); oral solution; injectable ampoules",
 effects=["Pain relief, calm, warmth; strong sedation at higher doses"],
 risks=["Dependence within 2–3 weeks of daily use", "ER tablets fatal if chewed/crushed"],
 overdoseSigns=["Pinpoint pupils", "Slow shallow breathing", "Cold clammy skin"],
 streetPrice="~$10–$30 per 60 mg tablet (diverted)",
 legalStatus="Rx-only, Schedule II; felony without prescription",
 lastUpdated="2026-09-12", sources=["NIDA","DEA"]),

dict(slug="hydromorphone", name="Hydromorphone (Dilaudid 8 mg)", aliases=["Dilaudid", "D", "Dillies", "8s"],
 category="opioids", schedule="Schedule II (US)",
 appearance="Small triangular white tablets ('8mg triangles'); clear injectable liquid",
 effects=["Rapid euphoria, warm sedation — 5× morphine potency"],
 risks=["Fast IV addiction", "Narrow safety margin; frequently implicated in overdose"],
 overdoseSigns=["Pinpoint pupils", "Respiratory depression", "Unresponsiveness"],
 streetPrice="~$20–$60 per 8 mg tablet (diverted)",
 legalStatus="Rx-only, Schedule II; felony without prescription",
 lastUpdated="2026-09-12", sources=["NIDA","DEA","CADTH"]),

dict(slug="oxycodone", name="Oxycodone (Roxicodone 30 mg)", aliases=["Roxy", "30s", "Blues", "Percs (with APAP)"],
 category="opioids", schedule="Schedule II (US)",
 appearance="Blue 30 mg IR tablets; also white pills with various imprints",
 effects=["Euphoria, pain relief, energy then sedation"],
 risks=["Highly addictive — a leading gateway to heroin/fentanyl transition", "Counterfeit 'blues' are usually fentanyl"],
 overdoseSigns=["Pinpoint pupils", "Slow breathing", "Blue lips"],
 streetPrice="~$15–$40 per 30 mg tablet (diverted); $3–$15 for counterfeits",
 legalStatus="Rx-only, Schedule II; felony without prescription",
 lastUpdated="2026-09-12", sources=["NIDA","DEA","CDC"]),

dict(slug="oxycontin", name="OxyContin", aliases=["OC", "Oxy", "Hillbilly Heroin"],
 category="opioids", schedule="Schedule II (US)",
 appearance="Round ER tablets (OC imprint); reformulated 2010 to deter crushing",
 effects=["Long-duration pain relief and euphoria"],
 risks=["Dependence; pre-2010 formulations still crushable on illicit market"],
 overdoseSigns=["Pinpoint pupils", "Respiratory depression", "Sedation"],
 streetPrice="~$20–$80 per 80 mg tablet (diverted; reformulated discounted)",
 legalStatus="Rx-only, Schedule II; felony without prescription",
 lastUpdated="2026-09-12", sources=["FDA","NIDA"]),

dict(slug="codeine-30-500", name="Codeine 30/500 mg (co-codamol)", aliases=["T3s", "Syrup", "Lean (with promethazine)"],
 category="opioids", schedule="Schedule V / Rx (US varies); OTC+pharmacy elsewhere",
 appearance="White tablets (30 mg codeine / 500 mg paracetamol); purple/clear syrup",
 effects=["Mild euphoria, relaxation, cough suppression"],
 risks=["Paracetamol component destroys the liver at high doses", "Lean + alcohol risks fatal respiratory depression"],
 overdoseSigns=["Extreme drowsiness", "Slow breathing", "Vomiting, confusion"],
 streetPrice="~$2–$10 per tablet; $100+/pint syrup",
 legalStatus="Rx-only in US (varies by state); pharmacy-controlled in EU; OTC-low-dose in some countries",
 lastUpdated="2026-09-12", sources=["NIDA","EMCDDA"]),

dict(slug="hydrocodone", name="Hydrocodone 10/500 mg", aliases=["Norco", "Vicodin (with APAP)", "Watsons (Watson labs)"],
 category="opioids", schedule="Schedule II (US, since 2014)",
 appearance="White/oblong tablets imprinted Watson 540-style; capsules historically",
 effects=["Pain relief, mild-moderate euphoria, sedation"],
 risks=["Dependence", "APAP liver toxicity when abused"],
 overdoseSigns=["Pinpoint pupils", "Slow breathing", "Extreme drowsiness"],
 streetPrice="~$5–$20 per 10 mg tablet (diverted)",
 legalStatus="Rx-only, Schedule II; felony without prescription",
 lastUpdated="2026-09-12", sources=["DEA","FDA"]),

dict(slug="vicoprofen", name="Hydrocodone–Ibuprofen (Vicoprofen)", aliases=["Vicoprofen", "Ibu-hydro"],
 category="opioids", schedule="Schedule II (US)",
 appearance="White oblong tablets (7.5 mg hydro / 200 mg ibuprofen)",
 effects=["Pain relief, mild euphoria"],
 risks=["Dependence", "GI bleeding/renal harm at high ibuprofen doses"],
 overdoseSigns=["Pinpoint pupils", "Slow breathing", "Confusion"],
 streetPrice="~$5–$15 per tablet (diverted)",
 legalStatus="Rx-only, Schedule II; felony without prescription",
 lastUpdated="2026-09-12", sources=["FDA","DEA"]),

dict(slug="meperidine", name="Meperidine (Demerol)", aliases=["Demerol", "Meperidine HCl caps", "Pethidine"],
 category="opioids", schedule="Schedule II (US)",
 appearance="White capsules (50/100 mg); clear injectable solution",
 effects=["Short-acting euphoria and pain relief"],
 risks=["Normeperidine metabolite causes seizures with repeated dosing", "Outdated — largely replaced in medicine"],
 overdoseSigns=["Pinpoint pupils", "Respiratory depression", "Tremor/seizures (toxic build-up)"],
 streetPrice="~$5–$20 per 100 mg capsule (rare, diverted)",
 legalStatus="Rx-only, Schedule II; felony without prescription",
 lastUpdated="2026-09-12", sources=["FDA","NIDA"]),

dict(slug="methadone", name="Methadone", aliases=["Done", "Dolly", "Amidone"],
 category="opioids", schedule="Schedule II (US)",
 appearance="Orange/red diskettes (40 mg), liquid (cherry), tablets, injectable ampoules",
 effects=["Long-lasting (24–36 h) opioid stability, blocks withdrawal and cravings"],
 risks=["Accumulates over days — overdose risk highest in first 2 weeks", "Fatal mixing with benzos/alcohol"],
 overdoseSigns=["Pinpoint pupils", "Slow breathing", "Extreme sedation"],
 streetPrice="~$10–$40 per 40 mg diskette (diverted)",
 legalStatus="Rx via licensed opioid-treatment programs; diversion is a felony",
 lastUpdated="2026-09-12", sources=["SAMHSA","NIDA","DEA"]),

dict(slug="suboxone", name="Suboxone (buprenorphine/naloxone)", aliases=["Subs", "Bupe", "Strips", "Oranges"],
 category="opioids", schedule="Schedule III (US)",
 appearance="Orange sublingual films (2/0.5 mg, 8/2 mg) or hexagonal tablets",
 effects=["Stops withdrawal and cravings; 'ceiling effect' limits respiratory depression"],
 risks=["Dependence (milder than full opioids)", "Precipitates withdrawal if taken too soon after other opioids"],
 overdoseSigns=["Rare alone; sedation + respiratory depression when mixed with benzos/alcohol"],
 streetPrice="~$10–$25 per 8 mg film (diverted)",
 legalStatus="Rx-only, Schedule III; felony without prescription (though widely used in treatment)",
 lastUpdated="2026-09-12", sources=["SAMHSA","FDA","NIDA"]),

dict(slug="subutex", name="Subutex (buprenorphine)", aliases=["Bupe", "Subbies"],
 category="opioids", schedule="Schedule III (US)",
 appearance="White sublingual tablets (2 mg, 8 mg), hexagonal imprint",
 effects=["Long-acting opioid — treats withdrawal and pain"],
 risks=["Diverted for IV use", "Overdose when injected with depressants"],
 overdoseSigns=["Sedation", "Slow breathing (rare alone)", "Miosis"],
 streetPrice="~$10–$30 per 8 mg tablet (diverted)",
 legalStatus="Rx-only, Schedule III; felony without prescription",
 lastUpdated="2026-09-12", sources=["SAMHSA","DEA"]),

dict(slug="duragesic", name="Fentanyl patches (Duragesic 12.5 mcg/hr)", aliases=["Duragesic", "Patches", "Gel patches"],
 category="opioids", schedule="Schedule II (US)",
 appearance="Tan rectangular transdermal patches (12.5–100 mcg/hr), gel or matrix type",
 effects=["72-hour continuous pain relief; warmth amplifies absorption"],
 risks=["Cut/heated patches dump lethal doses", "A used patch still holds ~30–50% of its fentanyl"],
 overdoseSigns=["Sedation", "Slow breathing", "Pinpoint pupils"],
 streetPrice="~$20–$100 per patch (diverted)",
 legalStatus="Rx-only, Schedule II; felony without prescription",
 lastUpdated="2026-09-12", sources=["FDA","NIDA"]),

dict(slug="diazepam-drug", name="Diazepam", aliases=["Valium", "Bensedine", "Apaurine (blue valium)", "V's"],
 category="benzodiazepines", schedule="Schedule IV (US)",
 appearance="2–10 mg tablets (yellow/blue/white); Apaurine = blue 10 mg; clear injectable vials",
 effects=["Calm, muscle relaxation, anti-anxiety, sedation"],
 risks=["Dependence in 2–4 weeks of daily use", "Dangerous withdrawal (seizures) — never stop cold turkey", "Mixing with opioids/alcohol can stop breathing"],
 overdoseSigns=["Extreme drowsiness", "Confusion", "Slow breathing (especially with other depressants)"],
 streetPrice="~$1–$10 per 10 mg tablet (diverted); counterfeits common",
 legalStatus="Rx-only, Schedule IV; felony without prescription",
 lastUpdated="2026-09-12", sources=["NIDA","DEA","EMCDDA"]),
]

DRUGS += [
# ---------------- BENZODIAZEPINES & RC BENZOS ----------------
dict(slug="alprazolam", name="Alprazolam (Xanax 2 mg)", aliases=["Xanax", "Bars", "Pfizer LongBars", "Zans", "Footballs"],
 category="benzodiazepines", schedule="Schedule IV (US)",
 appearance="White 2 mg 'bars' (long, scored); blue/white/yellow football-shaped tablets by dose",
 effects=["Fast anti-anxiety relief", "Calm sedation", "Muscle relaxation"],
 risks=["Dependence within weeks; brutal withdrawal (seizures risk)", "Counterfeit 'bars' increasingly contain fentanyl or bromazolam", "Amnesia and risky behavior ('barred out')"],
 overdoseSigns=["Extreme drowsiness", "Slurred speech", "Slow breathing — fatal with opioids/alcohol"],
 streetPrice="~$2–$10 per 2 mg bar (diverted); $1–$5 counterfeits",
 legalStatus="Rx-only, Schedule IV; felony without prescription",
 lastUpdated="2026-09-12", sources=["NIDA","DEA","EMCDDA"]),

dict(slug="lorazepam", name="Lorazepam (Ativan 2.5 mg)", aliases=["Ativan", "Tranks"],
 category="benzodiazepines", schedule="Schedule IV (US)",
 appearance="White tablets (0.5–2.5 mg) marked imprint; clear injectable vials (hospitals)",
 effects=["Calm, sedation, anti-anxiety, seizure control"],
 risks=["Dependence and withdrawal seizures", "Rebound anxiety between doses"],
 overdoseSigns=["Extreme sedation", "Confusion", "Slow breathing with other depressants"],
 streetPrice="~$1–$5 per 2.5 mg tablet (diverted)",
 legalStatus="Rx-only, Schedule IV; felony without prescription",
 lastUpdated="2026-09-12", sources=["NIDA","DEA"]),

dict(slug="clonazepam", name="Clonazepam (Rivotril/Klonopin 2 mg)", aliases=["Klonopin", "Rivotril", "K-pins", "Super Valium (street)"],
 category="benzodiazepines", schedule="Schedule IV (US)",
 appearance="White/orange scored tablets (0.5–2 mg); Rivotril common in EU/LatAm",
 effects=["Long-acting calm, anti-anxiety, anti-seizure"],
 risks=["Long half-life — dependence builds silently", "Withdrawal can last months"],
 overdoseSigns=["Extreme drowsiness", "Slow breathing with mixes", "Impaired coordination"],
 streetPrice="~$1–$5 per 2 mg tablet (diverted)",
 legalStatus="Rx-only, Schedule IV; felony without prescription",
 lastUpdated="2026-09-12", sources=["NIDA","DEA"]),

dict(slug="nitrazepam", name="Nitrazepam (Nipam 5 mg)", aliases=["Nipam", "Mogadon", "Nitrazadon"],
 category="benzodiazepines", schedule="Schedule IV (US) / Class C (UK)",
 appearance="White 5 mg tablets (Nipam/Mogadon imprint)",
 effects=["Strong hypnotic — sleep induction, sedation"],
 risks=["Morning 'hangover' impairment", "Dependence and falls in older users"],
 overdoseSigns=["Deep sedation", "Slow breathing", "Confusion"],
 streetPrice="~$1–$4 per 5 mg tablet (diverted)",
 legalStatus="Rx-only; controlled in all target regions",
 lastUpdated="2026-09-12", sources=["EMCDDA","NHS"]),

dict(slug="bromazepam", name="Bromazepam (Lexotan 6 mg)", aliases=["Lexotan", "Bromaz", "Lexotanil"],
 category="benzodiazepines", schedule="Schedule IV (US) / controlled EU",
 appearance="Pink/red or white tablets (3/6 mg), 'Lexotanil 6' imprint",
 effects=["Anxiety relief, calm, moderate sedation"],
 risks=["Dependence; withdrawal anxiety rebound"],
 overdoseSigns=["Sedation", "Slurred speech", "Slow breathing in combination"],
 streetPrice="~$1–$5 per 6 mg tablet (diverted)",
 legalStatus="Rx-only; controlled in US, EU, Canada, Australia",
 lastUpdated="2026-09-12", sources=["EMCDDA","DEA"]),

dict(slug="etizolam", name="Etizolam", aliases=["Etiz", "Etilaam", "Etizest", "Passionflower (branded)"],
 category="benzodiazepines", schedule="Not federally scheduled (US) — controlled in AL/AR/FL/OH/TX/VA etc.; banned UK 2017",
 appearance="Pink/blue 1 mg tablets or pink round pellets ('pellets'); blotters",
 effects=["Fast anxiety relief and sedation, short-acting"],
 risks=["Extremely popular RC benzo — dependence sneaks up fast", "Fake 'Xanax' bars often contain etizolam or stronger analogues"],
 overdoseSigns=["Sedation", "Amnesia", "Respiratory depression when mixed"],
 streetPrice="~$0.50–$3 per 1 mg tablet/pellet",
 legalStatus="Legal gray zone federally (US); illegal in UK, Germany, several US states; Rx in Italy/India/Japan",
 lastUpdated="2026-09-12", sources=["EMCDDA","TripSit","Erowid"]),

dict(slug="clonazolam", name="Clonazolam", aliases=["C-lam", "Clonitrazolam"],
 category="benzodiazepines", schedule="Schedule I (US, 2023)",
 appearance="White/pink powders, blotters, or pressed 'pellets' sold online",
 effects=["Very potent, long-lasting sedation and calm — active at ~0.5 mg"],
 risks=["Potency ≈ 2–4× alprazolam; blackouts and delusions of sobriety", "Withdrawal after short use due to potency"],
 overdoseSigns=["Deep unconsciousness", "Respiratory depression in mixes", "Amnesia"],
 streetPrice="~$1–$5 per 0.5 mg equivalent",
 legalStatus="Schedule I (US, 2023); controlled/prohibited across EU, UK, Canada, Australia",
 lastUpdated="2026-09-12", sources=["DEA","EMCDDA","TripSit"]),

dict(slug="diclazepam", name="Diclazepam", aliases=["Chlorodiazepam", "2'-chloro-diazepam"],
 category="benzodiazepines", schedule="Prosecutable under Analogue Act (US); banned UK 2017",
 appearance="White powder or pellets; rarely seen as tablets",
 effects=["Long-acting (24–48 h) calm, muscle relaxation"],
 risks=["Accumulation with repeated dosing", "Protracted withdrawal"],
 overdoseSigns=["Sedation", "Impaired coordination", "Slow breathing with mixes"],
 streetPrice="~$1–$4 per pellet equivalent",
 legalStatus="Analogue prosecutions (US); controlled in UK/EU; check locally",
 lastUpdated="2026-09-12", sources=["EMCDDA","TripSit"]),

dict(slug="flubromazepam", name="Flubromazepam", aliases=["F-Pam", "JYI 28"],
 category="benzodiazepines", schedule="Prosecutable as analogue (US); Class C (UK)",
 appearance="White/off-white powder or 4–8 mg pellets/tablets",
 effects=["Very long-acting (up to 3 days) sedation and calm"],
 risks=["Extreme duration — multi-day impairment and dangerous accumulation", "Withdrawal can last weeks"],
 overdoseSigns=["Prolonged sedation", "Confusion", "Slow breathing with other depressants"],
 streetPrice="~$1–$5 per 4–8 mg equivalent",
 legalStatus="Analogue Act (US); Class C UK; controlled in parts of EU",
 lastUpdated="2026-09-12", sources=["EMCDDA","TripSit","NPS-AD"]),

dict(slug="flubromazolam", name="Flubromazolam", aliases=["F-Lam", "JYI 73"],
 category="benzodiazepines", schedule="Schedule I (US, 2023)",
 appearance="White powder, blotters, pellets; active at ~0.25 mg",
 effects=["Ultra-potent, ultra-long sedative-hypnotic effects"],
 risks=["Blackout doses are close to active doses", "Detected in many fake-Xanax and fake-Valium supplies"],
 overdoseSigns=["Unconsciousness", "Respiratory depression", "Days-long sedation"],
 streetPrice="~$1–$4 per 0.25 mg equivalent",
 legalStatus="Schedule I (US, 2023); controlled UK/EU/Canada",
 lastUpdated="2026-09-12", sources=["DEA","EMCDDA"]),

dict(slug="flunitrazepam", name="Flunitrazepam (Rohypnol)", aliases=["Rohypnol", "Rophies", "Roofies", "Narcozep"],
 category="benzodiazepines", schedule="Not approved in US; Schedule IV-III equivalent elsewhere; 'date-rape drug' class",
 appearance="White 1–2 mg tablets (old ones turned blue in drinks); clear odorless liquid",
 effects=["Heavy sedation, amnesia, muscle relaxation within 20–30 min"],
 risks=["Anterograde amnesia — linked to drug-facilitated assault", "10× stronger hangover sedation than diazepam"],
 overdoseSigns=["Total sedation", "Confusion", "Respiratory depression with alcohol — often fatal"],
 streetPrice="~$2–$10 per 2 mg tablet where diverted",
 legalStatus="Rx-only in ~60 countries; not manufactured for US; illegal without Rx everywhere on our list",
 lastUpdated="2026-09-12", sources=["NIDA","EMCDDA","UNODC"]),

dict(slug="meclonazepam", name="Meclonazepam", aliases=["MBZ"],
 category="benzodiazepines", schedule="Analogue prosecutions (US); controlled several EU states",
 appearance="White powder or pellets, 3–6 mg typical",
 effects=["Anxiolytic, muscle relaxant — clonazepam-like"],
 risks=["Limited human data — unknown long-term harms", "Dependence assumed class-typical"],
 overdoseSigns=["Sedation", "Motor impairment", "Slow breathing with mixes"],
 streetPrice="~$1–$4 per pellet equivalent",
 legalStatus="Analogue Act (US); scheduled in parts of EU — check locally",
 lastUpdated="2026-09-12", sources=["TripSit","EMCDDA","NPS-AD"]),

dict(slug="phenazepam", name="Phenazepam", aliases=["Phenaz", "Bromdihydrochlorphenylbenzodiazepine"],
 category="benzodiazepines", schedule="Not scheduled federally (US) — state-level bans; Rx in Russia/CIS",
 appearance="White 1–2.5 mg tablets (Russian pharma), or white powder",
 effects=["Long-acting strong anxiolytic/sedative; used for epilepsy in CIS"],
 risks=["Linked to serious car crashes and deaths in CIS countries", "Dose errors common with raw powder"],
 overdoseSigns=["Deep sedation", "Slow breathing", "Amnesia"],
 streetPrice="~$0.50–$3 per 1 mg tablet",
 legalStatus="Rx in Russia/CIS; unscheduled federally in US (several state bans); controlled EU",
 lastUpdated="2026-09-12", sources=["EMCDDA","NPS-AD","TripSit"]),

dict(slug="pyrazolam", name="Pyrazolam", aliases=["SH-I-04"],
 category="benzodiazepines", schedule="Analogue prosecutions (US); banned UK 2017",
 appearance="White powder/pellets; active at 0.5–2 mg",
 effects=["Pure anti-anxiety with unusually little sedation (for a benzo)"],
 risks=["Still dependence-forming; little euphoria drives redosing"],
 overdoseSigns=["Sedation at high doses", "Impairment", "Slow breathing in mixes"],
 streetPrice="~$1–$4 per mg-equivalent",
 legalStatus="Analogue Act (US); Class C UK; check EU locally",
 lastUpdated="2026-09-12", sources=["TripSit","EMCDDA"]),

# ---------------- SEDATIVES / HYPNOTICS / OTHER DEPRESSANTS ----------------
dict(slug="zolpidem", name="Zolpidem (Ambien/Stilnox)", aliases=["Ambien", "Stilnox", "Z-drugs", "A-minus"],
 category="sedatives", schedule="Schedule IV (US)",
 appearance="White/pink oblong tablets (5–10 mg); 'Ambien' imprint",
 effects=["Sleep induction within 15 min; mild euphoria and amnesia at higher doses"],
 risks=["Sleep-walking, sleep-driving, hallucinations", "Dependence and rebound insomnia"],
 overdoseSigns=["Extreme sedation", "Confusion", "Respiratory depression with other depressants"],
 streetPrice="~$2–$10 per 10 mg tablet (diverted)",
 legalStatus="Rx-only, Schedule IV; felony without prescription",
 lastUpdated="2026-09-12", sources=["FDA","NIDA"]),

dict(slug="secobarbital", name="Secobarbital (Seconal)", aliases=["Seconal", "Reds", "Red devils", "F-40s"],
 category="sedatives", schedule="Schedule II (US)",
 appearance="Red-orange capsules (50–100 mg)",
 effects=["Rapid deep sedation, euphoria, disinhibition"],
 risks=["Barbiturates: tiny margin between dose and death", "Fatal in overdose, brutal withdrawal (seizures) — replaced by benzos in medicine"],
 overdoseSigns=["Deep coma", "Slow/absent breathing", "Hypothermia, blisters"],
 streetPrice="~$15–$40 per capsule where diverted (rare)",
 legalStatus="Rx-only, Schedule II; felony without prescription",
 lastUpdated="2026-09-12", sources=["NIDA","DEA"]),

dict(slug="soma", name="Carisoprodol (Soma)", aliases=["Soma", "Carisoma", "Vanadom"],
 category="sedatives", schedule="Schedule IV (US, 2012)",
 appearance="White 250/350 mg tablets; 'Soma' imprint",
 effects=["Muscle relaxation, sedation, mild euphoria (via meprobamate metabolite)"],
 risks=["Converts to meprobamate (Miltown) — dependence", "Popular 'Soma Coma' mix with opioids — deadly"],
 overdoseSigns=["Extreme drowsiness", "Low blood pressure", "Slow breathing with opioids"],
 streetPrice="~$1–$8 per 350 mg tablet (diverted)",
 legalStatus="Rx-only, Schedule IV (US); OTC in some countries (Mexico)",
 lastUpdated="2026-09-12", sources=["DEA","FDA"]),

dict(slug="cyclobenzaprine", name="Cyclobenzaprine (Flexeril)", aliases=["Flexeril", "Cyclobenz", "Merck tabs"],
 category="sedatives", schedule="Not scheduled (US)",
 appearance="Yellow/orange 10 mg tablets (Merck); white 5 mg",
 effects=["Muscle relaxation, sedation; little euphoria"],
 risks=["Overdose causes hallucinations, seizures, heart rhythm problems", "Abuse usually in combination (potentiates opioids)"],
 overdoseSigns=["Agitation then sedation", "Fast/irregular heartbeat", "Seizures, confusion"],
 streetPrice="~$1–$5 per 10 mg tablet",
 legalStatus="Rx-only (not federally controlled); prescription misuse is still illegal",
 lastUpdated="2026-09-12", sources=["FDA","NIH"]),

dict(slug="nembutal", name="Pentobarbital (Nembutal)", aliases=["Nembutal", "Yellow jackets", "Pentobarbs"],
 category="sedatives", schedule="Schedule II (US)",
 appearance="Yellow capsules, pink injectable solution (veterinary), powder",
 effects=["Fast deep sedation → anesthesia"],
 risks=["Veterinary euthanasia drug — overdose is usually fatal", "Narrow safety margin (barbiturate)"],
 overdoseSigns=["Coma", "Absent breathing", "Pupils dilated then fixed"],
 streetPrice="~$30–$100+ per vial/capsule-equivalent (rare, diverted)",
 legalStatus="Rx-only, Schedule II; used in physician-assisted death in some jurisdictions under strict law",
 lastUpdated="2026-09-12", sources=["DEA","FDA"]),

dict(slug="ghb", name="GHB (gamma-hydroxybutyrate)", aliases=["G", "Liquid ecstasy", "Grievous Bodily Harm", "Scoop"],
 category="depressants", schedule="Schedule I/III (US — illicit GHB is I; approved drug Xyrem is III)",
 appearance="Clear, salty/soapy-tasting liquid; white powder; clear capsules",
 effects=["Euphoria, disinhibition, increased sociability; sleep at higher doses"],
 risks=["Dose curve is razor-thin — 1 mL too much = coma", "Frequent dosing needed (90-min half-life) → dependence and brutal 24/7 withdrawal", "Also linked to drug-facilitated assault"],
 overdoseSigns=["Sudden deep sleep/unrousable", "Vomiting while unconscious", "Slow irregular breathing"],
 streetPrice="~$5–$20 per dose (capful); ~$60–$150 per 100 mL where found",
 legalStatus="Schedule I (illicit) US; Class B/C elsewhere — illegal without Rx everywhere listed",
 lastUpdated="2026-09-12", sources=["NIDA","EMCDDA","TripSit"]),

dict(slug="ghb-liquid", name="GHB Liquid", aliases=["G liquid", "Liquid G"],
 category="depressants", schedule="Schedule I (US, illicit)",
 appearance="Clear oily liquid in water bottles or vials; salty/soapy taste",
 effects=["Same as GHB — euphoria, disinhibition, sleep"],
 risks=["Concentration unknown — strength varies bottle to bottle", "Mixing with alcohol frequently fatal"],
 overdoseSigns=["Unrousable sleep", "Snoring/gurgling", "Slow breathing"],
 streetPrice="~$60–$150 per 100 mL (strength varies)",
 legalStatus="Illegal without prescription (all target regions)",
 lastUpdated="2026-09-12", sources=["NIDA","EMCDDA"]),

dict(slug="ghb-powder", name="GHB Powder", aliases=["NaGHB", "Sodium oxybate (pharma)"],
 category="depressants", schedule="Schedule I (US, illicit); III for approved Xyrem",
 appearance="White crystalline powder (hygroscopic)",
 effects=["Same as GHB liquid when dissolved"],
 risks=["Dissolving errors → misdosing", "Hygroscopic powder clumps — uneven concentration"],
 overdoseSigns=["Coma-like sleep", "Vomiting", "Respiratory depression"],
 streetPrice="~$40–$120 per 50 g where found",
 legalStatus="Illegal without prescription (all target regions)",
 lastUpdated="2026-09-12", sources=["NIDA","EMCDDA"]),

dict(slug="gbl", name="GBL (gamma-butyrolactone)", aliases=["GBL", "Liquid gold", "Blue nitro", "Firestrip"],
 category="depressants", schedule="Schedule I (US, 2000); controlled UK/EU/AU",
 appearance="Clear liquid with chemical/cologne smell; industrial solvent",
 effects=["Converts to GHB in the body — euphoria, sedation"],
 risks=["Stronger and faster than GHB; dosing even more unforgiving", "Caustic — burns mouth/esophagus undiluted", "Severe dependence with life-threatening withdrawal"],
 overdoseSigns=["Deep unconsciousness", "Slow breathing", "Incontinence"],
 streetPrice="~$50–$150 per liter (industrial-sourced)",
 legalStatus="Schedule I (US); Class B UK; controlled EU/AU/CA — industrial chemical restrictions apply",
 lastUpdated="2026-09-12", sources=["EMCDDA","NIDA","Home Office"]),

dict(slug="ketamine", name="Ketamine", aliases=["K", "Special K", "Kit Kat", "Ketalar"],
 category="dissociatives", schedule="Schedule III (US)",
 appearance="White crystalline powder; clear injectable liquid (Ketalar vials)",
 effects=["Dissociation (out-of-body), euphoria, pain relief; sedative at higher doses"],
 risks=["Bladder damage (ketamine cystitis) with regular use", "K-holes and accidents while impaired", "Dependence with heavy use"],
 overdoseSigns=["Unresponsive but eyes open", "Slow breathing (rarely fatal alone)", "Vomiting while sedated"],
 streetPrice="~$20–$60 per gram; vials $30–$100",
 legalStatus="Rx-only, Schedule III; illegal without prescription; Class B UK",
 lastUpdated="2026-09-12", sources=["NIDA","EMCDDA"]),

dict(slug="ketalar", name="Ketalar (ketamine injection)", aliases=["Ketalar", "Vials", "K vials"],
 category="dissociatives", schedule="Schedule III (US)",
 appearance="Clear liquid in 10/50 mg-per-mL vials, pharmaceutical packaging",
 effects=["Same as ketamine — dissociation, anesthesia"],
 risks=["IV use raises infection and dependence risk", "Bladder harm identical to powder use"],
 overdoseSigns=["Deep sedation", "Slow breathing with other depressants", "Unresponsive"],
 streetPrice="~$30–$100 per vial (diverted)",
 legalStatus="Rx/hospital-only, Schedule III; felony without prescription",
 lastUpdated="2026-09-12", sources=["FDA","NIDA"]),

dict(slug="2f-dck", name="2F-DCK (2-fluorodeschloroketamine)", aliases=["2F-K", "2FDCK"],
 category="dissociatives", schedule="Analogue prosecutions (US); scheduled Germany/UK/others",
 appearance="White/off-white crystals or powder",
 effects=["Ketamine-like dissociation, slightly longer duration"],
 risks=["Very little human safety data", "Bladder toxicity assumed similar to ketamine"],
 overdoseSigns=["Sedation", "Dissociative panic", "Slow breathing with depressants"],
 streetPrice="~$25–$60 per gram",
 legalStatus="Analogue Act (US); scheduled in DE/UK/NL/others — check locally",
 lastUpdated="2026-09-12", sources=["EMCDDA","TripSit","NPS-AD"]),
]

DRUGS += [
# ---------------- STIMULANTS ----------------
dict(slug="cocaine", name="Cocaine", aliases=["Coke", "Blow", "Snow", "Charlie", "Yayo", "Peruvian/Colombian"],
 category="stimulants", schedule="Schedule II (US)",
 appearance="White crystalline powder (HCl) or off-white 'base'/crack rocks; shiny 'fishscale' = high purity HCl",
 effects=["Euphoria, confidence, energy", "Numbing (local anesthetic)", "Suppressed appetite and sleep"],
 risks=["Heart attack/stroke even in young users", "Severe addiction — craving cycle", "Adulterants: levamisole (rotting flesh), fentanyl (overdose)"],
 overdoseSigns=["Chest pain, racing irregular heartbeat", "Seizures", "Extreme agitation, overheating"],
 streetPrice="~$60–$120 per gram (US); £40–£80 (UK); varies widely",
 legalStatus="Schedule II (US); Class A (UK); illegal for non-medical use everywhere listed",
 lastUpdated="2026-09-12", sources=["NIDA","DEA","EMCDDA"]),

dict(slug="speed", name="Speed (amphetamine paste)", aliases=["Amphetamine", "Base", "Paste", "Sulph", "Whizz"],
 category="stimulants", schedule="Schedule II (US, as amphetamine)",
 appearance="Damp white/yellowish paste or dry white powder; damp = high purity base",
 effects=["Energy, alertness, talkativeness", "Appetite suppression", "Euphoria at higher doses"],
 risks=["Insomnia, anxiety, paranoia", "Heart strain and overheating", "Cut with caffeine, glucose, ephedrine, or worse"],
 overdoseSigns=["Chest pain", "Panic, hallucinations", "Overheating, fast irregular pulse"],
 streetPrice="~$10–$40 per gram (EU); £10–£30 (UK)",
 legalStatus="Schedule II/controlled everywhere listed; Rx forms exist (Adderall, Dexedrine)",
 lastUpdated="2026-09-12", sources=["NIDA","EMCDDA","UNODC"]),

dict(slug="methamphetamine", name="Methamphetamine", aliases=["Meth", "Crystal", "Ice", "Glass", "Tina", "Crank"],
 category="stimulants", schedule="Schedule II (US)",
 appearance="Clear/white crystal shards ('ice'), powder, or pills",
 effects=["Intense euphoria, energy, focus lasting 6–12 h", "Suppressed appetite/sleep", "Confidence, hypersexuality"],
 risks=["Addiction — among the most addictive drugs known", "Meth mouth, skin sores, psychosis", "Overdose: stroke, heart failure, overheating"],
 overdoseSigns=["Chest pain, arrhythmia", "Extreme agitation, paranoia", "High fever, seizures"],
 streetPrice="~$20–$100 per gram (US); varies by region",
 legalStatus="Schedule II (US); Class A UK; illegal without Rx everywhere listed",
 lastUpdated="2026-09-12", sources=["NIDA","DEA","EMCDDA"]),

dict(slug="adderall", name="Adderall (amphetamine salts)", aliases=["Adderall IR", "Speed (diverted)", "Study drug"],
 category="stimulants", schedule="Schedule II (US)",
 appearance="Blue/peach round tablets (5–30 mg IR), imprint 'AD'",
 effects=["Focus, wakefulness, mild euphoria"],
 risks=["Dependence and tolerance", "Cardiovascular strain", "Counterfeits contain meth or caffeine-heavy mixes"],
 overdoseSigns=["Racing heart, chest pain", "Panic, aggression", "Overheating"],
 streetPrice="~$3–$15 per 30 mg tablet (diverted)",
 legalStatus="Rx-only, Schedule II; felony without prescription",
 lastUpdated="2026-09-12", sources=["FDA","DEA","NIDA"]),

dict(slug="adderall-xr", name="Adderall XR", aliases=["XR beads", "Extended-release Adderall"],
 category="stimulants", schedule="Schedule II (US)",
 appearance="Capsules (10–30 mg) with two-tone beads (half IR, half delayed)",
 effects=["10–12 h focus/wakefulness, smoother than IR"],
 risks=["Same as Adderall; long duration masks sleep debt", "Beads snorted bypass XR mechanism"],
 overdoseSigns=["Racing heart", "Insomnia mania", "Chest pain"],
 streetPrice="~$5–$20 per 30 mg capsule (diverted)",
 legalStatus="Rx-only, Schedule II; felony without prescription",
 lastUpdated="2026-09-12", sources=["FDA","DEA"]),

dict(slug="ritalin", name="Methylphenidate (Ritalin)", aliases=["Ritalin", "Concerta", "Methylin", "Rids", "JIF"],
 category="stimulants", schedule="Schedule II (US)",
 appearance="White/yellow 5–20 mg tablets; Concerta = long grey/red-brown pills",
 effects=["Focus, alertness, mild euphoria (shorter than amphetamine)"],
 risks=["Dependence; cardiovascular strain", "Injecting crushed tablets causes lung damage"],
 overdoseSigns=["Racing heart", "Agitation, hallucinations", "Seizures"],
 streetPrice="~$2–$10 per 20 mg tablet (diverted)",
 legalStatus="Rx-only, Schedule II; felony without prescription",
 lastUpdated="2026-09-12", sources=["FDA","DEA"]),

dict(slug="ephedrine", name="Ephedrine", aliases=["Ephedra", "Ma Huang", "Mini-thins"],
 category="stimulants", schedule="Not scheduled (US) — regulated sale (combat-meth laws)",
 appearance="White 25–30 mg tablets, powder, or dried herb",
 effects=["Stimulant, bronchodilator, appetite suppression"],
 risks=["Heart palpitations, blood pressure spikes", "Stroke at high doses", "Pre-cursor to meth — heavily watched"],
 overdoseSigns=["Racing heart", "Tremor, anxiety", "Severe hypertension"],
 streetPrice="~$0.50–$3 per tablet (retail-regulated)",
 legalStatus="OTC-regulated US (behind counter, ID + limits); Rx/controlled in many EU states",
 lastUpdated="2026-09-12", sources=["FDA","EMCDDA"]),

dict(slug="pseudoephedrine", name="Pseudoephedrine HCl", aliases=["Pseudo", "Sudafed", "PSE"],
 category="stimulants", schedule="Not scheduled — retail restricted (US); Rx in some countries",
 appearance="White 30/60 mg tablets; red-hot precursor to meth",
 effects=["Mild stimulant, nasal decongestant"],
 risks=["Hypertension, arrhythmia", "Meth-lab precursor — purchase tracked"],
 overdoseSigns=["Racing heart", "Severe headache", "Hallucinations (high dose)"],
 streetPrice="Retail ~$5–$15 per box (tracked)",
 legalStatus="Behind-the-counter with ID in US; Rx-only in several EU/CA states; export-restricted",
 lastUpdated="2026-09-12", sources=["FDA","DEA"]),

# RC & club stimulants
dict(slug="4-fa", name="4-FA (4-fluoroamphetamine)", aliases=["4-FMP", "Palladium"],
 category="stimulants", schedule="Analogue prosecutions (US); banned NL/UK/others",
 appearance="White/off-white powder or capsules",
 effects=["MDMA-like empathy + amphetamine energy, 4–6 h"],
 risks=["Serotonin neurotoxicity suspected (like MDMA analogues)", "Overheating in clubs"],
 overdoseSigns=["Racing heart, hypertension", "Overheating", "Serotonin-syndrome signs: agitation, clonus"],
 streetPrice="~$10–$30 per gram",
 legalStatus="Analogue Act (US); controlled NL/UK/DE/others — check locally",
 lastUpdated="2026-09-12", sources=["EMCDDA","TripSit"]),

dict(slug="mephedrone", name="Mephedrone (4-MMC)", aliases=["4-MMC", "Meow Meow", "M-Cat", "Drone", "Bubbles"],
 category="stimulants", schedule="Schedule I (US, 2011); Class B UK",
 appearance="White/off-white crystals or powder (crystals = '4-MMC crystals')",
 effects=["Euphoria, empathy, energy, strong urge to redose"],
 risks=["Cardiovascular strain; compulsive redosing", "Serotonin depletion crashes; psychosis with binges"],
 overdoseSigns=["Racing irregular heart", "Overheating, sweating", "Agitation, seizures"],
 streetPrice="~$15–$40 per gram",
 legalStatus="Schedule I (US); Class B UK; controlled EU/AU",
 lastUpdated="2026-09-12", sources=["EMCDDA","NIDA","Home Office"]),

dict(slug="4-mmc-crystals", name="4-MMC crystals", aliases=["Crystal meph", "Mephedrone crystal"],
 category="stimulants", schedule="Schedule I (US); Class B UK",
 appearance="Translucent/white crystalline shards sold as 'pure mephedrone'",
 effects=["Identical to mephhedrone — euphoria, energy, empathy"],
 risks=["Identical harms to mephedrone; 'crystal' purity claims are unverifiable"],
 overdoseSigns=["Racing heart", "Overheating", "Severe agitation"],
 streetPrice="~$20–$50 per gram",
 legalStatus="Same as mephedrone — illegal",
 lastUpdated="2026-09-12", sources=["EMCDDA","NIDA"]),

dict(slug="methylone", name="Methylone (bk-MDMA)", aliases=["M1", "bk-MDMA", "Explosion"],
 category="stimulants", schedule="Schedule I (US, 2013)",
 appearance="White/tan powder, crystals, or pressed 'Molly' pills",
 effects=["MDMA-lite: euphoria, empathy, stimulation"],
 risks=["Often sold as MDMA — users dose it like MDMA but it behaves differently", "Serotonin syndrome risk with antidepressants"],
 overdoseSigns=["Overheating", "Racing heart", "Agitation, confusion"],
 streetPrice="~$10–$30 per gram or $5–$15 per pill",
 legalStatus="Schedule I (US); controlled EU/UK/CA/AU",
 lastUpdated="2026-09-12", sources=["DEA","EMCDDA","TripSit"]),

dict(slug="pentedrone", name="Pentedrone", aliases=["α-PVP's cousin", "PD"],
 category="stimulants", schedule="Schedule I (US, 2014)",
 appearance="White/tan crystals or powder",
 effects=["Cocaine-like stimulation, short and compulsive"],
 risks=["Strong redose compulsion; days-long binges", "Psychosis, paranoia"],
 overdoseSigns=["Racing heart", "Extreme agitation", "Chest pain"],
 streetPrice="~$15–$40 per gram",
 legalStatus="Schedule I (US); controlled EU/UK/CA/AU",
 lastUpdated="2026-09-12", sources=["DEA","EMCDDA"]),

dict(slug="mdpv", name="MDPV", aliases=["Bath salts", "Magic", "Super Coke"],
 category="stimulants", schedule="Schedule I (US, 2011)",
 appearance="White/off-white powder or crystals; sold as 'bath salts'/'plant food'",
 effects=["Intense, long (6–8 h) stimulation; dopamine-heavy euphoria"],
 risks=["The original 'bath salts' panic drug — psychosis, self-harm reports", "Very compulsive redosing"],
 overdoseSigns=["Severe agitation, paranoia", "Racing heart, hypertension", "Hyperthermia, seizures"],
 streetPrice="~$15–$40 per gram",
 legalStatus="Schedule I (US); controlled everywhere listed",
 lastUpdated="2026-09-12", sources=["DEA","NIDA","EMCDDA"]),

dict(slug="a-pvp", name="α-PVP (Flakka)", aliases=["Flakka", "α-PVP", "Beta-pvp (β-PVP)", "Gravel"],
 category="stimulants", schedule="Schedule I (US, 2014)",
 appearance="White/pink crystals or powder ('gravel')",
 effects=["Powerful, hours-long stimulation, euphoria"],
 risks=["Notorious for psychotic episodes ('flakka zombies' media panic)", "Extreme compulsive redosing"],
 overdoseSigns=["Severe paranoia, hallucinations", "Racing heart", "Overheating, violence risk"],
 streetPrice="~$10–$30 per gram",
 legalStatus="Schedule I (US); banned UK 2015; controlled EU/AU",
 lastUpdated="2026-09-12", sources=["DEA","NIDA","EMCDDA"]),

dict(slug="a-php", name="α-PHP", aliases=["PHP", "α-Pyrrolidinohexanophenone"],
 category="stimulants", schedule="Analogue prosecutions (US); controlled DE/UK/others",
 appearance="White/yellow crystals or powder",
 effects=["Very potent stimulant, shorter and sharper than α-PVP"],
 risks=["Binge-compulsion; sleep deprivation psychosis", "Little human data"],
 overdoseSigns=["Racing heart, hypertension", "Paranoia", "Overheating"],
 streetPrice="~$15–$40 per gram",
 legalStatus="Analogue Act (US); scheduled DE/UK/CN — check locally",
 lastUpdated="2026-09-12", sources=["EMCDDA","TripSit","NPS-AD"]),

dict(slug="3cmc-4cmc", name="3-CMC / 4-CMC (clephedrone/chloromethcathinone)", aliases=["3CMC", "4CMC", "Clephedrone", "CMC crystals"],
 category="stimulants", schedule="Controlled in several EU states; analogue prosecutions (US)",
 appearance="White/off-white crystals or powder",
 effects=["Mephedrone-like stimulation and euphoria"],
 risks=["Suspected serotonin neurotoxicity (chlorine atom like para-chloroamphetamine)", "Cardiovascular strain"],
 overdoseSigns=["Racing heart", "Overheating", "Agitation"],
 streetPrice="~$15–$35 per gram",
 legalStatus="Banned DE/UK/NL/others; Analogue Act US — check locally",
 lastUpdated="2026-09-12", sources=["EMCDDA","NPS-AD","TripSit"]),

dict(slug="4-mar", name="4-Methylaminorex (4-MAR)", aliases=["U4Euh", "Euphoria", "Ice (mistakenly)"],
 category="stimulants", schedule="Schedule I (US)",
 appearance="White crystalline powder or small pellets",
 effects=["Long-lasting (8–12 h) amphetamine-like euphoria and energy"],
 risks=["Pulmonary hypertension linked to aminorex family", "Insomnia, anxiety, vasoconstriction"],
 overdoseSigns=["Chest pain, hypertension", "Racing heart", "Severe agitation"],
 streetPrice="~$20–$50 per gram (rare)",
 legalStatus="Schedule I (US); controlled EU/CA/AU",
 lastUpdated="2026-09-12", sources=["DEA","TripSit"]),

dict(slug="4-fluorococaine", name="4′-Fluorococaine", aliases=["pFC", "Fluorococaine"],
 category="stimulants", schedule="Analogue prosecutions (US); controlled several EU states",
 appearance="White powder mimicking cocaine",
 effects=["Cocaine-like local anesthetic + stimulation"],
 risks=["Sold as or mixed into cocaine — buyers can't tell the difference", "Little human safety data"],
 overdoseSigns=["Racing heart", "Chest pain", "Agitation"],
 streetPrice="Priced with cocaine markets (~$60–$120/g)",
 legalStatus="Analogue Act (US); scheduled in parts of EU — check locally",
 lastUpdated="2026-09-12", sources=["EMCDDA","NPS-AD"]),

dict(slug="camfetamine", name="Camfetamine", aliases=["CF", "N-methyl-3-phenyl-norbornan-2-amine"],
 category="stimulants", schedule="Analogue prosecutions (US); controlled several EU states",
 appearance="White/off-white powder or pellets",
 effects=["Amphetamine-like stimulation, euphoria"],
 risks=["Little published human data", "Class-typical cardiovascular strain"],
 overdoseSigns=["Racing heart", "Hypertension", "Agitation"],
 streetPrice="~$15–$40 per gram",
 legalStatus="Analogue Act (US); banned UK 2017; check EU locally",
 lastUpdated="2026-09-12", sources=["EMCDDA","TripSit","NPS-AD"]),

dict(slug="ethylphenidate", name="Ethylphenidate", aliases=["EP", "Ethyl DP"],
 category="stimulants", schedule="Analogue prosecutions (US); banned UK 2016",
 appearance="White crystalline powder",
 effects=["Ritalin-like focus and stimulation, short-acting"],
 risks=["Vasoconstriction reports — painful extremities", "Compulsive redosing"],
 overdoseSigns=["Racing heart", "Cold/numb fingers and toes", "Agitation"],
 streetPrice="~$15–$35 per gram",
 legalStatus="Analogue Act (US); Class B UK; scheduled parts of EU",
 lastUpdated="2026-09-12", sources=["EMCDDA","TripSit"]),

dict(slug="mpa", name="Methiopropamine (MPA)", aliases=["MPA", "Blow (UK, misleadingly)"],
 category="stimulants", schedule="Banned UK 2015; analogue prosecutions (US)",
 appearance="White/off-white crystals or powder",
 effects=["Mild-moderate stimulation, focus, long duration"],
 risks=["Thiophene ring — unknown long-term metabolism", "Class-typical heart strain"],
 overdoseSigns=["Racing heart", "Insomnia mania", "Hypertension"],
 streetPrice="~$15–$35 per gram",
 legalStatus="Class B UK (2015); Analogue Act US; check EU locally",
 lastUpdated="2026-09-12", sources=["EMCDDA","TripSit"]),

dict(slug="troparil", name="Troparil (β-CPT, WIN 35,428)", aliases=["β-CPT", "Troparil powder"],
 category="stimulants", schedule="Analogue prosecutions (US); limited scheduling history",
 appearance="White crystalline powder (research chemical)",
 effects=["Dopamine reuptake inhibition — cocaine-like stimulation"],
 risks=["Almost no human data — animal-research compound only", "Potency unknown outside lab settings"],
 overdoseSigns=["Racing heart", "Agitation", "Hypertension"],
 streetPrice="~$30–$80 per gram (rare)",
 legalStatus="Analogue Act (US); unscheduled in much of EU — check locally",
 lastUpdated="2026-09-12", sources=["TripSit","NPS-AD","Erowid"]),

dict(slug="synthacaine", name="Synthacaine", aliases=["Synthetic cocaine", "NEB/Dimethocaine blends"],
 category="stimulants", schedule="Components prosecuted as analogues (US)",
 appearance="White powder sold as 'legal cocaine' (usually dimethocaine + caffeine + lidocaine blends)",
 effects=["Weak local-anesthetic numbness + mild stimulation"],
 risks=["Marketing implies cocaine-like effects that aren't delivered — users escalate dose", "Variable unknown blends"],
 overdoseSigns=["Racing heart (from hidden stimulants)", "Chest pain", "Agitation"],
 streetPrice="~$20–$50 per gram",
 legalStatus="Blend-dependent; dimethocaine controlled in several EU states; Analogue Act US",
 lastUpdated="2026-09-12", sources=["EMCDDA","TripSit"]),

dict(slug="beta-pvp", name="β-PVP (beta-pyrrolidinovalerophenone)", aliases=["β-PVP", "Beta-PVP"],
 category="stimulants", schedule="Analogue prosecutions (US); controlled several EU states",
 appearance="White/yellowish crystals or powder",
 effects=["α-PVP-like stimulation, euphoria"],
 risks=["Same bath-salts profile: psychosis, binges", "Little human data"],
 overdoseSigns=["Severe agitation", "Racing heart", "Overheating"],
 streetPrice="~$15–$40 per gram",
 legalStatus="Analogue Act (US); scheduled in parts of EU/UK — check locally",
 lastUpdated="2026-09-12", sources=["EMCDDA","NPS-AD","TripSit"]),
]

DRUGS += [
# ---------------- EMPATHOGENS ----------------
dict(slug="mdma", name="MDMA", aliases=["Ecstasy (in pill form)", "Molly (powder)", "E", "X", "Adam"],
 category="empathogens", schedule="Schedule I (US)",
 appearance="White/off-white crystals or powder ('Molly'); pressed pills with logos ('XTC')",
 effects=["Euphoria, empathy, emotional closeness", "Energy, enhanced senses", "Music/social enhancement"],
 risks=["Overheating + dehydration (or fatal water intoxication)", "Serotonin depletion — multi-day comedown", "Pills often contain PMA/PMMA (deadly) or cathinones"],
 overdoseSigns=["Overheating, confusion", "Racing heart, seizures", "Jaw clenching, hallucinations"],
 streetPrice="~$10–$40 per pill; ~$30–$80 per gram powder",
 legalStatus="Schedule I (US); Class A UK; controlled everywhere listed",
 lastUpdated="2026-09-12", sources=["NIDA","DEA","EMCDDA"]),

dict(slug="molly", name="Molly (MDMA powder)", aliases=["Molly", "Mandy (UK)", "Moon rocks"],
 category="empathogens", schedule="Schedule I (US)",
 appearance="White/cream/purple-tinged crystalline powder or 'rocks'",
 effects=["Same as MDMA — euphoria, empathy, energy"],
 risks=["'Molly' is a marketing term, not a guarantee — half of seized 'Molly' contains other drugs", "Overheating, serotonin syndrome with antidepressants"],
 overdoseSigns=["Overheating", "Confusion, seizures", "Racing heart"],
 streetPrice="~$30–$80 per gram",
 legalStatus="Same as MDMA — Schedule I / Class A / controlled",
 lastUpdated="2026-09-12", sources=["NIDA","DEA"]),

dict(slug="xtc-pills", name="XTC Pills (ecstasy tablets)", aliases=["E pills", "Beans", "Rolls", "Disco biscuits"],
 category="empathogens", schedule="Schedule I (US)",
 appearance="Pressed tablets, every color/logo — Superman, Rolex, Tesla, skulls",
 effects=["4–6 h euphoria, empathy, energy"],
 risks=["High-dose pills (200–300+ mg) cause severe toxicity", "PMA/PMMA masquerading as ecstasy has killed many users (slow onset → double-dosing)"],
 overdoseSigns=["Body temperature >40°C / 104°F", "Seizures, rigid muscles", "Confusion, hallucinations"],
 streetPrice="~$10–$40 per pill",
 legalStatus="Schedule I (US); Class A UK; controlled everywhere listed",
 lastUpdated="2026-09-12", sources=["NIDA","EMCDDA","PillReports"]),

dict(slug="5-apb", name="5-APB", aliases=["Benzo Fury (with 6-APB blends)"],
 category="empathogens", schedule="Class B (UK); analogue prosecutions (US)",
 appearance="White/brown powder or pellets",
 effects=["MDA-like empathy + stimulation, 6–10 h duration"],
 risks=["Serotonin release + MAOI-like properties → serotonin syndrome risk", "Long duration complicates dosing"],
 overdoseSigns=["Overheating", "Agitation, clonus", "Racing heart"],
 streetPrice="~$15–$40 per gram or ~$5–$15 per pellet",
 legalStatus="Class B UK; Analogue Act US; controlled in parts of EU — check locally",
 lastUpdated="2026-09-12", sources=["EMCDDA","TripSit"]),

# ---------------- PSYCHEDELICS ----------------
dict(slug="dmt", name="DMT (dimethyltryptamine)", aliases=["The Spirit Molecule", "Deems", "Dimitri", "Businessman's trip"],
 category="psychedelics", schedule="Schedule I (US)",
 appearance="White/yellow crystalline powder; also in ayahuasca plant brews",
 effects=["5–20 min intense visual hallucinations, entity encounters", "Altered sense of reality/time", "Euphoria or terror"],
 risks=["Psychological distress ('bad trips')", "Dangerous behavior if unprepared", "Raises heart rate/blood pressure"],
 overdoseSigns=["No known lethal overdose in pure form — but terror/panic attacks are common", "Fainting, vomiting"],
 streetPrice="~$20–$60 per 50–100 mg dose",
 legalStatus="Schedule I (US); Class A UK; controlled everywhere listed (plant/brew laws vary, e.g. religious exemptions in some countries)",
 lastUpdated="2026-09-12", sources=["NIDA","DEA","MAPS"]),

dict(slug="peyote", name="Peyote (mescaline cactus)", aliases=["Lophophora williamsii", "Buttons", "Cactus"],
 category="psychedelics", schedule="Schedule I (US, except Native American Church ceremonial use)",
 appearance="Small spineless grey-green cactus 'buttons'; dried slices",
 effects=["8–12 h gentle visuals, introspection, euphoria", "Nausea early on"],
 risks=["Severe nausea/vomiting", "Psychological distress", "Slow-growing cactus — ecological harm from overharvesting"],
 overdoseSigns=["No documented lethal overdose", "Extreme nausea, disorientation"],
 streetPrice="~$10–$30 per button where sold",
 legalStatus="Schedule I (US) with NAC religious exemption; controlled in most target regions",
 lastUpdated="2026-09-12", sources=["NIDA","EMCDDA"]),

dict(slug="mescaline", name="Mescaline powder", aliases=["Mesc", "San Pedro extract"],
 category="psychedelics", schedule="Schedule I (US)",
 appearance="White/off-white crystalline powder (extracted) or brownish raw powder",
 effects=["Same as peyote — 8–12 h visuals, euphoria, introspection"],
 risks=["Heavy nausea at dose", "Panic/psychosis in vulnerable users"],
 overdoseSigns=["No known lethal overdose", "Vomiting, agitation"],
 streetPrice="~$20–$60 per dose",
 legalStatus="Schedule I (US); Class A UK; controlled everywhere listed",
 lastUpdated="2026-09-12", sources=["NIDA","EMCDDA","Erowid"]),

dict(slug="2c-b", name="2C-B", aliases=["Nexus", "Bees", "2's"],
 category="psychedelics", schedule="Schedule I (US, since 1995)",
 appearance="White/off-white powder or small pressed pills (often pink/purple)",
 effects=["MDMA-like euphoria at low doses + LSD-like visuals at higher doses, 4–8 h"],
 risks=["Very dose-sensitive — steep curve between fun and overwhelming", "Panic attacks"],
 overdoseSigns=["Extreme agitation, hallucinations", "Hypertension", "Fever"],
 streetPrice="~$10–$30 per pill or ~$50–$120 per gram",
 legalStatus="Schedule I (US); controlled everywhere listed",
 lastUpdated="2026-09-12", sources=["EMCDDA","NIDA","Erowid"]),

dict(slug="4-aco-dmt", name="4-AcO-DMT (psilacetin)", aliases=["4-Acetoxy-DMT", "Synthetic shrooms"],
 category="psychedelics", schedule="Analogue prosecutions (US); controlled Italy/UK-PSA",
 appearance="White/beige powder or fumarate crystals; pressed pellets",
 effects=["Psilocybin-like trip, 4–6 h — visuals, laughter, introspection"],
 risks=["Sold as 'legal mushrooms' — buyers misjudge dose", "Panic, risky behavior"],
 overdoseSigns=["No known lethal overdose", "Extreme anxiety, confusion"],
 streetPrice="~$20–$50 per dose",
 legalStatus="Analogue Act (US); UK Psychoactive Substances Act; scheduled in several EU states",
 lastUpdated="2026-09-12", sources=["TripSit","EMCDDA","Erowid"]),

# ---------------- SYNTHETIC CANNABINOIDS ----------------
dict(slug="4f-adb", name="4F-ADB", aliases=["4F-MDMB-BUTINACA"],
 category="cannabinoids", schedule="Schedule I (US, 2021)",
 appearance="White/yellow powder sprayed onto plant material ('K2/Spice') or in vape carts",
 effects=["Cannabis-like high but far more intense — sedation, confusion, anxiety"],
 risks=["Associated with 'Spice zombies' — catatonia, seizures", "Unpredictable potency sprayed unevenly", "Kidney damage, heart rhythm problems"],
 overdoseSigns=["Severe agitation, psychosis", "Seizures", "Racing heart, vomiting"],
 streetPrice="~$5–$20 per gram of 'herbal blend'",
 legalStatus="Schedule I (US); banned UK/CA/AU/EU-wide",
 lastUpdated="2026-09-12", sources=["DEA","EMCDDA","NPS-AD"]),

dict(slug="5f-adbica", name="5F-ADB / 5F-ADBICA", aliases=["5F-MDMB-PICA", "5F-ADBICA"],
 category="cannabinoids", schedule="Schedule I (US)",
 appearance="White powder sprayed on plant material or dissolved in e-liquid",
 effects=["Sedating, disorienting 'spice' high"],
 risks=["Multiple deaths linked to 5F-ADB (the compound behind early 'zombie spice' outbreaks)", "Seizures, kidney injury"],
 overdoseSigns=["Catatonic state", "Seizures", "Rapid heart rate"],
 streetPrice="~$5–$20 per gram of blend",
 legalStatus="Schedule I (US); banned everywhere on our list",
 lastUpdated="2026-09-12", sources=["DEA","EMCDDA","UNODC"]),

dict(slug="jwh-250", name="JWH-250", aliases=["JWH250"],
 category="cannabinoids", schedule="Schedule I (US, 2011)",
 appearance="White powder on plant material or in 'incense'",
 effects=["Early-generation synthetic cannabinoid — cannabis-like high"],
 risks=["First-generation spice compound; contaminated batches caused outbreaks", "Anxiety, tachycardia"],
 overdoseSigns=["Racing heart", "Panic, paranoia", "Vomiting"],
 streetPrice="~$5–$15 per gram of blend",
 legalStatus="Schedule I (US); banned EU/UK/CA/AU",
 lastUpdated="2026-09-12", sources=["DEA","EMCDDA"]),

dict(slug="nm2201", name="NM-2201 (CBL-2201)", aliases=["NM2201"],
 category="cannabinoids", schedule="Analogue prosecutions (US); controlled EU/UK",
 appearance="Off-white powder sprayed on herbs or in vape liquid",
 effects=["Strong sedating cannabinoid effect"],
 risks=["Little human data", "Severe anxiety, seizures reported"],
 overdoseSigns=["Agitation", "Seizures", "Racing heart"],
 streetPrice="~$5–$20 per gram of blend",
 legalStatus="Analogue Act (US); UK PSA; scheduled in several EU states",
 lastUpdated="2026-09-12", sources=["EMCDDA","TripSit","NPS-AD"]),

# ---------------- PERFORMANCE / MISCELLANEOUS PHARMA ----------------
dict(slug="aicar", name="AICAR (Acadesine)", aliases=["AICA ribonucleotide", "GW501516's twin (grey market)"],
 category="performance", schedule="Unscheduled (US/EU) — banned by WADA",
 appearance="White powder, sold as 'exercise in a pill' grey-market research chemical",
 effects=["AMPK activator — increases endurance at cellular level (animal data only)"],
 risks=["No human safety data — cancer-risk flags in cell studies", "Sold as research chemical, zero quality control"],
 overdoseSigns=["Unknown in humans", "Potential hypoglycemia symptoms"],
 streetPrice="~$50–$150 per gram (grey market)",
 legalStatus="Unscheduled but not approved for human use; prohibited in sport (WADA)",
 lastUpdated="2026-09-12", sources=["WADA","PubMed"]),

dict(slug="clenbuterol", name="Clenbuterol HCl", aliases=["Clen", "Spiropent"],
 category="performance", schedule="Not approved for human use (US); Rx elsewhere",
 appearance="White 20–40 mcg tablets; veterinary liquid",
 effects=["Bronchodilator → fat loss, stimulant-like energy at higher doses"],
 risks=["Racing heart, arrhythmia, tremors", "Overdose: dangerous potassium shifts, cardiac events", "Contaminated meat can cause positive tests"],
 overdoseSigns=["Severe tremor", "Racing irregular heart", "Chest pain, dizziness"],
 streetPrice="~$0.50–$2 per 40 mcg tablet (grey market)",
 legalStatus="Not FDA-approved for humans (US); Rx veterinary/Rx human elsewhere; doping-banned",
 lastUpdated="2026-09-12", sources=["FDA","WADA"]),

dict(slug="arimidex", name="Anastrozole (Arimidex)", aliases=["Arimidex", "Adex"],
 category="performance", schedule="Rx-only (US/EU) — not a controlled drug",
 appearance="White 1 mg tablets, 'Ari' imprints",
 effects=["Aromatase inhibitor — lowers estrogen (used in breast cancer; abused in steroid cycles)"],
 risks=["Bone density loss, joint pain with long-term use", "Crash estrogen too low → depression, libido loss"],
 overdoseSigns=["Nausea, headache", "Hot flashes"],
 streetPrice="~$2–$8 per 1 mg tablet (grey market)",
 legalStatus="Rx-only everywhere listed; not a controlled substance",
 lastUpdated="2026-09-12", sources=["FDA","EMA"]),

dict(slug="cialis", name="Tadalafil (Cialis)", aliases=["Cialis", "Tadalis", "Weekend pill"],
 category="performance", schedule="Rx-only — not controlled",
 appearance="Yellow almond-shaped 10/20 mg tablets; yellow film",
 effects=["36-hour erectile enhancement"],
 risks=["Counterfeit ED pills are a major fentanyl/adulterant channel in some regions", "Dangerous blood pressure drop with nitrates"],
 overdoseSigns=["Prolonged erection (>4 h — medical emergency)", "Chest pain, dizziness"],
 streetPrice="~$2–$15 per tablet (counterfeit); Rx ~$10–$70",
 legalStatus="Rx-only everywhere listed; large counterfeit trade",
 lastUpdated="2026-09-12", sources=["FDA","EMA","Interpol"]),

# ---------------- HAZARDOUS ----------------
dict(slug="potassium-cyanide", name="Potassium Cyanide (KCN)", aliases=["KCN", "Cyanide salts"],
 category="hazardous", schedule="Not a drug — regulated toxic chemical (poisons laws)",
 appearance="White crystalline salt, almond-like odor when damp",
 effects=["NONE — this is not a recreational drug. Blocks cellular oxygen use within minutes"],
 risks=["Lethal dose ~200–300 mg — death within minutes to an hour", "No antidote available outside hospital; hydrogen cyanide gas from acid contact"],
 overdoseSigns=["All exposure is poisoning: gasping, seizures, collapse, cardiac arrest"],
 streetPrice="N/A — sometimes sold fraudulently as 'peaceful exit' scams",
 legalStatus="Heavily regulated toxic chemical; possession without industrial license is a crime in all target regions",
 lastUpdated="2026-09-12", sources=["WHO","CDC","ATSDR"]),
]

DRUGS += [
dict(slug="xylazine", name="Xylazine (Tranq)", aliases=["Tranq", "Tranq dope", "Rompun (vet brand)"],
 category="opioids", schedule="Not a controlled drug — veterinary anesthetic, adulterant",
 appearance="No street form of its own — found mixed into fentanyl/heroin (white/beige powder) or pills",
 effects=["Heavy sedation, slow breathing", "Blackouts lasting hours", "Severe skin wounds (eschar) at injection sites"],
 risks=["Not an opioid — naloxone does NOT reverse it; it still kills breathing", "Flesh-rotting wounds (tranq lesions) that lead to amputation", "Withdrawal on top of opioid withdrawal, hard to treat"],
 overdoseSigns=["Unresponsive with slow breathing", "Blue-gray skin", "Severe hypotension (very low blood pressure)"],
 streetPrice="Sold as part of fentanyl/heroin bags (~$10-$40) — no separate price",
 legalStatus="Veterinary Rx-only; human use illegal; possession varies — often charged by drug weight when mixed",
 lastUpdated="2026-09-12", sources=["NIDA","CDC","DEA"]),
]
