# Editorial content for plugreports.com
# BUSTS: entries marked confirmed=False are scaffolded from user-submitted source links
# and MUST be completed with verified details before publishing. Never invent bust facts.

BUSTS = [
 dict(slug="bust-texas-cabbage-meth", title="2,000+ lbs of meth found packed inside cabbage shipment in South Texas", date="2026-09-12",
  location="Rio Grande Valley, South Texas, USA", agency="DEA / Homeland Security Task Force", confirmed=True,
  sourceUrl="https://vt.tiktok.com/ZSqQyGxJs/",
  summary="DEA agents peeling apart a commercial cabbage shipment in the Rio Grande Valley found more than 2,000 pounds of methamphetamine concealed inside the produce. The seizure is part of a Homeland Security Task Force investigation involving the DEA, HSI, FBI, CBP, Border Patrol and Texas DPS. Authorities have not publicly identified the exact location of the seizure.",
  drugsInvolved=["methamphetamine"],
  sentencing="Federal meth trafficking of 50 g or more carries a 10-year mandatory minimum up to life; multi-agency task force cases are prosecuted federally."),
 dict(slug="bust-spain-banana-cocaine-13t", title="13-ton cocaine haul disguised as banana shipment exposes international network", date="2026-07-20",
  location="Spain (investigation spans US, Dubai, Ireland)", agency="Bloomberg Politics / Spanish authorities", confirmed=True,
  sourceUrl="https://vt.tiktok.com/ZSqQyprWP/",
  summary="A 13-ton haul of cocaine disguised as a banana shipment has exposed alleged links between US financiers, luxury Dubai real estate and a crypto-trading Irish fintech, Bloomberg Politics reports. The case centers on cocaine concealed in fruit shipments entering Spain and a laundering network spanning three continents.",
  drugsInvolved=["cocaine"],
  sentencing="Spain: cocaine trafficking carries roughly 3–6 years, rising to 10+ years and beyond 20 for organized, large-quantity cases; EU coordination means additional member-state charges are likely."),
 dict(slug="bust-australia-sydney-cocaine-record", image="https://plugreports.com/media/drugs/4-fluorococaine.jpeg", title="Largest drug bust in Australian history: nearly $1B cocaine at rural Sydney property", date="2026-06-22",
  location="Rural property, western Sydney, NSW, Australia", agency="AFP-led joint operation (9News Sydney report)", confirmed=True,
  sourceUrl="https://vt.tiktok.com/ZSqQyqJMX/",
  summary="Authorities have executed the largest drug bust in Australian history, uncovering nearly a billion dollars' worth of cocaine at a rural property in western Sydney. Aerial footage shows dozens of shipping containers on the property being examined by investigators.",
  drugsInvolved=["cocaine"],
  sentencing="NSW: supplying a large commercial quantity of cocaine carries up to life imprisonment; Commonwealth importation charges can add further decades."),
]

NEWS = [
 dict(slug="nitazenes-spreading-eu", title="Nitazenes now detected in 12 European monitoring systems", date="2026-09-10", tag="Trend",
  summary="EMCDDA early-warning reports show the nitazene family (etonitazene, metonitazene, isotodesnitazene) spreading from the Baltics across Western Europe, mostly hidden in counterfeit oxycodone and 'heroin'.",
  body=["Nitazenes were developed by CIBA in the 1950s and abandoned as medicines — they are 10–25x fentanyl's potency and have no approved human use.",
        "Drug-checking services in several EU cities report nitazenes in pills sold as oxycodone 80 mg. Naloxone reverses them, but multiple doses are often needed.",
        "See our full nitazene explainer and the etonitazene / isotodesnitazene profiles."],
  sources=["EMCDDA EU Early Warning System","NIDA"], drugsInvolved=["etonitazene","isotodesnitazene"]),
 dict(slug="xylazine-beyond-us", title="Xylazine ('Tranq') confirmed in drug supply outside North America", date="2026-09-02", tag="Adulterant",
  summary="First confirmed lab detections of xylazine-adulterated fentanyl in the UK and EU supply. Wound-care and naloxone-limit guidance is being updated by harm-reduction services.",
  body=["Xylazine is a veterinary tranquilizer — not an opioid — so naloxone does not reverse it, though you should still give naloxone for suspected fentanyl co-exposure.",
        "Its hallmark is necrotic skin wounds far from injection sites. Wounds need medical care even when small.",
        "Read: our Xylazine (Tranq) guide and topic page."],
  sources=["NIDA","UK Home Office ACMD"], drugsInvolved=["xylazine","fentanyl"]),
 dict(slug="high-dose-ecstasy-warning", image="https://plugreports.com/media/drugs/xtc-pills.jpeg", title="High-dose ecstasy pills (250–330 mg) circulating again this festival season", date="2026-08-25", tag="Alert",
  summary="Pill-testing services across Europe are flagging pressed pills at 2–3x a typical adult dose. PMA/PMMA copycat pills — slow to kick in, deadly — remain in circulation.",
  body=["A common adult dose is 80–120 mg. Pills above 200 mg significantly raise the risk of severe overheating and serotonin toxicity.",
        "If a pill takes 2+ hours to work, do NOT assume it's weak — it may be PMA/PMMA. Never redose on a slow pill.",
        "See: How to spot pressed pills — real vs fake."],
  sources=["PillReports","EMCDDA","The Loop UK"], drugsInvolved=["mdma"]),
 dict(slug="counterfeit-xanax-update", image="https://plugreports.com/media/drugs/counterfeit-xanax-update.jpeg", title="Counterfeit 'Xanax bars' increasingly contain flubromazolam or fentanyl", date="2026-08-18", tag="Alert",
  summary="Forensic testing in the US and UK shows counterfeit alprazolam bars frequently contain the ultra-potent RC benzo flubromazolam — active at 0.25 mg — and intermittent fentanyl.",
  body=["Flubromazolam causes multi-day blackouts and dangerous withdrawal after short exposure.",
        "If you take pressed bars: never mix with opioids or alcohol, and tell someone what you took.",
        "Profiles: alprazolam, flubromazolam, clonazolam."],
  sources=["DEA","WEDINOS UK","NIDA"], drugsInvolved=["alprazolam","flubromazolam","fentanyl"]),
]

HOTLINES = {
 "USA": [("911","Emergency — overdose, always call","Fire/EMS can carry naloxone; Good Samaritan laws protect callers in most states.", "911"),
  ("1-800-662-4357","SAMHSA National Helpline","Free, 24/7, confidential treatment referrals (English/Spanish).","18006624357"),
  ("988","Suicide & Crisis Lifeline","Call or text 988 — crisis support 24/7.","988"),
  ("1-800-222-1222","Poison Control","24/7 poison and overdose triage by toxicology nurses.","18002221222"),
  ("1-800-484-3731","Never Use Alone","Call while using — an operator stays on the line and calls help if you become unresponsive.","18004843731"),
  ("Text HOME to 741741","Crisis Text Line","Free 24/7 text crisis support.","")],
 "Canada": [("911","Emergency","Immediate danger to life — always call first.","911"),
  ("9-8-8","Suicide Crisis Helpline","Call or text 9-8-8, 24/7.","988"),
  ("1-866-531-2600","ConnexOntario","Substance use and problem-gambling helpline, 24/7, free.","18665312600"),
  ("1-800-668-6868","Kids Help Phone","Youth support, call or text 686868.","18006686868")],
 "Europe": [("112","EU Emergency Number","Works in all EU member states, free, 24/7.","112"),
  ("0300 123 6600","FRANK (UK)","Drugs information & advice, 24/7, confidential.","03001236600"),
  ("0 800 23 13 13","Drogues Info Service (France)","Free, anonymous drug information line.","0800231313"),
  ("0180 5 31 30 31","Sucht- und Drogenhotline (Germany)","Federal addiction & drug hotline.","01805313031"),
  ("088 505 1220","Jellinek Advieslijn (Netherlands)","Addiction care advice line.","0885051220")],
 "Australia": [("000","Emergency","Ambulance, police, fire.","000"),
  ("1800 250 015","National Alcohol & Other Drug Hotline","Free 24/7 counselling and referral.","1800250015"),
  ("13 11 14","Lifeline","24/7 crisis support and suicide prevention.","131114"),
  ("1800 888 236","DirectLine (Victoria)","Free 24/7 AOD counselling & referral.","1800888236")],
 "Africa": [("SADAG 0800 456 789","South African Depression & Anxiety Group","Mental health helpline with substance-use support.","0800456789"),
  ("SANCA 011 262 5986","South African National Council on Alcoholism","Treatment referral network across SA provinces.","0112625986"),
  ("1192","NACADA Helpline (Kenya)","Government drug-control helpline, toll-free.","1192"),
  ("Nearest hospital emergency","Across the continent","Where dedicated lines are unavailable, hospital casualty departments and clinics are the fastest route to help.","")],
}

PHARMACIES = [
 dict(slug="nabp-safe-pharmacy", name="NABP Safe Pharmacy (verification program)", region="USA/online",
  desc="The National Association of Boards of Pharmacy verifies legitimate online pharmacies. Check any site against their .pharmacy registry before buying medication online — most 'online pharmacies' are counterfeit pill mills.",
  phone="(847) 391-4400", website="https://safe.pharmacy", verified=True),
 dict(slug="pharmacychecker", name="PharmacyChecker Verification", region="USA/Canada/online",
  desc="Independent verification of licensed mail-order pharmacies, with price comparison limited to accredited sellers. Use it to avoid counterfeit ED pills and fake 'Canadian' pharmacies.",
  phone="", website="https://www.pharmacychecker.com", verified=True),
 dict(slug="healthwarehouse", name="HealthWarehouse.com", region="USA",
  desc="NABP-accredited US online pharmacy (VIPPS). A reference example of what a verified online pharmacy looks like: requires prescriptions, licensed pharmacists, US address.",
  phone="(513) 8DEPO-7", website="https://www.healthwarehouse.com", verified=True),
]

REHABS = [
 dict(slug="hazelden-betty-ford", name="Hazelden Betty Ford Foundation", region="USA (multi-state)",
  desc="One of the largest nonprofit addiction treatment organizations in the US: residential, outpatient, detox, and virtual care. Sliding-scale and insurance accepted.",
  phone="1-866-831-5700", website="https://www.hazeldenbettyford.org", verified=True),
 dict(slug="priory-group", name="Priory Group", region="UK & Europe",
  desc="Major UK mental-health and addiction provider: residential rehab, day programs, NHS-funded pathways.",
  phone="0800 840 3218", website="https://www.priorygroup.com", verified=True),
 dict(slug="narcotics-anonymous", name="Narcotics Anonymous", region="Worldwide (free)",
  desc="Free, peer-led 12-step fellowship with meetings in 140+ countries. No cost, no insurance, no referral needed — welcome with any drug history.",
  phone="", website="https://www.na.org", verified=True),
 dict(slug="smart-recovery", name="SMART Recovery", region="Worldwide (free)",
  desc="Evidence-based, self-empowering alternative to 12-step: CBT and motivational tools. Free meetings online and in-person across our focus regions.",
  phone="", website="https://www.smartrecovery.org", verified=True),
]

SENTENCING = [
 dict(region="United States", flag="US",
  summary="Two systems apply: federal and state. Federal simple possession (first offence) carries up to 1 year; trafficking scales to life. Most possession cases are prosecuted under state law, where penalties vary enormously.",
  table=[["Offence (federal)","Typical range"],
   ["Simple possession, 1st offence","Up to 1 year + fine"],
   ["Simple possession, 2nd+","15 days–2 years"],
   ["Trafficking (e.g., fentanyl >400g)","10 years–life (mandatory minimums)"],
   ["Good Samaritan laws","47 states protect overdose callers from possession charges"]]),
 dict(region="Canada", flag="CA",
  summary="Controlled Drugs and Substances Act. Simple possession (summary conviction): fines and diversion for first offences; indictable up to 3 years for repeat or hard drugs. Trafficking 1 year–life.",
  table=[["Offence","Typical range"],
   ["Possession (summary)","Discharge to 6 months / fines"],
   ["Possession (indictable)","Up to 3 years"],
   ["Trafficking","1 year–life"],
   ["Note","Supervised consumption sites operate legally in BC, ON, QC and AB"]]),
 dict(region="United Kingdom", flag="UK",
  summary="Misuse of Drugs Act 1971: Class A (heroin, cocaine, MDMA) possession up to 7 years; Class B (amphetamine, ketamine, cannabis) 5 years; Class C (benzos without Rx, GHB) 2 years. Supply sentences roughly triple possession.",
  table=[["Class","Possession","Supply"],
   ["A (heroin, coke, MDMA, LSD)","7 yrs","Life"],
   ["B (speed, ketamine, cannabis)","5 yrs","14 yrs"],
   ["C (benzos w/o Rx, GHB)","2 yrs","14 yrs"]]),
 dict(region="European Union", flag="EU",
  summary="No single EU drug law — each member state differs widely. Notable: Portugal decriminalized possession of small (10-day supply) amounts in 2001 (administrative offences only); most states treat supply far more harshly than possession.",
  table=[["Country","Possession (small amount)"],
   ["Portugal","Administrative fine / dissuasion panel — not criminal"],
   ["Germany (cannabis)","Legal within personal-use limits"],
   ["France","1 year + fine (use is also an offence)"],
   ["Netherlands","Cannabis tolerated in coffeeshops; hard drugs prosecuted"]]),
 dict(region="Australia", flag="AU",
  summary="State-based law. Simple possession commonly up to 2 years (varies by state and drug); several states offer diversion (caution / education) for first offences. Importation is federal and severe — up to life.",
  table=[["Offence","Typical range"],
   ["Possession (state)","Fines to 2 yrs imprisonment"],
   ["Cultivation/manufacture","2–25 yrs"],
   ["Importation (federal)","Up to life imprisonment"]]),
 dict(region="Africa (selected)", flag="AF",
  summary="Varies widely. South Africa: Drugs and Drug Trafficking Act — possession of dependence-producing drugs carries fines and/or up to 15 years for dangerous drugs; personal cannabis use was decriminalized by the Constitutional Court in 2018. Kenya and Nigeria maintain strict criminal regimes with long trafficking sentences.",
  table=[["Country","Possession"],
   ["South Africa","Fines / up to 15 yrs (dangerous drugs)"],
   ["Kenya","Fines + up to 10 yrs"],
   ["Nigeria","10 yrs+ (NDLEA Act)"]]),
]

SETTINGS = dict(site="plugreports.com", tagline="Know the drug. Know the risk. Know the way out.",
 gsc="fpjrQ73pPwkCAm_jYft5fKHfCgei5Eu3zr6KTmTmNtc", bing="", clarity="yiltr1g8h1", ga="",
 crisisNote="If you or someone nearby may be overdosing: call emergency services now, give naloxone if available, stay with the person.")

QUIT_SPECS = {
 "heroin": dict(name="Heroin", cat="Opioid", danger="Medical detox strongly advised — opioid withdrawal is rarely deadly on its own; complications (dehydration, relapse into lowered tolerance) are the killers.",
  days=[("Hour 6–12","First withdrawal","Anxiety, muscle aches, sweating, runny nose — like a severe flu starting."),
        ("Day 1–3","Peak","Nausea, vomiting, diarrhea, insomnia, cramps. Peak and highest relapse-risk window."),
        ("Day 4–7","Turning corner","Physical symptoms ease; exhaustion and low mood dominate. Sleep slowly returns."),
        ("Week 2–4","PAWS begins","Anhedonia (nothing feels good), cravings, anxiety. Most relapses happen here — support matters most now."),
        ("Month 2–6","PAWS fades","Energy and mood normalize gradually. Exercise and routine genuinely accelerate this.")],
  tips=["Naloxone on hand — relapse after detox is the #1 overdose killer because tolerance drops",
        "Buprenorphine/methadone and meds like clonidine make detox far safer — see a clinic",
        "Never Use Alone line if you do use: 1-800-484-3731"]),
 "fentanyl": dict(name="Fentanyl", cat="Opioid", danger="Same opioid withdrawal profile as heroin, often starting sooner and dragging longer due to fentanyl's fat storage. Buprenorphine induction needs special timing — see a clinician.",
  days=[("Hour 4–8","Early withdrawal","Fentanyl stores in body fat — symptoms can start fast and drag out."),
        ("Day 1–4","Brutal peak","Longer peak than heroin — days 2 and 3 are typically the worst."),
        ("Day 5–10","Slow ease","Symptoms fade slowly; insomnia and restless legs linger."),
        ("Weeks 2–8","Extended PAWS","Stored metabolites make post-acute symptoms longer than heroin for many people."),
        ("Month 3+","Recovery","Most report feeling substantially normal by month 3–6 with support.")],
  tips=["Do not attempt fentanyl detox alone — the relapse-overdose window is deadly",
        "Methadone/buprenorphine maintenance is medicine, not failure",
        "Keep naloxone everywhere you might be"]),
 "cocaine": dict(name="Cocaine", cat="Stimulant", danger="Withdrawal is psychological more than physical — the crash is depression and craving, and suicide risk is real. Support matters.",
  days=[("Hour 1–72","The crash","Exhaustion, depression, increased appetite, intense craving. Sleep a lot — your brain is repairing."),
        ("Week 1","Anhedonia","Nothing feels rewarding. This is dopamine depletion, not a permanent state."),
        ("Weeks 2–4","Craving waves","Cravings come in waves, usually triggered by people, places, paraphernalia. Each wave passes in ~15 minutes."),
        ("Month 1–3","Steady recovery","Sleep, mood and motivation normalize. Vivid drug dreams are common and normal."),
        ("Month 3+","New baseline","Most cognitive and mood effects resolve. Cardiovascular risk starts dropping immediately after quitting.")],
  tips=["The crash is temporary — week 1 is not how you'll feel forever",
        "Delete numbers, change routes, avoid using friends for the first 90 days",
        "If depression feels dangerous, call/text 988 (US)"]),
 "meth": dict(name="Methamphetamine", cat="Stimulant", danger="Longest and deepest crash of the stimulants — expect 1–3 weeks of heavy sleep and low mood, then months of gradual dopamine recovery.",
  days=[("Days 1–3","The wall","12–20 hour sleeps, ravenous hunger, flat mood. Normal repair, not failure."),
        ("Week 1–2","Low mood","Anhedonia, irritability, intense craving. Suicide risk peaks here — don't isolate."),
        ("Weeks 3–6","Fog lifting","Thinking clears; 'meth dreams' and sudden cravings are common and pass."),
        ("Months 2–6","Dopamine rebuild","Motivation and pleasure return slowly. Exercise is one of the few proven accelerants."),
        ("Month 6+","Largely recovered","Most cognitive testing returns to normal ranges within 6–12 months.")],
  tips=["Eat and sleep on schedule — the brain needs raw materials to rebuild",
        "Cravings pass in waves; have a 15-minute plan (shower, walk, call someone)",
        "NA/MA meetings and contingency-management programs have the best evidence"]),
 "mdma": dict(name="MDMA", cat="Empathogen", danger="No dangerous physical withdrawal — but expect a real serotonin comedown. The main risks are depression in week 1 and the temptation to redose to escape it.",
  days=[("Day 1–3","Comedown","Low mood, fatigue, appetite loss. Serotonin stores are depleted; they rebuild."),
        ("Week 1","Emotional flatness","Some feel tearful or anxious. Sleep, sunlight and exercise help more than anything."),
        ("Week 2–4","Back to baseline","Mood normalizes. If it doesn't — or low mood predates use — talk to a professional."),
        ("Ongoing","Frequency rule","The brain needs roughly 1–3 months between rolls to recover serotonin function — more frequent use is where real damage happens.")],
  tips=["Never use MDMA to escape the MDMA comedown — that's the spiral",
        "Persistent low mood after use is a sign to stop and get support",
        "Test pills — PMA/PMMA masquerading as MDMA kills"]),
 "alprazolam": dict(name="Alprazolam (Xanax)", cat="Benzodiazepine", danger="NEVER quit cold turkey after regular use — benzodiazepine withdrawal can cause fatal seizures. Taper under medical supervision (diazepam-switch / Ashton-style).",
  days=[("During taper","Slow reduction","A proper taper reduces dose ~5–10% every 1–2 weeks so symptoms stay manageable."),
        ("Post-taper wk 1","Rebound","Anxiety and insomnia return hard — the brain recalibrating, not a need for the drug."),
        ("Weeks 2–6","Acute withdrawal","Sensory hypersensitivity, muscle pain, waves of panic. Peaks around week 2–3."),
        ("Months 2–12","Protracted (some)","A minority get months of windows-and-waves. It resolves — peer support groups help enormously.")],
  tips=["Seizure risk is exactly why you taper — never stop abruptly",
        "Tell a prescriber honestly; they help with this every day",
        "Avoid alcohol completely during withdrawal"]),
 "ketamine": dict(name="Ketamine", cat="Dissociative", danger="Physical withdrawal is mild; the real recovery targets are the bladder and the mind. Heavy users often need months for bladder symptoms to improve.",
  days=[("Day 1–7","Cravings + low mood","Irritability, restlessness, low mood. Urinary frequency may temporarily worsen before improving."),
        ("Weeks 2–4","Bladder recovery","Pelvic pain and frequency ease when use stops. Hydrate; see a urologist if blood appears."),
        ("Months 1–3","Mood rebuild","Motivation returns. K-cravings are strongly situational — change routines."),
        ("Month 3+","Mostly recovered","Bladder symptoms largely resolve in most former heavy users who stay stopped.")],
  tips=["K cramps and blood in urine = stop now and see a doctor",
        "Improving urinary symptoms are your proof the body repairs",
        "Ketamine is used clinically for depression — self-medicating is not the same thing"]),
 "ghb": dict(name="GHB/GBL", cat="Depressant", danger="Daily GHB/GBL use creates the most dangerous withdrawal of any recreational drug — abrupt cessation can be fatal (seizures, delirium, rhabdomyolysis). Medical detox is NOT optional for daily users.",
  days=[("Hour 4–8","First signs","Tremor, anxiety, insomnia — GHB clears fast, so daily users dose around the clock."),
        ("Day 1–3","Acute withdrawal","Severe anxiety, hallucinations, fast heart rate. A MEDICAL EMERGENCY — hospital detox with benzodiazepines is standard."),
        ("Weeks 2–4","Rebound","Insomnia, low mood, persistent tremor slowly fade."),
        ("Month 1–3","Stabilize","Sleep architecture and mood normalize.")],
  tips=["Daily user? Do not attempt sudden withdrawal outside hospital",
        "GHB withdrawal kills — treat it like alcohol withdrawal (mechanistically it is)",
        "Every hour of recovered sleep is measurable progress"]),
}

# Block types: p, h2, h3, ul, ol, quote, callout(color,title,text), stats[(n,label)],
# table(headers+rows), figure(html, caption), timeline, checklist, related[slugs], links[urls]
TOPICS = [
 dict(slug="what-is-xylazine", title="What is Xylazine (Tranq) and why it's terrifying first responders", date="2026-09-11", read="6 min",
  desc="The veterinary sedative being cut into fentanyl — the wounds, the blackouts, and why naloxone doesn't fix it.",
  blocks=[
   ("p","Xylazine is a veterinary anesthetic approved for horses and cattle. It is <b>not an opioid, not a human medicine, and has no approved antidote</b> for human overdose. Since roughly 2020 it has spread through the US fentanyl supply; by 2023 the DEA found it in about a quarter of tested fentanyl powder, and detections have since been confirmed in Canada, the UK and continental Europe."),
   ("h2","Why it's different from every other adulterant"),
   ("ul",["It <b>slows breathing like an opioid but isn't one</b> — naloxone will NOT reverse it (give naloxone anyway if fentanyl is possible; xylazine is almost always mixed with it).",
          "It causes <b>necrotic skin wounds</b> — 'tranq lesions' — black scabs that can appear anywhere on the body, not just injection sites, and can lead to amputation.",
          "It causes <b>hours-long blackouts</b> during which people are robbed, assaulted, or stop breathing."]),
   ("callout",("red","If someone is unresponsive","Call emergency services immediately. Give naloxone if you have it (for the fentanyl). Xylazine has no field antidote — hospital supportive care (airway, breathing support) is the only treatment.")),
   ("h2","Why first responders are alarmed"),
   ("p","Overdoses involving xylazine respond slower and less predictably. Blood pressure drops hard. Wounds need wound-care teams most paramedics don't carry. And users in withdrawal face <b>both</b> opioid withdrawal and xylazine withdrawal at once — a combination clinics are still learning to treat."),
   ("stats",[("~25%","of US fentanyl powder contained xylazine (DEA, 2023)"),("0","approved human antidotes"),("hrs","typical blackout length after a tranq-heavy dose")]),
   ("h2","If you or someone you know is using tranq-dope"),
   ("checklist",["Never use alone — call Never Use Alone (US): 1-800-484-3731","Carry naloxone — it reverses the fentanyl half of the mix","Treat every small wound seriously: clean, cover, and get medical care early — tranq wounds do not heal on their own","Tell wound-care and outreach workers you use tranq — they now specialize in this"]),
   ("related",["xylazine","fentanyl","nitazenes-new-opioids"])]),

 dict(slug="cocaine-purity-and-cuts", image="https://plugreports.com/media/drugs/cocaine-purity-and-cuts.jpeg", title="What is cocaine actually cut with? Purity explained", date="2026-09-09", read="7 min",
  desc="From levamisole to phenacetin to fentanyl: what drug-checking shows is really in cocaine, and why 'pure' can be more dangerous, not less. External deep-dive: 247avlplug.com/understanding-cocaine-purity/.",
  blocks=[
   ("p","Retail cocaine purity has climbed in Europe (EMCDDA reports averages near 60–70% in several countries) while US seizures vary widely. But purity is not safety — the most dangerous things in cocaine are often the <b>cuts and adulterants</b>, and occasionally fentanyl itself."),
   ("h2","The usual suspects found by drug checking"),
   ("table",[["Adulterant","Why it's there","The risk"],
     ["Levamisole (vet wormer)","Bulks powder, mimics stimulant feel","Immune suppression; severe skin necrosis"],
     ["Phenacetin / paracetamol / caffeine","Cheap bulk, numbing effect","Kidney damage (phenacetin); liver stress"],
     ["Boric acid / benzocaine","Mimics shine & numbing","Seizures at high dose; methemoglobinemia"],
     ["Mannitol, lactose, glucose","Inert bulk","Low risk by themselves"],
     ["Fentanyl (rare, deadly)","Cross-contamination at packaging","Opioid overdose in a non-tolerant user"]]),
   ("h2","Why 'stronger' cocaine sends more people to hospital"),
   ("p","When purity jumps from 30% to 70% without the user knowing, the same 'two lines' is more than double the dose. Drug-checking services report that <b>most cocaine hospitalizations track unexpected potency, not new drugs</b>."),
   ("callout",("amber","Harm reduction if you use","Start with a quarter of your usual amount when the source changes. Never mix with alcohol (forms cocaethylene — extra cardiotoxic) or opioids. If someone collapses with slow breathing after cocaine: give naloxone — it may be fentanyl contamination.")),
   ("quote","Cocaine-related deaths in England & Wales hit record levels in recent ONS releases — most involve cocaine plus opioids or alcohol together, not cocaine alone.","ONS / EMCDDA trend reporting"),
   ("related",["cocaine","4-fluorococaine","fentanyl"])]),

 dict(slug="fentanyl-numbers", image="https://plugreports.com/media/drugs/fentanyl.webp", title="Fentanyl: the numbers nobody tells you", date="2026-09-07", read="6 min",
  desc="2 milligrams. 5 minutes. One naloxone spray may not be enough. The arithmetic of the deadliest drug supply in history.",
  blocks=[
   ("stats",[("2 mg","potentially fatal dose — a few grains of salt"),("~75,000","US overdose deaths involving fentanyl per year (CDC)"),("10–25x","nitazene potency vs fentanyl — the next wave"),("3–5 min","for fentanyl to reach the brain when smoked")]),
   ("p","Fentanyl is a legitimate medicine — 50–100x morphine's potency, used for surgical pain and end-of-life care. Illegally manufactured fentanyl is the same molecule made in clandestine labs, pressed into fake pills that mimic oxycodone, Xanax, Adderall — even candy-colored tablets."),
   ("h2","The arithmetic that kills"),
   ("ul",["A lethal dose is <b>2 mg</b>; a $20 bag can hold hundreds of lethal doses — street mixes are eyeballed, not scaled.",
          "Pills are pressed, not dosed: <b>one pill in a batch can be 10x another</b>.",
          "Fentanyl builds dependence fast: <b>3–5 days of daily use creates physical dependence</b>."]),
   ("h2","The reversal arithmetic that saves"),
   ("p","Naloxone displaces fentanyl from opioid receptors. Because fentanyl binds hard, <b>one spray may reverse for only 30–90 minutes while fentanyl outlasts it</b> — the person can re-overdose. Protocol: give naloxone, call 911, and STAY — even after they wake up."),
   ("table",[["Sign","What to do"],
     ["Unresponsive, pinpoint pupils, slow/gurgling breathing","Call 911 (Good Samaritan laws protect you in most places)"],
     ["Naloxone given, person wakes","STAY. Second overdose possible as naloxone wears off"],
     ["No naloxone available","Rescue breathing / chest compressions until help arrives"]]),
   ("callout",("red","Free naloxone","US: naloxone is over-the-counter nationwide (Narcan, ~$45; many states and syringe programs give it free). Nextdistro.org and harm-reduction programs mail it free. Canada: pharmacies. UK: via drug services.")),
   ("related",["fentanyl","nitazenes-new-opioids","what-actually-happens-when-you-quit"])]),

 dict(slug="spot-pressed-pills", title="How to spot pressed pills: real vs fake", date="2026-09-04", read="8 min",
  desc="Counterfeit oxycodone, Xanax and Adderall kill thousands. The tells, the tests, and why appearance alone can never guarantee safety.",
  blocks=[
   ("p","Pill presses are cheap and imprints are copyable — <b>the DEA states most counterfeit pills tested contain fentanyl or meth</b>. You cannot identify a fake reliably by eye. What you CAN do is stack the odds: know the tells, use test strips, and never use alone."),
   ("h2","Visual tells (weak, but worth knowing)"),
   ("checklist",["Imprint uneven, smudged or off-center — pharma imprints are laser-crisp","Color 'too' uniform or slightly off-shade; coating looks painted on","Pill crumbles or chips easily; real tablets are dense","Source: social-media DM, 'a friend of a friend', or '$5 blues' — classic counterfeit channels","Price too good: real 30 mg oxycodone diverts at $15–40"]),
   ("h2","What lab testing actually finds"),
   ("table",[["Pill sold as","Typical lab finding"],
     ["'Oxycodone 30' (blue, M30)","Fentanyl + filler — sometimes ONLY fentanyl"],
     ["'Xanax bar'","Alprazolam — or etizolam, flubromazolam, sometimes fentanyl"],
     ["'Adderall 30' (orange)","Methamphetamine or caffeine/dextro blends"],
     ["'Percocet'","Fentanyl; rarely any oxycodone"]]),
   ("h2","The real safety layers"),
   ("ul",["<b>Fentanyl test strips</b> (~$1): dissolve a tiny sample — two lines = fentanyl absent, one line = present.",
          "<b>Reagent kits</b> (Marquis/Mecke): distinguish MDMA from PMA, opiates, etc.",
          "<b>Never use alone</b> + naloxone within reach — the last line, and the one that has saved hundreds of thousands of lives.",
          "<b>Drug checking</b> where legal: The Loop (UK), DIMS (NL), Energy Control (ES), CheckIt! (AT)."]),
   ("callout",("red","If someone took a pill and is now unresponsive","Naloxone NOW (repeat doses if needed), 911, rescue breathing. Tell responders exactly what was taken — they treat, not arrest.")),
   ("related",["fentanyl","alprazolam","counterfeit-xanax-update"])]),

 dict(slug="drug-busts-this-week", title="Drug busts this week: how to read enforcement news", date="2026-09-01", read="5 min",
  desc="Seizures are data about the supply, not just police wins. What a bust headline actually tells you — and what it doesn't.",
  blocks=[
   ("p","Every week agencies publish seizure figures: pills, kilograms, precursor chemicals. Read them like a supply-chain analyst — they tell you <b>what's flowing, where, and in what form</b>."),
   ("h2","How to read a bust headline"),
   ("ul",["<b>Pill counts (e.g. '500,000 pills')</b> → industrial pill-press networks; that volume means a regional hub, not a street dealer.",
          "<b>Kilograms at ports</b> → the wholesale tier; price ripples reach streets months later.",
          "<b>Precursor seizures (NPP, ANPP, 4-AP)</b> → a fentanyl lab is being starved; expect temporary local potency spikes.",
          "<b>One region repeatedly</b> → an active trafficking corridor; local harm-reduction services usually post alerts."]),
   ("h2","Why this matters for safety"),
   ("p","After major seizures, markets destabilize: <b>strength varies batch to batch for weeks</b>. The period after a big bust is consistently a high-risk window for unexpected potency."),
   ("callout",("amber","Practical takeaway","When big seizures make local news: treat your usual dose as unknown, test if you can, never use alone, keep naloxone close.")),
   ("p","We track notable seizures in our Busts section — each entry lists agency, location, substances and the applicable sentencing exposure."),
   ("related",["busts","fentanyl-numbers"])]),
]

TOPICS += [
 dict(slug="krokodil-fact-vs-myth", title="Krokodil: the drug that rots flesh — fact vs myth", date="2026-08-29", read="6 min",
  desc="Desomorphine is real. The zombie-apocalypse version mostly wasn't. What krokodil actually is, and where the flesh-rotting really comes from.",
  blocks=[
   ("p","Krokodil is desomorphine — a semi-synthetic opioid 8–10x morphine's potency, used medically in Soviet-era Russia. The 'flesh-rotting zombie drug' of 2010s headlines was <b>not the molecule</b> — it was the chemistry: users synthesize it from codeine tablets using gasoline, hydrochloric acid and red phosphorus, then <b>inject without purification</b>."),
   ("h2","The facts"),
   ("ul",["Desomorphine itself is a short-acting opioid — the damage attributed to 'krokodil' comes from <b>residual acids and solvents burning skin and veins</b>.",
          "Confirmed cases cluster where codeine is OTC and heroin is scarce — Russia, Ukraine, Kazakhstan. Isolated cases elsewhere were often misattributed.",
          "Repeated 'spreading to the US/EU' panics were debunked — codeine is prescription-controlled in the West, removing the raw material.",
          "Yes, real users lost limbs — from gangrene and infections of the injection site, worsened by immune collapse."]),
   ("h2","Why the myth matters"),
   ("p","Panic coverage did real harm: it made users hide wounds until amputation was the only option, and it taught the public that drug injury is punishment rather than a medical emergency. The correct response to any injection wound — any drug, any country — is <b>early wound care</b>. Tranq (xylazine) wounds today are a real, spreading phenomenon; krokodil mostly wasn't."),
   ("callout",("green","If you have a wound from injecting","Clean with soap and water, cover with a clean dressing, seek a clinic EARLY. No clinic will report you to police for a wound. Hidden wounds become amputations.")),
   ("related",["xylazine","heroin"])]),

 dict(slug="nitazenes-new-opioids", title="Nitazenes: the new opioids stronger than fentanyl", date="2026-08-26", read="6 min",
  desc="Abandoned 1950s medicines, resurrected by the drug trade. Etonitazene, isotodesnitazene and what their spread changes about overdose response.",
  blocks=[
   ("p","The nitazenes are a family of benzimidazole opioids synthesized at CIBA in the 1950s and <b>never approved for human use</b> — animal studies showed them too dangerous for medicine. The drug trade disagreed: they are cheap to synthesize, easy to ship, and 10–25x fentanyl's potency."),
   ("h2","Which ones are showing up"),
   ("table",[["Compound","Relative potency","Where it's appearing"],
     ["Etonitazene","10–25x fentanyl","Counterfeit pills; US Schedule I (2023); EU alerts"],
     ["Isotodesnitazene ('ISO')","≈ fentanyl","Heroin/fentanyl adulterant; US midwest + Baltic→EU spread"],
     ["Metonitazene","≈ fentanyl","US east coast; injected 'dope' supplies"],
     ["Protonitazene","≈ 3x fentanyl","Increasing US forensic identifications"]]),
   ("h2","What changes for overdose response"),
   ("ul",["<b>Naloxone still works</b> — nitazenes are opioids — but <b>higher or repeated doses are often required</b>.",
          "They last long: re-sedation after naloxone wears off is common. <b>Stay; repeat doses every 2–3 min if they re-sedate.</b>",
          "Standard urine screens often MISS nitazenes — hospitals may not detect them. Tell responders what the local supply rumor mill says."]),
   ("callout",("red","If you use any opioid in 2026","Assume fentanyl, assume nitazenes, assume tranq. Carry 2+ naloxone doses, never use alone, and treat 'they woke up' as the START of the emergency, not the end.")),
   ("related",["etonitazene","isotodesnitazene","fentanyl-numbers","xylazine"])]),

 dict(slug="sentencing-explained", title="Drug sentencing explained: what possession actually costs you", date="2026-08-22", read="9 min",
  desc="Schedule classes, mandatory minimums, Good Samaritan laws and the one phone call that changes everything. Region-by-region tables.",
  blocks=[
   ("p","Nothing on this page is legal advice — penalties change constantly and facts matter enormously. What follows is the map of how sentencing <b>systems</b> work in our five focus regions, so the stakes are understood before anyone stands in front of a judge."),
   ("h2","How the US system works (short version)"),
   ("ul",["<b>Federal vs state</b>: most possession cases are state; trafficking can be either. Federal simple possession (1st offence): up to 1 year. Trafficking fentanyl >400 g: <b>10 years to life, mandatory minimum</b>.",
          "<b>Drug weight drives everything</b>: a baggie + a scale can convert possession into 'possession with intent'.",
          "<b>Good Samaritan laws</b>: 47 US states + DC protect overdose-callers from possession charges. <b>They only work if someone calls.</b>",
          "<b>Drug courts & diversion</b>: many jurisdictions route first offences to treatment instead of jail — a fast lawyer request changes outcomes."]),
   ("h2","The five regions at a glance"),
   ("p","Full tables live on our Sentencing page — summary: UK Class A possession (heroin/coke/MDMA) up to <b>7 years</b>; Canada up to <b>3 years</b> indictable; the EU varies wildly (Portugal: no prison for personal amounts); Australia state-based, typically <b>up to 2 years</b>; Africa ranges from reform-minded (South Africa decriminalized personal cannabis) to severe."),
   ("h2","What to actually do if arrested"),
   ("checklist",["Say only: 'I want a lawyer and I'm exercising my right to remain silent.'","Do not consent to searches verbally — say 'I do not consent' calmly","Never discuss where anything came from — that sentence converts charges","Ask about diversion/drug court — they exist precisely for this"]),
   ("callout",("amber","The one thing that outweighs all of it","A living person beats a clean record. If someone is overdosing: CALL. Good Samaritan laws exist so fear of jail never wins over a life.")),
   ("related",["sentencing","hotlines"])]),

 dict(slug="talk-to-your-kid", title="How to talk to your kid about drugs without losing them", date="2026-08-19", read="7 min",
  desc="The evidence is clear: fear lectures fail, honest conversations work. A practical script for every age.",
  blocks=[
   ("p","Decades of prevention research converge on one finding: <b>'just say no' programs don't work; connected, honest conversations do.</b> Kids who can talk to their parents about drugs use less, and use more safely when they do experiment. The goal isn't a promise — it's a channel."),
   ("h2","The core rules"),
   ("ul",["<b>Ask before you tell.</b> 'What have you heard about vapes/pills at school?' turns a lecture into a conversation.",
          "<b>Trade honesty for honesty.</b> You don't have to confess details — but don't lie. 'I tried things; here's what I wish I'd known' lands harder than any threat.",
          "<b>Teach the fentanyl reality, not the 1980s version.</b> The conversation that matters most now: <b>never take a pill that wasn't prescribed to them</b> — counterfeit Adderall/Xanax/oxycodone is where kids die.",
          "<b>Separate the person from the drug.</b> 'I'm not mad at you — I'm worried about the pill' keeps the channel open after a confession."]),
   ("h2","Age-by-age script"),
   ("table",[["Age","What to say"],
     ["8–12","Medicine rules: only from parents/doctor, never a friend's pill; some people sell pills that look real but aren't"],
     ["13–15","Vapes, edibles and the counterfeit-pill warning; extract the 3 AM promise"],
     ["16–18","Fentanyl specifics, naloxone at school, Good Samaritan laws, and the standing deal: 'call me at 3 AM and I'll come — no punishment that night, ever'"],
     ["18+","Treat as adults: harm reduction, testing, what an overdose looks like"]]),
   ("callout",("green","The 3 AM rule","One promise unlocks everything: 'If you or a friend is in trouble, call me first. No punishment that night — we talk tomorrow.' Fear of punishment is exactly why kids die in parking lots instead of calling.")),
   ("related",["hotlines","fentanyl-numbers"])]),

 dict(slug="hotline-directory", title="Hotline directory: help anywhere", date="2026-08-15", read="4 min",
  desc="Every verified helpline across the USA, Canada, Europe, Australia and Africa — overdose, crisis, treatment referral, in one place.",
  blocks=[
   ("p","These are the numbers that answer at 3 AM. Save this page. Full cards with tap-to-call buttons are on our Hotlines page — this is the quick-reference directory."),
   ("h2","USA"),
   ("ul",["<b>911</b> — emergency (say 'unresponsive, not breathing'; naloxone given if available)",
          "<b>SAMHSA 1-800-662-4357</b> — treatment referral, 24/7, free",
          "<b>988</b> — suicide & crisis (call/text/chat)",
          "<b>Poison Control 1-800-222-1222</b>",
          "<b>Never Use Alone 1-800-484-3731</b>",
          "<b>Crisis Text Line: text HOME to 741741</b>"]),
   ("h2","Canada"),
   ("ul",["<b>911</b> · <b>9-8-8</b> crisis (call/text) · <b>ConnexOntario 1-866-531-2600</b> · <b>Kids Help Phone 1-800-668-6868</b>"]),
   ("h2","Europe"),
   ("ul",["<b>112</b> EU emergency · <b>UK FRANK 0300 123 6600</b> · <b>FR 0 800 23 13 13</b> · <b>DE 0180 5 31 30 31</b> · <b>NL Jellinek 088 505 1220</b>"]),
   ("h2","Australia"),
   ("ul",["<b>000</b> emergency · <b>National AOD Hotline 1800 250 015</b> · <b>Lifeline 13 11 14</b> · <b>DirectLine 1800 888 236</b>"]),
   ("h2","Africa"),
   ("ul",["<b>South Africa: SADAG 0800 456 789</b> · <b>SANCA 011 262 5986</b> · <b>Kenya NACADA 1192</b> · elsewhere: nearest hospital emergency department"]),
   ("callout",("red","Overdose right now?","Call your local emergency number FIRST. Then naloxone if you have it. Then rescue breathing. Order matters.")),
   ("related",["hotlines","talk-to-your-kid"])]),

 dict(slug="what-actually-happens-when-you-quit", title="What actually happens to your body when you quit — day by day", date="2026-08-12", read="5 min",
  desc="Every substance has its own withdrawal clock. The honest, day-by-day timelines — what hurts, what's normal, and when it ends.",
  blocks=[
   ("p","Fear of withdrawal keeps people using more than almost anything else. The antidote is <b>a concrete timeline</b>: knowing that day 3 is the peak, or that the crash ends, is itself harm reduction. We publish full day-by-day pages per substance — this is the hub."),
   ("h2","The pattern across all substances"),
   ("ul",["<b>Hour 0–72</b>: acute phase. Opioids peak at 48–72 h; stimulants 'crash' at 24–72 h; alcohol and benzos are the dangerous ones (seizures) — both need medical detox.",
          "<b>Weeks 2–4</b>: most physical symptoms resolve. Mood is the battleground now.",
          "<b>Months 2–6</b>: PAWS (post-acute withdrawal) — waves of low mood, craving, poor sleep. They pass. Nearly everyone who stays stopped feels substantially normal by month 3–6.",
          "<b>The exception rule</b>: benzo and GHB/GBL withdrawal can kill — never cold-turkey daily use."]),
   ("h2","Pick your substance"),
   ("table",[["Substance","Peak misery","Feel-better point"],
     ["Heroin/fentanyl","Day 2–4","~1 week physical; months of PAWS"],
     ["Cocaine","Day 1–3 (crash)","Weeks for mood"],
     ["Meth","Week 1–2","1–3 months"],
     ["MDMA","Day 1–3 (comedown)","1–2 weeks"],
     ["Xanax/benzos","Week 2–3 of a taper","Months; must be tapered"],
     ["GHB/GBL (daily)","Day 1–3 — MEDICAL EMERGENCY","Weeks, hospital-supervised"],
     ["Ketamine","Days 1–7 mild","Weeks; bladder heals for months"]]),
   ("callout",("amber","The relapse rule that saves lives","Tolerance drops fast. After even a week clean, your old dose can kill you. If you slip, treat it like your first time — and never use alone.")),
  ],
  links=["quit/heroin","quit/fentanyl","quit/cocaine","quit/meth","quit/mdma","quit/alprazolam","quit/ketamine","quit/ghb"]),
]
