# Category metadata — accent gradients per category hub
CATEGORIES = {
 "opioids": dict(name="Opioids", color="#dc2626", grad="linear-gradient(135deg,#b91c1c,#ea580c)",
  tagline="Heroin, fentanyl, painkillers and the nitazenes — the deadliest category in the drug supply.",
  blurb="Opioids suppress breathing. Most overdose deaths in the US, Canada and Europe now involve fentanyl or its analogues — often mixed into drugs the buyer never asked for.",
  stat=("~80%","of US overdose deaths involve an opioid (CDC)")),
 "stimulants": dict(name="Stimulants", color="#d97706", grad="linear-gradient(135deg,#b45309,#f59e0b)",
  tagline="Cocaine, meth, speed and the cathinone family — energy at a cardiovascular price.",
  blurb="Stimulants drive heart rate, blood pressure and body temperature up. Overdose looks like a heart event: chest pain, racing pulse, overheating.",
  stat=("2x","stimulant-involved deaths roughly doubled in 5 yrs (US CDC)")),
 "benzodiazepines": dict(name="Benzodiazepines", color="#7c3aed", grad="linear-gradient(135deg,#6d28d9,#a855f7)",
  tagline="Xanax, Valium and the research-chemical benzos — calm that quietly becomes dependence.",
  blurb="Benzodiazepine withdrawal can kill (seizures). Never stop abruptly after regular use — medical tapering is essential.",
  stat=("~30%","of opioid overdoses also involve benzos (NIDA)")),
 "sedatives": dict(name="Sedatives & Hypnotics", color="#0f766e", grad="linear-gradient(135deg,#0f766e,#14b8a6)",
  tagline="Sleeping pills, barbiturates and muscle relaxants — depressants with razor-thin margins.",
  blurb="From Ambien to Seconal: these slow the brain and breathing. Mixing with opioids or alcohol multiplies the danger.",
  stat=("3-5x","overdose risk when depressants are mixed (studies)")),
 "depressants": dict(name="GHB / GBL", color="#1d4ed8", grad="linear-gradient(135deg,#1e40af,#3b82f6)",
  tagline="Liquid euphoria with a dosing curve measured in milliliters.",
  blurb="GHB and GBL are among the most dose-sensitive recreational drugs. One extra milliliter can be the difference between euphoria and a coma.",
  stat=("1 mL","can separate a social dose from unconsciousness")),
 "dissociatives": dict(name="Dissociatives", color="#0891b2", grad="linear-gradient(135deg,#0e7490,#06b6d4)",
  tagline="Ketamine, 2F-DCK and the out-of-body class.",
  blurb="Dissociatives detach mind from body. The main long-term risk with ketamine-class drugs is bladder damage.",
  stat=("~20%","of heavy ketamine users develop bladder symptoms (studies)")),
 "empathogens": dict(name="Empathogens", color="#be185d", grad="linear-gradient(135deg,#9d174d,#ec4899)",
  tagline="MDMA, Molly and the 'love drug' family.",
  blurb="Empathogens release serotonin in a flood. The risks: overheating, water imbalance, and pills that contain something else entirely.",
  stat=("~50%","of seized 'ecstasy' contains adulterants (EMCDDA averages)")),
 "psychedelics": dict(name="Psychedelics", color="#4d7c0f", grad="linear-gradient(135deg,#3f6212,#84cc16)",
  tagline="DMT, mescaline and the 2C family — mind-altering, not life-threatening at pure doses.",
  blurb="Classic psychedelics have no known lethal overdose range — the real risks are psychological and behavioral: panic, bad judgment, accidents.",
  stat=("0","confirmed lethal overdoses of pure classic psychedelics (published literature)")),
 "cannabinoids": dict(name="Cannabinoids", color="#57534e", grad="linear-gradient(135deg,#44403c,#a8a29e)",
  tagline="Natural cannabis and synthetic 'Spice' — same receptors, wildly different dangers.",
  blurb="Natural cannabis is one of the most-used drugs on earth — low acute toxicity but real risks with potency, dependence and contaminants. Synthetic cannabinoids ('Spice', K2) bind far harder than THC: seizures, catatonia, kidney failure, deaths.",
  stat=("100x+","potency of some synthetics vs natural THC")),
 "performance": dict(name="Performance & Grey-Market Pharma", color="#b45309", grad="linear-gradient(135deg,#92400e,#fbbf24)",
  tagline="Grey-market bodybuilding and 'research' compounds with zero quality control.",
  blurb="Clenbuterol, AICAR, grey-market ED pills — sold as research chemicals or 'not for human use', with no dosing safety data.",
  stat=("0","human safety trials for most grey-market compounds")),
 "hazardous": dict(name="Hazardous Substances", color="#111827", grad="linear-gradient(135deg,#111827,#4b5563)",
  tagline="Things sold alongside drugs that are not drugs at all.",
  blurb="Potassium cyanide and similar substances appear in listings and scams. There is no safe use — this section exists to warn.",
  stat=("mg","doses that kill are measured in milligrams")),
}

CATEGORIES.update({
 "steroids": dict(name="Steroids & Anabolics", color="#4338ca", grad="linear-gradient(135deg,#3730a3,#6366f1)",
  tagline="Testosterone, trenbolone, Dianabol and the gym-pharma grey market — what the labels actually contain.",
  blurb="Anabolic steroids are the most counterfeited drug class on earth. Underdosed vials, mislabeled esters and contaminated injectables are the norm in grey-market supply — every profile covers the real compound, the risks, and how the brands map.",
  stat=("~50%","of grey-market steroids tested are underdosed or fake (independent lab analyses)")),
 "peptides": dict(name="Peptides & Research Chemicals", color="#0d9488", grad="linear-gradient(135deg,#0f766e,#14b8a6)",
  tagline="BPC-157, TB-500, Melanotan and the 'research use only' pipeline.",
  blurb="Peptides are sold online as 'research chemicals — not for human use', which means zero quality control, no dosing safety data, and no recourse when a vial is contaminated or mislabeled. Most have never passed a human safety trial.",
  stat=("0","human safety trials for most grey-market peptides")),
 "sexual-health": dict(name="Sexual Health & ED Meds", color="#c026d3", grad="linear-gradient(135deg,#a21caf,#d946ef)",
  tagline="Viagra, Cialis and 40+ generic brands — same molecules, wildly different supply chains.",
  blurb="Sildenafil, tadalafil and vardenafil are among the most counterfeited medicines in the world. The brand table on each compound page maps the grey-market names (Cenforce, Vidalista, Kamagra) to what's actually inside.",
  stat=("$ billions","lost yearly to fake ED pills — Interpol's most-faked drug class")),
 "weight-loss": dict(name="Weight Loss & Metabolic Meds", color="#65a30d", grad="linear-gradient(135deg,#4d7c0f,#84cc16)",
  tagline="GLP-1 pens, thyroid hormones, clenbuterol and the 'cutting' grey market.",
  blurb="From counterfeit Ozempic-style pens to clenbuterol and T3 bought as 'research chemicals' — the weight-loss grey market sells powerful metabolic drugs with no medical oversight. Heart rhythm, thyroid collapse and refilled-pen scams are the signature harms.",
  stat=("100%","of pre-launch grey-market GLP-1 sales are likely counterfeit")),
 "hair-hormones": dict(name="Hair Loss & Hormone Meds", color="#a16207", grad="linear-gradient(135deg,#854d0e,#eab308)",
  tagline="Finasteride, dutasteride, HGH and the post-cycle-therapy pharmacy.",
  blurb="Hair-loss drugs with sexual side effects most sellers won't mention, growth hormone with counterfeit rates near total, and the SERM/AI pharmacy that steroid users depend on — profiles for the compounds behind the brand soup.",
  stat=("~90%","of online 'HGH' tested in studies was fake or underdosed")),
})

CATEGORIES.update({
 "beauty": dict(name="Beauty Industry & Med Spa", color="#db2777", grad="linear-gradient(135deg,#9d174d,#ec4899)",
  tagline="Botox parties, black-market filler, and the unregulated cosmetic procedures targeting under-25s.",
  blurb="The beauty industry has a drug problem: unlicensed injectors, counterfeit Botox, illegal filler sold online, and teenagers getting lip filler at kitchen-table parties. These substances and procedures carry real risk — vascular occlusion, blindness, sepsis, and worse.",
  stat=("73%","of FDA adverse-event reports for dermal fillers come from unlicensed/non-medical settings")),
})

CATEGORIES.update({
 "tobacco": dict(name="Tobacco & Nicotine", color="#7c2d12", grad="linear-gradient(135deg,#7c2d12,#b45309)",
  tagline="Cigarettes, vapes, snus, hookah and the nicotine products hooking the next generation.",
  blurb="Nicotine is the most widely used addictive drug on earth — and the only one still marketed legally to adults everywhere. Most smokers start before 18. Every form carries its own harm profile: combustion cancer, nicotine pouches rewiring adolescent brains, hookah's hour-long smoke sessions.",
  stat=("8M","deaths per year worldwide from tobacco (WHO)")),
})
