# MDMA city rankings by region — same sourced, hedged, citable formula as the
# meth/cocaine pages. Method note: no country measures MDMA use per city directly;
# rankings combine wastewater analysis, surveys, seizures and hospital data.

MDMA_CITY_PAGES = [
 dict(slug="mdma-cities-usa", region="United States", title="Top 10 US cities with the most MDMA use",
  updated="September 2026", read="7 min", image="https://plugreports.com/media/drugs/molly.jpeg",
  desc="Where 'molly' moves most in America — Miami, Vegas, NYC and the festival-driven markets, ranked from survey data, DEA lab reports and nightlife-market evidence.",
  stats=[("2.1 M","Americans used MDMA in the past year (NSDUH)"),("52 kg","record MDMA seizure by Argentina's PFA (2026) — most US-bound supply moves as powder/pills via mail"),("18–25","the age band that drives almost all US MDMA use")],
  intro="The US has no city-level wastewater ranking for MDMA, so this list triangulates SAMHSA survey data, DEA NFLIS forensic-lab reports, seizure reporting and the geography of the live-music economy. The pattern is consistent: MDMA concentrates in nightlife and festival cities — Miami, Las Vegas, New York, LA — plus college-dense metros. Unlike cocaine, use is event-driven: holiday weekends and festival seasons move the numbers.",
  cities=[
   ("1","Miami, FL","America's club-capital MDMA market — Ultra Music Festival and the year-round South Beach/club economy make Miami the country's most visible MDMA city in DEA reporting."),
   ("2","Las Vegas, NV","EDC Las Vegas alone draws half a million attendees; Nevada's MDMA indicators spike around every major festival weekend. The Strip's club scene keeps baseline demand high all year."),
   ("3","New York City, NY","The largest nightlife economy in America — Brooklyn warehouse parties to Manhattan clubs. NYC posts among the highest MDMA lab-report counts in NFLIS metro data."),
   ("4","Los Angeles, CA","California has the largest MDMA user population of any state; LA's festival circuit (and its role as a distribution hub) anchors the West Coast market."),
   ("5","San Francisco / Bay Area, CA","The historical home of American rave culture; the Bay Area's electronic-music economy keeps MDMA use rates among the country's highest."),
   ("6","Chicago, IL","The Midwest's MDMA hub — a large club and festival scene (Lollapalooza, house music's birthplace) with steady lab-report volume."),
   ("7","Denver, CO","Colorado's young demographics and Red Rocks/festival culture give Denver one of the highest per-capita MDMA profiles in the country."),
   ("8","Austin, TX","SXSW, ACL and a huge student population make Austin Texas's MDMA capital."),
   ("9","Seattle, WA","The Pacific Northwest's electronic-music scene and young tech workforce keep Seattle in the top band of survey indicators."),
   ("10","Atlanta, GA","The Southeast's club and hip-hop nightlife hub; Georgia's MDMA lab reports concentrate in metro Atlanta."),
  ],
  notes="Honorable mentions: New Orleans (festival + tourism), San Diego, Boston (student density) and Washington DC. The pattern: MDMA follows festivals and clubs, not ports — it arrives by mail and courier, so every festival city is its own market.",
  method="Methodology: composite of SAMHSA NSDUH past-year MDMA use estimates, DEA NFLIS-Drug metro report counts, festival/nightlife market data and seizure reporting (2023–26). No wastewater ranking exists for US MDMA; rankings are directional.",
  sources=["SAMHSA National Survey on Drug Use and Health 2023–24","DEA NFLIS-Drug 2025","DEA National Drug Threat Assessment 2025","EDC/Ultra festival market reporting"]),

 dict(slug="mdma-cities-canada", region="Canada", title="Top 10 Canadian cities with the most MDMA use",
  updated="September 2026", read="6 min", image="https://plugreports.com/media/drugs/xtc-pills.jpeg",
  desc="Toronto, Montreal and Vancouver lead Canada's MDMA map — a festival-and-club market measured through wastewater comparisons, border seizures and police data.",
  stats=[("Top-3","Toronto, Montreal, Vancouver dominate every Canadian MDMA indicator"),("~1%","past-year MDMA use among Canadian adults (higher in the 18–24 band)"),("Mail order","dominant supply route — MDMA arrives by post from NL/BE labs more than overland")],
  intro="Canada's MDMA market mirrors its nightlife geography: Toronto's club district, Montreal's festival calendar and Vancouver's rave scene lead, with university cities close behind. Canada is also a documented producer/exporter of MDMA (superlabs in BC and Ontario), which keeps domestic prices low and purity relatively high — and drives police lab-report counts in production regions.",
  cities=[
   ("1","Toronto, ON","Canada's biggest MDMA market — the largest club economy, the biggest festivals, and Ontario's production labs nearby."),
   ("2","Montreal, QC","Osheaga, Igloofest and North America's most famous after-hours scene; Montreal consistently posts top-tier MDMA indicators."),
   ("3","Vancouver, BC","BC's rave culture plus the province's MDMA superlabs make Vancouver both a consumption and production center."),
   ("4","Calgary, AB","Alberta's largest market — young demographics and oil-income nightlife spending."),
   ("5","Ottawa, ON","University-driven market between Toronto and Montreal supply lines."),
   ("6","Edmonton, AB","Pairs with Calgary as Alberta's twin market; steady festival-season spikes."),
   ("7","Winnipeg, MB","The prairies' distribution point for club drugs as well as meth."),
   ("8","Quebec City, QC","Quebec's second market, tied to Montreal networks and a large student population."),
   ("9","Halifax, NS","Atlantic Canada's university city — five universities drive a seasonal market."),
   ("10","Victoria / Kelowna, BC","BC's interior and island festival scenes (Shambhala region) spike every summer."),
  ],
  notes="Festival effect: Shambhala (BC), Osheaga (Montreal) and Veld (Toronto) create measurable regional spikes every summer. Note that Canada both consumes and exports MDMA — production-bust cities (interior BC, rural Ontario) are supply-side, not demand-side.",
  method="Methodology: composite of Health Canada survey data, CBSA seizure reporting, provincial police lab-report counts and festival-market evidence (2023–26). Rankings are directional.",
  sources=["Health Canada Canadian Drug Use Survey","CBSA seizure reporting 2025–26","Statistics Canada police-reported data","EUDA international wastewater comparisons"]),

 dict(slug="mdma-cities-europe", region="Europe", title="Top 10 European cities with the most MDMA use",
  updated="September 2026", read="7 min", image="https://plugreports.com/media/drugs/mdma.jpeg",
  desc="Europe's MDMA capitals measured in sewage: Amsterdam, Eindhoven, Zurich and Antwerp lead the SCORE/EUDA wastewater ranking — and the pills keep getting stronger.",
  stats=[("130","cities measured for MDMA metabolites in the 2025 SCORE wastewater study"),("NL + BE","the Netherlands and Belgium produce most of the world's MDMA — and consume plenty"),("Weekend +","MDMA loads spike sharply on weekends — the clearest 'party drug' signature in the study")],
  intro="Europe measures MDMA the way it measures cocaine: the SCORE group's wastewater study tracks MDMA metabolites in 130 cities across 28 countries. The results are dominated by the production belt — Dutch and Belgian cities post the continent's highest loads — followed by Swiss, German and Spanish nightlife cities. The weekend-spike pattern is stronger for MDMA than for any other drug in the study: this is a Friday-and-Saturday-night substance.",
  cities=[
   ("1","Amsterdam, NL","Europe's MDMA capital by wastewater load — home market of the world's MDMA production industry, with a club culture (ADE, warehouse raves) to match."),
   ("2","Eindhoven, NL","The production heartland: Brabant's lab region posts MDMA loads that rival Amsterdam — supply-side proximity shows up in the sewage."),
   ("3","Zurich, CH","Switzerland's richest city combines high purchasing power with a huge techno scene (Street Parade draws ~1 million) — consistently top-three in wastewater."),
   ("4","Antwerp, BE","Belgium's party cities sit next to the production belt; Antwerp leads Belgium's MDMA indicators as it does cocaine's."),
   ("5","Barcelona, ES","Spain's club capital (Sónar, the year-round techno calendar) — top of Spain's MDMA wastewater league."),
   ("6","Berlin, DE","The world's techno capital. Berlin's club scene (Berghain and beyond) drives Germany's highest per-capita MDMA indicators."),
   ("7","London, UK","The UK's largest MDMA market — a huge club and festival economy; British pill-testing (The Loop) data shows UK pills among Europe's strongest."),
   ("8","Utrecht, NL","The Netherlands' fourth city posts MDMA loads matching the big three — Dutch cities dominate the top of the table as a bloc."),
   ("9","Prague, CZ","Central Europe's party-tourism capital — cheap, famous nightlife draws a regional crowd."),
   ("10","Manchester, UK","The UK's northern nightlife powerhouse — Warehouse Project and a student population of 100,000 keep Manchester in the UK's top tier."),
  ],
  notes="Watch the purity trend: European MDMA pills have averaged well above 150 mg per pill in recent years — double a standard dose — which is why festival pill-testing keeps warning about 'super-strength' batches. Weekend wastewater spikes exceed weekday loads several-fold in most top-10 cities.",
  method="Methodology: SCORE/EUDA wastewater analysis 2025 (130 cities, 28 countries), national survey data, seizure and pill-testing (The Loop, DIMS) reports. Rankings are directional; mid-table positions are a band.",
  sources=["SCORE/EUDA wastewater study 2025","EMCDDA European Drug Report 2025","The Loop / DIMS pill-testing reports","National crime and health surveys"]),

 dict(slug="mdma-cities-australia", region="Australia", title="Top 10 Australian cities with the most MDMA use",
  updated="September 2026", read="6 min", image="https://plugreports.com/media/drugs/mdma.jpg",
  desc="Sydney and Melbourne lead Australia's MDMA map — the ACIC wastewater program tracks the festival-driven market from Byron Bay to Perth.",
  stats=[("Record","national MDMA consumption measured by ACIC wastewater in the latest reporting year"),("2×","capital-city MDMA use vs regional areas — the opposite of meth"),("Dec–Mar","festival season — Australia's MDMA calendar is summer-driven")],
  intro="Australia has excellent MDMA data: the ACIC's National Wastewater Drug Monitoring Program measures MDMA at ~60 sites covering most of the population. The pattern is the mirror image of meth: MDMA is a capital-city, weekend-and-festival drug, with Sydney and Melbourne leading on absolute consumption and summer spikes around the festival calendar. Australia is also a high-price market — pills and caps here cost 3–5× European street prices.",
  cities=[
   ("1","Sydney, NSW","Australia's largest MDMA market — the biggest club economy and festival calendar (and historically its strictest policing, which shaped the pill-testing debate)."),
   ("2","Melbourne, VIC","The live-music capital — Melbourne's club and warehouse scene keeps it level with Sydney in wastewater terms."),
   ("3","Brisbane, QLD","Queensland's hub — steady year-round club demand plus the festival corridor down to Byron Bay."),
   ("4","Perth, WA","The most isolated big city in the world still posts high per-capita MDMA loads — a young, cashed-up market."),
   ("5","Gold Coast, QLD","Tourism + nightlife + Schoolies week: the Gold Coast's MDMA indicators spike hard in November–December."),
   ("6","Byron Bay / Northern Rivers, NSW","Small population, huge festival footprint (Splendour in the Grass region) — per-capita indicators are among Australia's highest."),
   ("7","Adelaide, SA","A steady mid-table market with strong festival-season spikes."),
   ("8","Canberra, ACT","Home of Australia's first fixed pill-testing trial (CanTEST) — the data from it shows just how strong and mis-sold the local supply is."),
   ("9","Hobart, TAS","Small but growing market — Tasmania's indicators have risen every recent reporting period."),
   ("10","Darwin, NT","The smallest capital — MDMA indicators are modest here; Darwin's stimulant problem is meth, not MDMA."),
  ],
  notes="The Australian quirk: MDMA here is expensive (~$25–$35 per pill/cap) and frequently mis-sold — CanTEST pill-testing has found everything from high-dose MDMA to cathinones sold as 'molly'. Festival season (December–March) is when the hospital presentations spike.",
  method="Methodology: ACIC National Wastewater Drug Monitoring Program (Year 9+ reporting), state survey data, seizure reporting, CanTEST/The Loop pill-testing results. Rankings are directional.",
  sources=["ACIC National Wastewater Drug Monitoring Program","AIHW National Drug Strategy Household Survey","CanTEST pill-testing reports","State police seizure data 2025–26"]),

 dict(slug="mdma-cities-middle-east", region="Middle East", title="Top Middle East cities for MDMA use", updated="September 2026", read="6 min", image="https://plugreports.com/media/drugs/mdma-nasal-spray.jpg",
  desc="Tel Aviv and Dubai anchor the Middle East's small but fast-growing MDMA market — an honest, hedged ranking for a region with thin public data.",
  stats=[("Thin data","no Middle East country publishes city-level MDMA monitoring — this ranking is hedged"),("Top-2","Tel Aviv and Dubai dominate every available indicator"),("Mail + mules","supply arrives from European labs by post and courier")],
  intro="Honest framing first: the Middle East has no wastewater monitoring for MDMA and limited published survey data, so this page triangulates seizure reporting, nightlife-market evidence and UNODC regional assessments. The market is small but growing fast, concentrated in wealthy, internationally connected cities with big nightlife or expatriate scenes. Treat every position as a band, not a rank.",
  cities=[
   ("1","Tel Aviv, IL","The Middle East's undisputed party capital — a world-famous techno scene, and Israel posts the region's highest MDMA indicators by a wide margin."),
   ("2","Dubai, AE","The Gulf's nightlife and expatriate hub — UAE customs seizures of MDMA pills and powder have grown steadily with the city's club economy."),
   ("3","Beirut, LB","Lebanon's famous nightlife has long included a club-drug market despite economic collapse; supply arrives via Europe-connected networks."),
   ("4","Amman, JO","Jordan's capital has a small, private-party-driven market; Jordan is also a transit corridor (Captagon routes) where other synthetics move."),
   ("5","Istanbul, TR","Bridging Europe and the Middle East — Turkey's largest city has a growing electronic-music scene and rising MDMA seizures."),
   ("6","Doha, QA","Small but wealthy market with growing expatriate nightlife demand."),
   ("7","Riyadh, SA","Saudi's opening entertainment sector (Soundstorm festival draws hundreds of thousands) has created a new, heavily policed market."),
   ("8","Kuwait City, KW","Small, private-network market — seizures are rare but rising."),
  ],
  notes="Critical context: penalties in the Gulf states are severe (long prison terms for possession; worse for supply), and several countries conduct drug testing of residents and visitors. The region's dominant stimulant by far is Captagon (fenethylline) — MDMA is a niche, affluent-city market by comparison.",
  method="Methodology: UNODC regional assessments, national customs seizure reporting (UAE, Saudi, Jordan), nightlife-market evidence. No wastewater or reliable survey data exists; rankings are hedged bands.",
  sources=["UNODC World Drug Report 2025","UAE/Saudi customs seizure reporting","Israeli anti-drug authority reporting","Regional press investigations"]),

 dict(slug="mdma-cities-africa", region="Africa", title="Top African cities for MDMA use",
  updated="September 2026", read="6 min", image="https://plugreports.com/media/busts/argentina-mdma-52kg-pfa.jpeg",
  desc="Cape Town, Johannesburg and Nairobi lead Africa's emerging MDMA market — an honest, hedged ranking for a continent with little monitoring.",
  stats=[("Thin data","no African country publishes city-level MDMA monitoring — this ranking is hedged"),("ZA leads","South Africa dominates African MDMA indicators"),("Growing","East African seizures and festival scenes are rising from a small base")],
  intro="Honest framing first: Africa has no MDMA wastewater monitoring and sparse survey data. This ranking triangulates UNODC reporting, national seizure data and nightlife-market evidence. The market is concentrated in South Africa's big cities, with emerging scenes in East African capitals. Treat positions as bands.",
  cities=[
   ("1","Cape Town, ZA","Africa's MDMA capital — a world-class festival and techno scene (and psytrance heartland) drives South Africa's strongest demand."),
   ("2","Johannesburg, ZA","The continent's biggest club economy — Joburg's nightlife and affluent northern suburbs anchor the national market."),
   ("3","Durban, ZA","Port city with a growing festival and club scene; supply lines run through the harbor."),
   ("4","Nairobi, KE","East Africa's emerging hub — a young, internationally connected nightlife scene; Kenyan MDMA seizures have risen steadily."),
   ("5","Lagos, NG","West Africa's biggest nightlife economy — MDMA is an affluent-neighborhood and club market layered on top of Nigeria's larger tramadol and cannabis markets."),
   ("6","Accra, GH","Ghana's capital has a growing returnee- and tourist-driven scene (Detty December)."),
   ("7","Marrakech / Casablanca, MA","Morocco's festival and tourism economy (Oasis, and the European party-tourism circuit) drives North Africa's largest MDMA indicators."),
   ("8","Kampala, UG","East Africa's rising party city — Nyege Nyege festival put it on the international electronic-music map."),
  ],
  notes="Context: MDMA is a small, affluent market in Africa compared to the continent's dominant drug stories — tramadol in West Africa, kush in Sierra Leone/Liberia, nyaope and meth (tik) in Southern Africa. But festival-driven demand is growing fast in South Africa, Kenya and Ghana.",
  method="Methodology: UNODC World Drug Report, national seizure reporting (South Africa, Kenya, Nigeria, Morocco), festival/nightlife market evidence. No monitoring data exists; rankings are hedged bands.",
  sources=["UNODC World Drug Report 2025","SAPS seizure reporting","Kenya NACADA reporting","Regional press investigations"]),
]
