# Drug library expansion — 100 additional profiles (2026-09-29).
# Focus: dangerous substances not yet covered + high-use societal gaps
# (fentanyl analogs, nitazenes, RC benzos, regional combos, OTC abuse,
# inhalants, doping agents). Same schema as data_drugs.py.

DRUGS_EXPANSION = [
# ---------------- OPIOIDS (new) ----------------
dict(slug="butyrylfentanyl", name="Butyrylfentanyl", aliases=["BF", "Butyryl fent"],
 category="opioids", schedule="Schedule I (US, 2016)",
 appearance="White/off-white powder; also pressed into counterfeit oxycodone pills",
 effects=["Fentanyl-like euphoria and sedation", "Pain relief", "Shorter duration than fentanyl"],
 risks=["Roughly 1/7 the potency of fentanyl — but still fatal in milligram errors", "Often sold as heroin or fake pills", "Multiple naloxone doses usually needed"],
 overdoseSigns=["Pinpoint pupils", "Slow or stopped breathing", "Unresponsive, limp body"],
 streetPrice="~$30–$80/g where found; usually hidden in heroin/pills",
 legalStatus="Schedule I (US); controlled across EU, UK, Canada, Australia",
 lastUpdated="2026-09-29", sources=["DEA", "EMCDDA", "UNODC"]),

dict(slug="cyclopropylfentanyl", name="Cyclopropylfentanyl", aliases=["CPF", "Cyclopropyl fent"],
 category="opioids", schedule="Schedule I (US, 2018)",
 appearance="White powder, indistinguishable from heroin or fentanyl",
 effects=["Potent opioid euphoria", "Sedation", "Respiratory depression"],
 risks=["Potency comparable to fentanyl", "Linked to fatal overdose clusters in the US and Europe", "No safe dose without testing"],
 overdoseSigns=["Respiratory arrest", "Pinpoint pupils", "Blue lips and fingertips"],
 streetPrice="Rarely sold openly — appears as adulterant",
 legalStatus="Schedule I (US); banned in EU/UK/Canada/Australia",
 lastUpdated="2026-09-29", sources=["DEA", "EMCDDA"]),

dict(slug="valerylfentanyl", name="Valerylfentanyl", aliases=["VF", "Valeryl fent"],
 category="opioids", schedule="Schedule I (US, 2018)",
 appearance="White/off-white powder",
 effects=["Opioid euphoria and pain relief", "Sedation"],
 risks=["Weaker than fentanyl milligram-for-milligram but fatal in naive users", "Found in fake pills and heroin mixes", "Dose impossible to judge by eye"],
 overdoseSigns=["Slow breathing", "Pinpoint pupils", "Loss of consciousness"],
 streetPrice="~$30–$70/g equivalent; mostly an adulterant",
 legalStatus="Schedule I (US); controlled in EU/UK/Canada/Australia",
 lastUpdated="2026-09-29", sources=["DEA", "EMCDDA"]),

dict(slug="acrylfentanyl", name="Acrylfentanyl", aliases=["Acryl fent", "Acryloylfentanyl"],
 category="opioids", schedule="Schedule I (US, 2017)",
 appearance="White powder; pressed pills",
 effects=["Strong opioid effects, fast onset"],
 risks=["Potency similar to fentanyl", "Implicated in dozens of EU and US deaths", "Resistant appearance — looks identical to weaker powders"],
 overdoseSigns=["Stopped breathing", "Pinpoint pupils", "Cold, clammy skin"],
 streetPrice="Mostly encountered as a hidden adulterant",
 legalStatus="Schedule I (US); banned across Europe, Canada, Australia",
 lastUpdated="2026-09-29", sources=["DEA", "EMCDDA", "EUDA"]),

dict(slug="ocfentanil", name="Ocfentanil", aliases=["OCF", "Ocfentanyl"],
 category="opioids", schedule="Schedule I (US, 2018)",
 appearance="White powder; counterfeit pills",
 effects=["Fentanyl-type euphoria and sedation"],
 risks=["Slightly less potent than fentanyl but deadly in any weighing error", "Detected in US overdose deaths since 2016", "Frequently mixed with other fentanyls"],
 overdoseSigns=["Respiratory depression", "Pinpoint pupils", "Unresponsive"],
 streetPrice="Adulterant — not sold under its own name",
 legalStatus="Schedule I (US); controlled in EU/UK/Canada/Australia",
 lastUpdated="2026-09-29", sources=["DEA", "CDC"]),

dict(slug="etonitazepipne", name="Etonitazepipne (N-Pyrrolidino Etonitazene)", aliases=["NPE", "Pyrrolidino-nitazene"],
 category="opioids", schedule="Schedule I (US, 2023, class-wide nitazene scheduling)",
 appearance="White/yellow powder; increasingly found in fake oxycodone and heroin",
 effects=["Extremely potent opioid euphoria", "Long sedation"],
 risks=["Potency meets or exceeds fentanyl — among the strongest opioids ever sold on the street", "Overdose clusters across North America and Europe", "May need repeated naloxone doses"],
 overdoseSigns=["Breathing stops quickly", "Pinpoint pupils", "Deep unresponsiveness"],
 streetPrice="~$50–$150/g online; mostly hidden in other drugs",
 legalStatus="Schedule I (US); controlled in UK/EU/Canada/Australia",
 lastUpdated="2026-09-29", sources=["DEA", "UNODC", "EUDA"]),

dict(slug="butonitazene", name="Butonitazene", aliases=["Butonitazene HCl", "Buto"],
 category="opioids", schedule="Schedule I (US, nitazene class)",
 appearance="White/yellowish powder",
 effects=["Potent opioid sedation and euphoria"],
 risks=["Nitazene-class potency (many times morphine)", "Found in counterfeit pills and 'heroin' samples", "Naloxone works but multiple doses may be needed"],
 overdoseSigns=["Slow/stopped breathing", "Pinpoint pupils", "Blue-gray skin"],
 streetPrice="Adulterant; online research-chemical vendors ~$60–$140/g",
 legalStatus="Schedule I (US); controlled in EU/UK/Canada/Australia",
 lastUpdated="2026-09-29", sources=["DEA", "UNODC"]),

dict(slug="etodesnitazene", name="Etodesnitazene (Etazene)", aliases=["Etazene", "Desnitro-etonitazene"],
 category="opioids", schedule="Schedule I (US, nitazene class)",
 appearance="White/tan powder",
 effects=["Opioid euphoria, strong sedation"],
 risks=["Potency estimated around 70× morphine", "Detected in US and European death investigations", "Sold as 'benzo' research chemical — buyers misjudge it"],
 overdoseSigns=["Respiratory arrest", "Pinpoint pupils", "Unresponsive"],
 streetPrice="~$50–$120/g from RC vendors",
 legalStatus="Schedule I (US); controlled in EU/UK/Canada/Australia",
 lastUpdated="2026-09-29", sources=["DEA", "EMCDDA"]),

dict(slug="metodesnitazene", name="Metodesnitazene", aliases=["Metazene", "Desnitro-metonitazene"],
 category="opioids", schedule="Schedule I (US, nitazene class)",
 appearance="White/off-white powder",
 effects=["Opioid euphoria and sedation"],
 risks=["Potency roughly comparable to fentanyl", "Appeared in street supply after first nitazene bans", "Unknown interaction profile with other depressants"],
 overdoseSigns=["Slow breathing", "Pinpoint pupils", "Loss of consciousness"],
 streetPrice="~$50–$120/g online; also an adulterant",
 legalStatus="Schedule I (US); controlled in EU/UK/Canada/Australia",
 lastUpdated="2026-09-29", sources=["DEA", "UNODC"]),

dict(slug="cychlorphine", name="Cychlorphine", aliases=["Cychlorphine HCl", "N-propionitrile chlorphine"],
 category="opioids", schedule="Unscheduled analog (prosecuted under US Analogue Act); banned in several EU states",
 appearance="White crystalline powder sold by online opioid vendors",
 effects=["Extremely potent opioid euphoria", "Long duration"],
 risks=["Reported potency hundreds of times morphine — among the strongest opioids in the 2024–25 supply", "Emerging cause of fatal overdoses in Europe and North America", "Standard fentanyl test strips do not detect it"],
 overdoseSigns=["Rapid respiratory arrest", "Pinpoint pupils", "Prolonged coma — needs multiple naloxone doses"],
 streetPrice="~$80–$200/g from gray-market vendors",
 legalStatus="Analogue prosecutions in the US; specifically banned in parts of the EU; treat as illegal everywhere",
 lastUpdated="2026-09-29", sources=["UNODC", "EUDA", "CFSRE"]),

dict(slug="u-48800", name="U-48800", aliases=["U-48800 HCl", "U4 analog"],
 category="opioids", schedule="Unscheduled analog (US Analogue Act applies); controlled in several countries",
 appearance="White powder sold as 'research chemical' opioid",
 effects=["Opioid euphoria and sedation, similar to U-47700"],
 risks=["Replaced U-47700 after its ban — similar death profile", "Short duration drives compulsive redosing", "Corrosive to veins and nasal tissue"],
 overdoseSigns=["Respiratory depression", "Pinpoint pupils", "Unresponsive"],
 streetPrice="~$40–$100/g online",
 legalStatus="Effectively illegal as an analog in the US; controlled in UK/EU/Canada/Australia",
 lastUpdated="2026-09-29", sources=["DEA", "UNODC"]),

dict(slug="ap-238", name="AP-238", aliases=["AP-238 HCl", "Bucinnazine analog"],
 category="opioids", schedule="Unscheduled analog; banned in several EU states",
 appearance="White powder, sometimes in solution",
 effects=["Opioid euphoria, moderate potency", "Sedation"],
 risks=["Weaker than fentanyl but deaths reported when combined with benzos or alcohol", "Sold as 'legal opioid' — a false sense of safety", "Dependence develops quickly"],
 overdoseSigns=["Slow breathing", "Pinpoint pupils", "Sedation to unconsciousness"],
 streetPrice="~$40–$90/g online",
 legalStatus="Analogue risk in the US; controlled in parts of the EU",
 lastUpdated="2026-09-29", sources=["UNODC", "EMCDDA"]),

dict(slug="pentazocine", name="Pentazocine (Talwin)", aliases=["Talwin", "Ts (with Ritalin = 'T's and blues')"],
 category="opioids", schedule="Schedule IV (US)",
 appearance="Tablets; historically injected after crushing ('T's and blues' with tripelennamine)",
 effects=["Mixed opioid agonist-antagonist: mild euphoria, pain relief"],
 risks=["Injecting crushed tablets causes severe lung and skin damage", "Can trigger withdrawal in dependent users", "Seizures in overdose, especially with tripelennamine"],
 overdoseSigns=["Slow breathing", "Confusion, hallucinations", "Seizures"],
 streetPrice="~$2–$5/tablet where diverted",
 legalStatus="Prescription-only; Schedule IV (US), controlled elsewhere",
 lastUpdated="2026-09-29", sources=["DEA", "NIDA"]),

dict(slug="nalbuphine", name="Nalbuphine (Nubain)", aliases=["Nubain", "Nubain injection"],
 category="opioids", schedule="Unscheduled federally (US); prescription-only, controlled in many states and countries",
 appearance="Injectable solution; diverted ampoules",
 effects=["Mixed agonist-antagonist opioid: pain relief, mild euphoria"],
 risks=["Abused by bodybuilders to counter steroid-cycle pain — dependence follows", "Triggers withdrawal in opioid-dependent users", "Injection-site infections"],
 overdoseSigns=["Slow breathing", "Extreme drowsiness", "Dizziness, low blood pressure"],
 streetPrice="~$10–$25 per ampoule diverted",
 legalStatus="Prescription-only worldwide",
 lastUpdated="2026-09-29", sources=["DEA", "NIDA"]),

dict(slug="levorphanol", name="Levorphanol (Levo-Dromoran)", aliases=["Levo-Dromoran", "Levorphan"],
 category="opioids", schedule="Schedule II (US)",
 appearance="Tablets (2 mg); injectable",
 effects=["Long-acting opioid pain relief", "Euphoria", "Sedation"],
 risks=["Roughly 4–8× morphine potency with a long, stacking half-life — easy to overdose by redosing", "Strong respiratory depression", "NMDA activity complicates mixing"],
 overdoseSigns=["Slow breathing", "Pinpoint pupils", "Deep sedation"],
 streetPrice="~$10–$30/tablet diverted",
 legalStatus="Schedule II (US); prescription-only everywhere",
 lastUpdated="2026-09-29", sources=["DEA", "NIDA"]),

dict(slug="dextropropoxyphene", name="Dextropropoxyphene (Darvon / Darvocet)", aliases=["Darvon", "Darvocet (with APAP)", "Proxyphene"],
 category="opioids", schedule="Withdrawn in US/EU (2010); still found in some markets",
 appearance="Pink capsules/tablets; combination pills with paracetamol",
 effects=["Weak opioid euphoria", "Pain relief"],
 risks=["Banned for causing fatal heart-rhythm disturbances even at normal doses", "Overdose is fast and often fatal — heart stops before breathing", "Old stock and foreign pills still circulate"],
 overdoseSigns=["Sudden collapse, cardiac arrest", "Slow breathing", "Seizures"],
 streetPrice="Black-market relic — price varies widely",
 legalStatus="Withdrawn/banned in the US, UK and EU; any supply is illicit",
 lastUpdated="2026-09-29", sources=["FDA", "EMA", "WHO"]),

dict(slug="tilidine", name="Tilidine (Valoron)", aliases=["Valoron", "Tilidin", "Tili"],
 category="opioids", schedule="Prescription-only (Germany/EU); not marketed in the US",
 appearance="Drops, capsules and extended-release tablets (often combined with naloxone)",
 effects=["Opioid euphoria, warm sedation", "Pain relief"],
 risks=["Germany's most-abused prescription opioid — especially among teens", "Drops are easy to overdose; syrup-style mixing is common", "Dependence and withdrawal like other opioids"],
 overdoseSigns=["Slow breathing", "Pinpoint pupils", "Unresponsive"],
 streetPrice="~€1–€3 per 50 mg equivalent on the street",
 legalStatus="Prescription-only across Europe; possession without script is illegal",
 lastUpdated="2026-09-29", sources=["EMCDDA", "BfArM", "UNODC"]),

dict(slug="ketobemidone", name="Ketobemidone (Ketogan)", aliases=["Ketogan", "Ketobemidon"],
 category="opioids", schedule="Prescription-only (Nordics/EU); Schedule I equivalent elsewhere",
 appearance="Tablets and injection; diverted in Scandinavia",
 effects=["Potent opioid euphoria (~morphine-level)", "Pain relief"],
 risks=["Long history of injecting misuse in Sweden, Norway and Denmark", "Seizures reported in overdose", "Strong dependence"],
 overdoseSigns=["Slow breathing", "Pinpoint pupils", "Seizures", "Unresponsive"],
 streetPrice="~€5–€15 per tablet diverted",
 legalStatus="Prescription-only; strictly controlled in the Nordics and EU",
 lastUpdated="2026-09-29", sources=["EMCDDA", "UNODC"]),

dict(slug="sublocade", name="Sublocade (Buprenorphine Depot Injection)", aliases=["Sublocade", "Monthly bupe shot", "Buvidal (EU/AU)"],
 category="opioids", schedule="Schedule III (US)",
 appearance="Monthly subcutaneous depot injection given in clinics",
 effects=["Steady buprenorphine levels — blocks cravings and withdrawal for a month", "Blunts the effect of other opioids"],
 risks=["Injection-site lumps and pain", "Attempts to divert or dissolve the depot are dangerous", "Overdose possible if combined with benzos or alcohol"],
 overdoseSigns=["Slow breathing (with other depressants)", "Extreme sedation", "Pinpoint pupils"],
 streetPrice="Treatment medication — diversion is uncommon but exists",
 legalStatus="Prescription-only; administered by licensed providers",
 lastUpdated="2026-09-29", sources=["FDA", "SAMHSA", "NIDA"]),

dict(slug="mitragynine-pseudoindoxyl", name="Mitragynine Pseudoindoxyl", aliases=["MP", "7-OH metabolite analog", "Pseudoindoxyl kratom"],
 category="opioids", schedule="Unscheduled; appears in concentrated kratom products",
 appearance="Semi-synthetic kratom alkaloid in high-potency extracts, shots and gummies",
 effects=["Opioid-like euphoria far stronger than plain kratom leaf", "Pain relief", "Sedation"],
 risks=["Potency estimated well above morphine — nothing like plain leaf kratom", "Shows up in '7-OH' and extract products without labeling", "Dependence and opioid-style withdrawal reported"],
 overdoseSigns=["Slow breathing", "Heavy sedation", "Nausea, pinpoint pupils"],
 streetPrice="Sold in extract shots/gummies ~$10–$30 each",
 legalStatus="Gray zone — sold as 'kratom extract'; several US states are moving to ban concentrated alkaloids",
 lastUpdated="2026-09-29", sources=["FDA", "NIDA", "UNODC"]),

dict(slug="dextromoramide", name="Dextromoramide (Palfium)", aliases=["Palfium", "Dextromoramide tartrate"],
 category="opioids", schedule="Withdrawn in most countries; Schedule I (US)",
 appearance="Tablets (historically 5–10 mg); illicit stock circulates in parts of Europe and Asia",
 effects=["Short, intense opioid euphoria", "Pain relief"],
 risks=["'Short-acting heroin' — extreme redosing compulsion", "Withdrawn because of abuse and fatal overdoses", "Crushing and injecting tablets is especially damaging"],
 overdoseSigns=["Slow breathing", "Pinpoint pupils", "Unresponsive"],
 streetPrice="Rare; high black-market prices where found",
 legalStatus="Withdrawn/banned in most of the world",
 lastUpdated="2026-09-29", sources=["UNODC", "EMCDDA"]),

dict(slug="dipipanone", name="Dipipanone (Diconal)", aliases=["Diconal", "Dipipanone-cyclizine"],
 category="opioids", schedule="Withdrawn in the UK; Schedule I (US)",
 appearance="Tablets combined with cyclizine (Diconal); illicit leftovers and lookalikes",
 effects=["Strong opioid euphoria", "Sedation"],
 risks=["Notorious in the UK for injection deaths — cyclizine gave a 'rush' that drove IV use", "Withdrawn due to fatal abuse", "Any current supply is illicit or counterfeit"],
 overdoseSigns=["Slow breathing", "Pinpoint pupils", "Collapse"],
 streetPrice="Rare relic; prices vary",
 legalStatus="Withdrawn/banned in the UK and US",
 lastUpdated="2026-09-29", sources=["EMCDDA", "UNODC"]),

dict(slug="nurofen-plus", name="Codeine–Ibuprofen (Nurofen Plus) Abuse", aliases=["Nurofen Plus", "Co-codaprin", "Co-codamol OTC variants"],
 category="opioids", schedule="OTC (some countries, low-dose); prescription at higher doses",
 appearance="Over-the-counter combination tablets (codeine 12.8 mg + ibuprofen 200 mg)",
 effects=["Mild opioid euphoria and relaxation", "Pain relief"],
 risks=["High-dose abuse floods the body with ibuprofen — stomach bleeding, kidney failure", "Gateway to stronger opioids for some users", "Daily-codeine dependence develops quietly"],
 overdoseSigns=["Stomach pain, black stools (GI bleed)", "Slow breathing", "Confusion, ringing ears"],
 streetPrice="~$8–$15 per pack OTC; abuse runs to multiple packs daily",
 legalStatus="OTC behind-the-counter in Australia/UK (low dose); codeine-only products prescription-only in many countries",
 lastUpdated="2026-09-29", sources=["TGA", "MHRA", "NIDA"]),
]

DRUGS_EXPANSION += [
# ---------------- STIMULANTS (new) ----------------
dict(slug="methcathinone", name="Methcathinone (Cat / Ephedrone)", aliases=["Cat", "Ephedrone", "Jeff", "Mulka"],
 category="stimulants", schedule="Schedule I (US)",
 appearance="White/off-white powder or damp paste; home-cooked from ephedrine in Russia/Eastern Europe and South Africa",
 effects=["Intense euphoria and energy", "Talkativeness, confidence", "Appetite suppression"],
 risks=["Manganese-based home synthesis causes irreversible Parkinson-like brain damage", "Binges last days with severe crash", "Psychosis with repeated use"],
 overdoseSigns=["Extreme agitation", "Chest pain, racing heart", "Hyperthermia, seizures"],
 streetPrice="~$20–$60/g in Southern Africa and Eastern Europe",
 legalStatus="Schedule I (US); illegal in South Africa, Russia, EU",
 lastUpdated="2026-09-29", sources=["DEA", "UNODC", "EMCDDA"]),

dict(slug="2-mmc", name="2-MMC", aliases=["2-Methylmethcathinone", "2MMC"],
 category="stimulants", schedule="Controlled in NL/EU; analog risk in the US",
 appearance="White crystals or powder sold as 'legal mephedrone'",
 effects=["Stimulation and mild euphoria", "Sociability", "Less empathogenic than 3-MMC/4-MMC"],
 risks=["Filled the gap after 3-MMC/4-MMC bans — risks under-studied", "Compulsive redosing", "Often mis-sold as 3-MMC"],
 overdoseSigns=["Agitation", "Rapid heartbeat", "Overheating"],
 streetPrice="~€15–€40/g from EU webshops",
 legalStatus="Banned in the Netherlands and several EU states; US Analogue Act risk",
 lastUpdated="2026-09-29", sources=["EMCDDA", "EUDA", "UNODC"]),

dict(slug="3-fma", name="3-FMA (3-Fluoromethamphetamine)", aliases=["3-FMA", "3-Fluorometh"],
 category="stimulants", schedule="Unscheduled analog; Analogue Act risk (US)",
 appearance="White powder or pellets from RC vendors",
 effects=["Meth-like stimulation and euphoria", "Long duration", "Focus and wakefulness"],
 risks=["Barely studied — assumed meth-like neurotoxicity", "Long duration fuels redosing and psychosis", "Cardiovascular strain"],
 overdoseSigns=["Agitation, paranoia", "Chest pain", "Hyperthermia"],
 streetPrice="~$30–$70/g online",
 legalStatus="Analog of methamphetamine — effectively illegal in the US; controlled in parts of the EU",
 lastUpdated="2026-09-29", sources=["UNODC", "EMCDDA"]),

dict(slug="isopropylphenidate", name="Isopropylphenidate (IPH)", aliases=["IPH", "Isopropyl Ritalin"],
 category="stimulants", schedule="Unscheduled analog; controlled in UK (2015)",
 appearance="White powder or pressed pellets",
 effects=["Ritalin-like focus and stimulation", "Mild euphoria"],
 risks=["Longer and harsher than methylphenidate — insomnia, anxiety", "Snorting damages nasal tissue", "Sold as 'study drug' to students"],
 overdoseSigns=["Agitation", "Racing heart", "Sleeplessness for 24h+"],
 streetPrice="~$20–$50/g online",
 legalStatus="Controlled in the UK; analog risk in the US",
 lastUpdated="2026-09-29", sources=["EMCDDA", "UNODC"]),

dict(slug="amfepramone", name="Amfepramone (Diethylpropion / Tenuate)", aliases=["Tenuate", "Diethylpropion", "Amfepramon"],
 category="stimulants", schedule="Schedule IV (US)",
 appearance="Tablets (25/75 mg) prescribed for weight loss; diverted",
 effects=["Mild amphetamine-like stimulation", "Appetite suppression", "Alertness"],
 risks=["Abused in high doses for the buzz — dependence follows", "Heart strain, blood-pressure spikes", "Insomnia and irritability"],
 overdoseSigns=["Agitation", "Rapid heartbeat", "Tremor, sweating"],
 streetPrice="~$2–$5/tablet diverted",
 legalStatus="Prescription-only; Schedule IV (US), controlled in EU/UK",
 lastUpdated="2026-09-29", sources=["DEA", "NIDA"]),

dict(slug="dexmethylphenidate", name="Dexmethylphenidate (Focalin)", aliases=["Focalin", "Focalin XR", "Dex-MPH"],
 category="stimulants", schedule="Schedule II (US)",
 appearance="Tablets and XR capsules; diverted as a study drug",
 effects=["Stronger, cleaner Ritalin effect — focus, wakefulness", "Mild euphoria when snorted or taken in high doses"],
 risks=["Same risks as methylphenidate with roughly double potency per mg", "Insomnia, appetite loss, anxiety", "Abuse-deterrent nothing — XR beads are crushed and snorted"],
 overdoseSigns=["Agitation, panic", "Racing heart, chest pain", "Hyperthermia"],
 streetPrice="~$3–$10/tablet on campus",
 legalStatus="Schedule II (US); prescription-only everywhere",
 lastUpdated="2026-09-29", sources=["DEA", "NIDA"]),

dict(slug="levo-methamphetamine", name="Levo-Methamphetamine (OTC Nasal Inhalers)", aliases=["Vicks inhaler", "Levmetamfetamine", "L-meth"],
 category="stimulants", schedule="OTC (US inhalers); methamphetamine is Schedule II",
 appearance="Nasal inhaler sticks (50 mg levmetamfetamine) sold in US pharmacies",
 effects=["Decongestion; mild stimulation at high doses", "Much weaker central effects than street meth"],
 risks=["Abused by extracting or eating inhaler contents", "High doses strain the heart with little euphoria", "Legal-product illusion lowers caution"],
 overdoseSigns=["Rapid heartbeat", "Anxiety, tremor", "High blood pressure"],
 streetPrice="~$5–$8 per inhaler OTC",
 legalStatus="OTC in the US; extraction/possession for abuse can be prosecuted",
 lastUpdated="2026-09-29", sources=["FDA", "DEA"]),

dict(slug="naphyrone", name="Naphyrone (NRG-1)", aliases=["NRG-1", "Naphthylpyrovalerone", "Energy-1"],
 category="stimulants", schedule="Class B (UK, 2010); controlled across the EU",
 appearance="White powder sold as 'NRG-1' legal high around 2010; still resurfaces",
 effects=["MDPV-like intense stimulation", "Euphoria", "Long duration"],
 risks=["Pyrovalerone family — compulsive redosing and paranoia", "Heart strain and overheating", "Early 'legal high' that drove the UK's generic ban"],
 overdoseSigns=["Severe agitation", "Chest pain", "Hyperthermia, hallucinations"],
 streetPrice="Mostly historical; ~£20–£40/g when found",
 legalStatus="Banned in the UK and most of the EU; US analog risk",
 lastUpdated="2026-09-29", sources=["EMCDDA", "UNODC"]),

dict(slug="2-dpmp", name="2-DPMP (Desoxypipradrol / Ivory Wave)", aliases=["2-DPMP", "D2PM", "Ivory Wave"],
 category="stimulants", schedule="Class B (UK, 2012); controlled in the EU",
 appearance="White powder sold as 'Ivory Wave' bath salts",
 effects=["Extremely long stimulation (24–72 h)", "Alertness, euphoria at low doses"],
 risks=["Half-life so long that one line can mean three days awake", "Severe psychosis and hospital admissions drove its ban", "Heart strain"],
 overdoseSigns=["Prolonged agitation and paranoia", "Hallucinations", "Racing heart"],
 streetPrice="Mostly historical; occasionally in 'bath salts' mixes",
 legalStatus="Banned in the UK/EU; US analog risk",
 lastUpdated="2026-09-29", sources=["EMCDDA", "UNODC"]),

dict(slug="mdai", name="MDAI", aliases=["MDAI", "6,7-Methylenedioxy-2-aminoindane"],
 category="stimulants", schedule="Unscheduled; controlled in Finland and parts of the EU",
 appearance="White/tan powder sold as a 'non-neurotoxic MDMA alternative'",
 effects=["Mild empathogenic warmth", "Relaxation more than stimulation", "Subtle mood lift"],
 risks=["Far weaker than MDMA — users redose into unknown territory", "Barely studied in humans", "Often mis-sold or mixed with stronger cathinones"],
 overdoseSigns=["Nausea", "Agitation at high doses", "Rapid heartbeat"],
 streetPrice="~$30–$60/g online",
 legalStatus="Gray zone; banned in some EU states",
 lastUpdated="2026-09-29", sources=["EMCDDA", "UNODC"]),

dict(slug="cocaethylene", name="Cocaethylene (Cocaine + Alcohol)", aliases=["Cocaethylene", "Coke and booze metabolite"],
 category="stimulants", schedule="Formed in the body — not sold",
 appearance="Not a product: your liver makes it whenever cocaine and alcohol are used together",
 effects=["Longer, stronger euphoria than cocaine alone — which is why people combine them"],
 risks=["Roughly 18–25× more cardiotoxic than cocaine alone", "Biggest single driver of cocaine-related sudden death", "Liver damage with repeated formation"],
 overdoseSigns=["Chest pain, palpitations", "Collapse after a session", "Seizures"],
 streetPrice="N/A — formed in the body",
 legalStatus="N/A — but cocaine and alcohol supply laws apply",
 lastUpdated="2026-09-29", sources=["NIDA", "EMCDDA", "WHO"]),

dict(slug="pre-workout-supplements", name="Pre-Workout Stimulant Blends", aliases=["Pre-workout", "Jack3d-style blends", "DMAA/DMHA powders"],
 category="stimulants", schedule="Legal supplements; DMAA/DMHA banned by FDA but still found",
 appearance="Flavored powders and shots sold in gyms and online",
 effects=["Energy rush, focus, pump", "Appetite suppression"],
 risks=["Many contain banned stimulants (DMAA, DMHA, synephrine stacks) at unlisted doses", "Scoop-by-eye dosing = accidental overdose", "Heart attacks and strokes reported in young gym users"],
 overdoseSigns=["Chest pain, pounding heart", "Dizziness, tunnel vision", "Overheating during exercise"],
 streetPrice="~$30–$60 per tub",
 legalStatus="Legal as supplements; DMAA and DMHA are prohibited ingredients in the US, UK, Australia",
 lastUpdated="2026-09-29", sources=["FDA", "TGA", "WADA"]),
]

DRUGS_EXPANSION += [
# ---------------- BENZODIAZEPINES (new) ----------------
dict(slug="desalkylgidazepam", name="Desalkylgidazepam (Bromonordiazepam)", aliases=["Bromonordiazepam", "Desalkyl-gidazepam"],
 category="benzodiazepines", schedule="Unscheduled RC; analog risk (US)",
 appearance="White powder or pellets from RC vendors",
 effects=["Long-acting benzo sedation and anti-anxiety effect"],
 risks=["Very long half-life — redosing stacks into days of blackout-level sedation", "Amnesia and falls", "Withdrawal seizures after regular use"],
 overdoseSigns=["Extreme drowsiness", "Slurred speech, staggering", "Slow breathing (with opioids/alcohol)"],
 streetPrice="~$1–$3 per pellet online",
 legalStatus="Gray-zone RC; prosecuted as analog in the US; banned in several EU states",
 lastUpdated="2026-09-29", sources=["UNODC", "EMCDDA"]),

dict(slug="adinazolam", name="Adinazolam (Deracyn)", aliases=["Deracyn", "Adinazolam mesylate"],
 category="benzodiazepines", schedule="Unscheduled; sold as RC",
 appearance="Tablets/powder; originally an experimental antidepressant benzo",
 effects=["Alprazolam-like sedation with a mood lift", "Anti-anxiety"],
 risks=["Short-acting — rebound anxiety drives redosing", "Dependence in weeks", "Amnesia at high doses"],
 overdoseSigns=["Deep sedation", "Poor coordination", "Slow breathing with other depressants"],
 streetPrice="~$1–$4 per dose online",
 legalStatus="RC gray zone; analog risk in the US",
 lastUpdated="2026-09-29", sources=["UNODC", "EMCDDA"]),

dict(slug="deschloroetizolam", name="Deschloroetizolam", aliases=["Etizolam metabolite RC", "DCE"],
 category="benzodiazepines", schedule="Unscheduled RC; thienodiazepine",
 appearance="Powder, pellets and blotters",
 effects=["Etizolam-like sedation and anti-anxiety effect"],
 risks=["Active metabolite of etizolam sold directly — potency misjudged", "Blackouts and compulsive redosing", "Withdrawal seizures"],
 overdoseSigns=["Extreme sedation", "Amnesia", "Respiratory depression with opioids"],
 streetPrice="~$1–$3 per pellet",
 legalStatus="RC gray zone; banned in several US states and EU countries",
 lastUpdated="2026-09-29", sources=["UNODC", "EMCDDA"]),

dict(slug="metizolam", name="Metizolam (Desmethyletizolam)", aliases=["Desmethyletizolam", "Metiz"],
 category="benzodiazepines", schedule="Unscheduled RC; banned in Sweden/UK-adjacent lists",
 appearance="Powder and pellets",
 effects=["Thienodiazepine sedation, roughly half etizolam potency per mg"],
 risks=["Users double-dose expecting etizolam strength — then black out on the rebound", "Dependence and withdrawal like other benzos", "Amnesia"],
 overdoseSigns=["Heavy sedation", "Staggering, slurred speech", "Slow breathing with alcohol/opioids"],
 streetPrice="~$1–$3 per pellet",
 legalStatus="RC gray zone; controlled in parts of the EU",
 lastUpdated="2026-09-29", sources=["UNODC", "EMCDDA"]),

dict(slug="flubrotizolam", name="Flubrotizolam", aliases=["Flubrotizolam 0.5 mg", "FANAX substitute"],
 category="benzodiazepines", schedule="Unscheduled RC; banned in several US states",
 appearance="0.5 mg pellets and blotters — the pellet size hides extreme potency",
 effects=["Very potent thienodiazepine sedation at sub-milligram doses"],
 risks=["Among the strongest RC benzos — half a milligram too much = blackout", "Redosing during amnesia causes multi-day blackouts", "Severe withdrawal seizures"],
 overdoseSigns=["Unrousable sedation", "Amnesia for days", "Respiratory depression with opioids"],
 streetPrice="~$2–$5 per pellet",
 legalStatus="RC; banned in several US states; analog risk federally",
 lastUpdated="2026-09-29", sources=["UNODC", "CFSRE"]),

dict(slug="nimetazepam", name="Nimetazepam (Erimin-5)", aliases=["Erimin-5", "Erimin", "Happy 5"],
 category="benzodiazepines", schedule="Prescription-only (Japan/SE Asia); widely trafficked",
 appearance="Small white 5 mg tablets — the classic Southeast Asian party benzo",
 effects=["Strong hypnotic sedation", "Disinhibition, euphoria"],
 risks=["Long history of trafficking and violent-crime association in Malaysia/Singapore/Indonesia", "Mixed with alcohol it causes blackouts", "Dependence and withdrawal seizures"],
 overdoseSigns=["Deep sleep, hard to wake", "Staggering", "Slow breathing with alcohol"],
 streetPrice="~$1–$3 per tablet in SE Asia",
 legalStatus="Prescription-only; trafficking carries severe penalties in SE Asia (caning/death in some states)",
 lastUpdated="2026-09-29", sources=["UNODC", "INCB"]),

dict(slug="brotizolam", name="Brotizolam (Lendormin)", aliases=["Lendormin", "Brotiz"],
 category="benzodiazepines", schedule="Prescription-only (EU/JP/AU); not marketed in the US",
 appearance="0.25 mg tablets — potent triazolobenzodiazepine hypnotic",
 effects=["Fast, strong sleep induction", "Sedation"],
 risks=["Sub-milligram potency — easy to overshoot", "Next-day amnesia and rebound insomnia", "Dependence within weeks of nightly use"],
 overdoseSigns=["Deep sedation", "Confusion, amnesia", "Respiratory depression with other depressants"],
 streetPrice="~$2–$5 per tablet diverted",
 legalStatus="Prescription-only; controlled in the EU, Japan, Australia",
 lastUpdated="2026-09-29", sources=["EMCDDA", "INCB"]),

dict(slug="flurazepam", name="Flurazepam (Dalmane)", aliases=["Dalmane", "Fluraz"],
 category="benzodiazepines", schedule="Schedule IV (US)",
 appearance="Capsules (15/30 mg) prescribed for insomnia",
 effects=["Long-acting benzo sedation", "Sleep induction"],
 risks=["Active metabolite lasts days — daytime impairment stacks up", "Falls and confusion in older users", "Dependence and withdrawal"],
 overdoseSigns=["Prolonged deep sedation", "Poor coordination", "Slow breathing with alcohol/opioids"],
 streetPrice="~$1–$3 per capsule diverted",
 legalStatus="Schedule IV (US); prescription-only worldwide",
 lastUpdated="2026-09-29", sources=["DEA", "NIDA"]),

dict(slug="clorazepate", name="Clorazepate (Tranxene)", aliases=["Tranxene", "Clorazepate dipotassium"],
 category="benzodiazepines", schedule="Schedule IV (US)",
 appearance="Tablets and capsules; long-acting prodrug of nordiazepam",
 effects=["Smooth, long anti-anxiety effect", "Sedation"],
 risks=["Long half-life hides accumulation — overdose creeps up", "Dependence with daily use", "Dangerous with alcohol"],
 overdoseSigns=["Extreme drowsiness", "Slurred speech", "Slow breathing with depressants"],
 streetPrice="~$1–$3 per tablet diverted",
 legalStatus="Schedule IV (US); prescription-only worldwide",
 lastUpdated="2026-09-29", sources=["DEA", "NIDA"]),

dict(slug="gidazepam", name="Gidazepam", aliases=["Gidazepam HCl", "Gidazepamum"],
 category="benzodiazepines", schedule="Prescription-only (Russia/Ukraine); RC elsewhere",
 appearance="Tablets from Eastern European pharmacies; powder online",
 effects=["Daytime anti-anxiety effect with mild activation (unusual for a benzo)"],
 risks=["Sold online as a 'functional' benzo — dependence still develops", "Long-acting metabolites accumulate", "Withdrawal anxiety and seizures"],
 overdoseSigns=["Sedation at high doses", "Poor coordination", "Slow breathing with alcohol"],
 streetPrice="~$0.50–$2 per tablet online",
 legalStatus="Prescription-only in Russia/Ukraine; unscheduled gray zone elsewhere",
 lastUpdated="2026-09-29", sources=["UNODC", "INCB"]),

dict(slug="tofisopam", name="Tofisopam (Grandaxin)", aliases=["Grandaxin", "Tofizopam"],
 category="benzodiazepines", schedule="Prescription-only (Eastern Europe/Russia)",
 appearance="Tablets (50/100 mg) — atypical 2,3-benzodiazepine",
 effects=["Anti-anxiety without much sedation", "Mild stimulation"],
 risks=["Marketed as 'non-addictive benzo' — dependence still reported", "Abused in high doses in Eastern Europe", "Mixing with alcohol removes its safety advantage"],
 overdoseSigns=["Drowsiness", "Nausea", "Low blood pressure"],
 streetPrice="~$0.50–$1.50 per tablet",
 legalStatus="Prescription-only in Eastern Europe and Russia",
 lastUpdated="2026-09-29", sources=["INCB", "EMCDDA"]),

# ---------------- SEDATIVES (new) ----------------
dict(slug="phenobarbital", name="Phenobarbital", aliases=["Phenobarb", "Luminal", "Barbs"],
 category="sedatives", schedule="Schedule IV (US)",
 appearance="Tablets and elixir; old-school barbiturate still prescribed for seizures",
 effects=["Deep sedation", "Anti-seizure", "Drowsy euphoria at high doses"],
 risks=["Classic overdose drug — narrow gap between high and fatal", "Induces liver enzymes, wrecking other medications", "Brutal, sometimes fatal withdrawal"],
 overdoseSigns=["Slow, shallow breathing", "Cold skin, low blood pressure", "Coma"],
 streetPrice="~$1–$3 per tablet diverted",
 legalStatus="Schedule IV (US); controlled worldwide",
 lastUpdated="2026-09-29", sources=["DEA", "WHO", "NIDA"]),

dict(slug="chloral-hydrate", name="Chloral Hydrate", aliases=["Mickey Finn", "Knockout drops", "Chloral"],
 category="sedatives", schedule="Schedule IV (US); largely discontinued",
 appearance="Syrup or capsules; the original 'knockout drops'",
 effects=["Rapid deep sedation", "Sleep"],
 risks=["The 'Mickey Finn' — secretly slipped into drinks to incapacitate", "Severe stomach and heart damage with abuse", "Narrow lethal margin"],
 overdoseSigns=["Unrousable sleep", "Slow breathing", "Irregular heartbeat"],
 streetPrice="Rare; mostly a drink-spiking concern",
 legalStatus="Schedule IV (US); restricted or discontinued in most countries",
 lastUpdated="2026-09-29", sources=["DEA", "FDA"]),

dict(slug="glutethimide", name="Glutethimide (Doriden)", aliases=["Doriden", "Gluteth", "Loads (with codeine)"],
 category="sedatives", schedule="Schedule II (US); withdrawn in many countries",
 appearance="Tablets; notorious combined with codeine as 'loads' or 'pancakes and syrup'",
 effects=["Barbiturate-like euphoric sedation"],
 risks=["'Loads' (glutethimide + codeine) killed users in waves — extreme respiratory depression", "Unpredictable absorption", "Severe withdrawal"],
 overdoseSigns=["Slow breathing", "Coma", "Dilated pupils (unusual for a downer)"],
 streetPrice="Rare relic; high prices where found",
 legalStatus="Schedule II (US); withdrawn in most markets",
 lastUpdated="2026-09-29", sources=["DEA", "UNODC"]),

dict(slug="mecloqualone", name="Mecloqualone", aliases=["Mecloqualone", "Nubarene", "Casfen"],
 category="sedatives", schedule="Schedule I (US); controlled in South Africa/India",
 appearance="Tablets; methaqualone analog sold on the Mandrax market",
 effects=["Mandrax-like hypnotic euphoria", "Muscle relaxation"],
 risks=["Fills the methaqualone gap in Southern Africa and India", "Overdose causes convulsions and coma", "Often smoked with cannabis like Mandrax"],
 overdoseSigns=["Convulsions", "Slow breathing", "Coma"],
 streetPrice="~$1–$3 per tablet in Southern Africa",
 legalStatus="Schedule I (US); banned in South Africa and India",
 lastUpdated="2026-09-29", sources=["UNODC", "INCB"]),

# ---------------- DISSOCIATIVES (new) ----------------
dict(slug="3-ho-pcp", name="3-HO-PCP", aliases=["3-Hydroxyphencyclidine", "3-HO"],
 category="dissociatives", schedule="Unscheduled RC; analog risk (US)",
 appearance="White powder from RC vendors",
 effects=["PCP-like dissociation with opioid-like warmth", "Potent at low milligram doses"],
 risks=["Active at ~5 mg — volumetric dosing errors are common and severe", "Mania and psychosis at high doses", "Long duration (6–12 h)"],
 overdoseSigns=["Agitation, delirium", "Numbness, loss of coordination", "High blood pressure"],
 streetPrice="~$40–$80/g online",
 legalStatus="PCP analog — effectively illegal in the US; controlled in parts of the EU",
 lastUpdated="2026-09-29", sources=["UNODC", "EMCDDA"]),

dict(slug="3-meo-pce", name="3-MeO-PCE", aliases=["3-Methoxyeticyclidine", "MXE analog"],
 category="dissociatives", schedule="Unscheduled RC; controlled in UK/EU",
 appearance="White powder",
 effects=["MXE-like dissociation, more manic edge", "Euphoria, hole states at high doses"],
 risks=["Mania and compulsive redosing reported more than with ketamine", "Bladder risk with heavy use (arylcyclohexylamine class)", "Delusions of sobriety — accidents follow"],
 overdoseSigns=["Agitation", "Disconnection, unresponsiveness", "High blood pressure"],
 streetPrice="~$30–$70/g online",
 legalStatus="Controlled in the UK and parts of the EU; US analog risk",
 lastUpdated="2026-09-29", sources=["UNODC", "EMCDDA"]),

dict(slug="o-pce", name="O-PCE (2-Oxo-PCE)", aliases=["O-PCE", "Eticyclidone", "MXE successor"],
 category="dissociatives", schedule="Unscheduled RC; controlled in UK/EU",
 appearance="White/off-white powder",
 effects=["The closest RC to banned MXE — dissociation, euphoria, holes"],
 risks=["Drove the post-MXE market and its hospitalizations", "Compulsive redosing and multi-day binges", "Bladder damage with heavy use"],
 overdoseSigns=["Severe dissociation, unresponsive", "Agitation", "Overheating"],
 streetPrice="~$30–$70/g online",
 legalStatus="Controlled in the UK and EU states; US analog risk",
 lastUpdated="2026-09-29", sources=["UNODC", "EMCDDA"]),

dict(slug="tiletamine", name="Tiletamine (Telazol component)", aliases=["Tiletamine", "Telazol (with zolazepam)", "Cat tranquilizer"],
 category="dissociatives", schedule="Schedule III (US, as Telazol)",
 appearance="Veterinary anesthetic (with zolazepam); diverted powder",
 effects=["Ketamine/PCP-like dissociation", "Longer and rougher than ketamine"],
 risks=["Diverted vet supply — purity and dosing unknown", "Zolazepam (a benzo) in the mix adds respiratory risk", "Painful, damaging injections"],
 overdoseSigns=["Deep unresponsiveness", "Slow breathing", "Agitation on recovery"],
 streetPrice="~$40–$100 per diverted vial",
 legalStatus="Schedule III (US); veterinary-controlled worldwide",
 lastUpdated="2026-09-29", sources=["DEA", "UNODC"]),

dict(slug="diphenidine", name="Diphenidine (DPD)", aliases=["Diphenidine", "DPD", "1,2-DEP"],
 category="dissociatives", schedule="Unscheduled; controlled in UK (2016)",
 appearance="White powder sold in capsules",
 effects=["Long, heavy dissociation (6–10 h)", "Numbness, dreamlike states"],
 risks=["Much longer than ketamine — users get stuck immobile for hours", "High-dose delirium and memory blackouts", "Sold as 'legal ketamine' — it is not"],
 overdoseSigns=["Prolonged unresponsiveness", "Agitation, confusion", "High blood pressure"],
 streetPrice="~$30–$60/g online",
 legalStatus="Controlled in the UK; gray zone elsewhere with analog risk",
 lastUpdated="2026-09-29", sources=["EMCDDA", "UNODC"]),

dict(slug="ephenidine", name="Ephenidine", aliases=["Ephenidine", "NEDPA"],
 category="dissociatives", schedule="Unscheduled; controlled in parts of the EU",
 appearance="White powder",
 effects=["Very long dissociation (8–14 h)", "Sedating, dreamlike hole states"],
 risks=["Half-day duration catches users off guard", "NMDA-antagonist organ risk with repeated use", "Confusion and falls"],
 overdoseSigns=["Hours of unresponsiveness", "Agitation", "High blood pressure"],
 streetPrice="~$30–$60/g online",
 legalStatus="Gray zone; controlled in some EU states",
 lastUpdated="2026-09-29", sources=["UNODC", "EMCDDA"]),

dict(slug="deschloroketamine", name="Deschloroketamine (DCK)", aliases=["DCK", "2-Oxo-PCM", "DXE"],
 category="dissociatives", schedule="Unscheduled RC; controlled in UK/EU",
 appearance="White crystals/powder",
 effects=["Ketamine-like dissociation, longer and less visual", "Hole states at high doses"],
 risks=["Filled the ketamine-analog gap after MXE's ban", "Bladder damage likely with heavy use (class effect)", "Depression and cognitive fog after binges"],
 overdoseSigns=["Deep dissociation", "Loss of coordination", "Slow breathing with depressants"],
 streetPrice="~$30–$70/g online",
 legalStatus="Controlled in the UK and EU states; US analog risk",
 lastUpdated="2026-09-29", sources=["UNODC", "EMCDDA"]),

dict(slug="dimenhydrinate", name="Dimenhydrinate (Dramamine) Abuse", aliases=["Dramamine", "Dime", "Gravol (Canada)"],
 category="dissociatives", schedule="OTC",
 appearance="Motion-sickness tablets sold everywhere",
 effects=["At high doses: delirium, realistic hallucinations, confusion", "Heavy, dreamlike detachment"],
 risks=["Deliriant, not a fun trip — terrifying hallucinations and days of confusion", "Seizures and heart-rhythm problems in overdose", "Popular with teens because it is cheap and legal"],
 overdoseSigns=["Delirium, talking to people who are not there", "Hot dry skin, racing heart", "Seizures"],
 streetPrice="~$5–$10 per pack OTC",
 legalStatus="OTC; abuse of it is not illegal but is medically dangerous",
 lastUpdated="2026-09-29", sources=["FDA", "NIDA", "Poison Control data"]),

dict(slug="trihexyphenidyl", name="Trihexyphenidyl (Artane) Abuse", aliases=["Artane", "Trihex", "Benzhexol"],
 category="dissociatives", schedule="Prescription-only",
 appearance="Tablets for Parkinson's disease; diverted in the Middle East, North Africa and prisons",
 effects=["At high doses: euphoric delirium, hallucinations", "Stimulant-like buzz for some users"],
 risks=["Anticholinergic delirium — confusion, dangerous hallucinations", "Heat stroke risk (blocks sweating)", "Dependence reported in prison and refugee settings"],
 overdoseSigns=["Delirium", "Hot dry flushed skin", "Racing heart, urinary retention"],
 streetPrice="~$0.50–$2 per tablet where diverted",
 legalStatus="Prescription-only worldwide",
 lastUpdated="2026-09-29", sources=["WHO", "UNODC", "INCB"]),

dict(slug="pheniramine", name="Pheniramine (Avil) Abuse", aliases=["Avil", "Pheniramine maleate", "Avil injection"],
 category="dissociatives", schedule="OTC/prescription varies (India, South Asia)",
 appearance="Tablets and injectable ampoules; widely diverted and injected in India, Bangladesh and Nepal",
 effects=["At high or injected doses: deliriant 'high', hallucinations", "Sedation at normal doses"],
 risks=["Injecting Avil is a documented epidemic in parts of India — abscesses, gangrene, amputations", "Anticholinergic delirium and seizures", "Often combined with opioids ('speedball' style)"],
 overdoseSigns=["Delirium, hallucinations", "Racing heart", "Seizures"],
 streetPrice="~$0.20–$1 per tablet/ampoule in South Asia",
 legalStatus="OTC or prescription depending on country; injection is prescription-only",
 lastUpdated="2026-09-29", sources=["WHO", "UNODC", "Indian Journal of Psychiatry"]),
]

DRUGS_EXPANSION += [
# ---------------- PSYCHEDELICS (new) ----------------
dict(slug="5-meo-dipt", name="5-MeO-DiPT (Foxy / Foxy Methoxy)", aliases=["Foxy", "Foxy Methoxy", "5-MeO-DiPT"],
 category="psychedelics", schedule="Schedule I (US, 2003)",
 appearance="White powder or capsules; early-2000s club drug that still resurfaces",
 effects=["Tactile, body-heavy psychedelic high", "Euphoria, music enhancement", "Less visual than LSD"],
 risks=["Nausea and vomiting are common", "High doses cause agitation and hallucinatory confusion", "Club setting + overheating risk"],
 overdoseSigns=["Severe agitation", "Vomiting, diarrhea", "Racing heart, high blood pressure"],
 streetPrice="~$30–$60/g equivalent; rare now",
 legalStatus="Schedule I (US); controlled in EU/UK/Canada/Australia",
 lastUpdated="2026-09-29", sources=["DEA", "EMCDDA"]),

dict(slug="4-ho-mipt", name="4-HO-MiPT (Miprocin)", aliases=["Miprocin", "4-HO-MiPT"],
 category="psychedelics", schedule="Unscheduled RC; psilocin analog risk (US)",
 appearance="White/off-white powder or capsules",
 effects=["Mushroom-like trip — visuals, euphoria, head-space", "4–6 hour duration"],
 risks=["Potency similar to psilocin — capsule dosing errors happen", "Anxiety and confusion at high doses", "Unstudied long-term profile"],
 overdoseSigns=["Panic, overwhelming hallucinations", "Nausea", "Rapid heartbeat"],
 streetPrice="~$40–$80/g online",
 legalStatus="Gray zone; prosecutable as a psilocin analog in the US",
 lastUpdated="2026-09-29", sources=["UNODC", "EMCDDA"]),

dict(slug="bufo-venom", name="Bufo / Toad Venom (5-MeO-DMT)", aliases=["Bufo", "Toad", "Bufo alvarius venom", "The God Molecule"],
 category="psychedelics", schedule="5-MeO-DMT is Schedule I (US); toad secretion unscheduled but contains it",
 appearance="Dried secretion of the Sonoran Desert toad, smoked in a pipe; celebrity-retreat trend",
 effects=["Overwhelming 15–30 minute ego-dissolution experience", "Whiteout visuals, total immersion"],
 risks=["Among the most intense psychedelics known — panic and trauma reactions without support", "Retreat deaths linked to unsafe facilitation, not the drug alone", "Toad populations are being poached to collapse — synthetic 5-MeO-DMT is the ethical route"],
 overdoseSigns=["Total unresponsiveness during the peak", "Vomiting while unconscious (aspiration risk)", "Panic on re-entry"],
 streetPrice="~$150–$400 per retreat ceremony; venom ~$100–$250/g illicitly",
 legalStatus="5-MeO-DMT is Schedule I (US); possession of venom is prosecuted as possession of the compound",
 lastUpdated="2026-09-29", sources=["DEA", "NIDA", "UNODC"]),

dict(slug="shroom-bars", name="'Mushroom' Gummies & Chocolate Bars (Gas-Station Edibles)", aliases=["Shroom bars", "Magic mushroom gummies", "PolkaDot-style bars", "Amanita gummies"],
 category="psychedelics", schedule="Sold as 'legal' — contents often illegal or undeclared",
 appearance="Branded chocolate bars and gummies sold in smoke shops and online",
 effects=["Marketed as psilocybin — most contain 4-AcO-DMT, muscimol, or unknown synthetics"],
 risks=["Independent tests keep finding undeclared research chemicals and no psilocybin at all", "2024–25 poison-control outbreaks (Diamond Shruumz) hospitalized dozens", "Dose per piece is a guess — kids mistake them for candy"],
 overdoseSigns=["Severe agitation and confusion", "Vomiting, seizures in outbreak cases", "Racing heart"],
 streetPrice="~$20–$50 per bar/pack",
 legalStatus="Psilocybin is Schedule I; products with synthetic analogs face Analogue-Act and FDA action",
 lastUpdated="2026-09-29", sources=["FDA", "CDC", "Poison Control data"]),

dict(slug="2c-e", name="2C-E", aliases=["2C-E", "Europa", "Aquarust"],
 category="psychedelics", schedule="Schedule I (US)",
 appearance="White powder; milligram-dosed capsules",
 effects=["Long, intense psychedelic trip (8–12 h)", "Strong visuals and body load"],
 risks=["Active at ~10 mg — a small weighing error becomes a nightmare trip", "Vomiting and body load are common", "Hospitalizations from eyeball-dosed 'bumps'"],
 overdoseSigns=["Terrifying hallucinations, panic", "Vomiting", "High blood pressure, agitation"],
 streetPrice="~$50–$100/g online equivalent",
 legalStatus="Schedule I (US); controlled in EU/UK/Canada/Australia",
 lastUpdated="2026-09-29", sources=["DEA", "EMCDDA"]),

dict(slug="2c-i", name="2C-I", aliases=["2C-I", "Infinity"],
 category="psychedelics", schedule="Schedule I (US)",
 appearance="White powder, pills, or blotter",
 effects=["Visual, energetic psychedelic trip (6–10 h)", "Euphoria, enhanced senses"],
 risks=["Frequently mis-sold as or laced into 'ecstasy'", "Unpredictable potency between batches", "Agitation and confusion at high doses"],
 overdoseSigns=["Severe agitation", "Hallucinatory panic", "High blood pressure"],
 streetPrice="~$50–$100/g equivalent",
 legalStatus="Schedule I (US); controlled in EU/UK/Canada/Australia",
 lastUpdated="2026-09-29", sources=["DEA", "EMCDDA"]),

# ---------------- CANNABINOIDS (new) ----------------
dict(slug="jwh-018", name="JWH-018", aliases=["JWH-018", "1-pentyl-3-(1-naphthoyl)indole", "Original Spice chemical"],
 category="cannabinoids", schedule="Schedule I (US, 2011)",
 appearance="Sprayed onto herbal smoking blends — the original 'Spice' ingredient",
 effects=["THC-like high, often stronger and shorter", "Sedation at high doses"],
 risks=["Full CB1 agonist — unlike THC it can cause seizures and psychosis outright", "Drove the first wave of synthetic-cannabinoid ER visits", "Still detected in prison 'spice' papers"],
 overdoseSigns=["Seizures", "Agitation, psychosis", "Racing heart, vomiting"],
 streetPrice="Included in spice products ~$5–$20/pack",
 legalStatus="Schedule I (US); banned across EU/UK/Canada/Australia",
 lastUpdated="2026-09-29", sources=["DEA", "EMCDDA", "UNODC"]),

dict(slug="ur-144", name="UR-144", aliases=["UR-144", "KM-X1", "Abbott cyclopropyl cannabinoid"],
 category="cannabinoids", schedule="Schedule I (US, 2012)",
 appearance="Sprayed on herbal blends; second-generation spice ingredient",
 effects=["THC-like intoxication", "Shorter, harsher than cannabis"],
 risks=["Replaced JWH-018 after its ban — same ER-visit profile", "Seizures and kidney injury reported", "Unknown dosing per batch"],
 overdoseSigns=["Agitation", "Vomiting", "Seizures, confusion"],
 streetPrice="In spice blends ~$5–$20/pack",
 legalStatus="Schedule I (US); banned in EU/UK/Canada/Australia",
 lastUpdated="2026-09-29", sources=["DEA", "UNODC"]),

dict(slug="am-2201", name="AM-2201", aliases=["AM-2201", "Fluorinated JWH-018"],
 category="cannabinoids", schedule="Schedule I (US, 2012)",
 appearance="Sprayed on herbal smoking blends",
 effects=["Potent synthetic-cannabinoid high"],
 risks=["More potent than JWH-018 — linked to seizures and acute kidney injury clusters", "Panic and psychosis at high doses", "Unpredictable batch strength"],
 overdoseSigns=["Seizures", "Severe agitation", "Chest pain, vomiting"],
 streetPrice="In spice blends ~$5–$20/pack",
 legalStatus="Schedule I (US); banned in EU/UK/Canada/Australia",
 lastUpdated="2026-09-29", sources=["DEA", "UNODC"]),

dict(slug="xlr-11", name="XLR-11 (5F-UR-144)", aliases=["XLR-11", "5F-UR-144"],
 category="cannabinoids", schedule="Schedule I (US, 2013)",
 appearance="Sprayed on herbal blends; notorious 2012–13 'spice' wave ingredient",
 effects=["Synthetic-cannabinoid intoxication"],
 risks=["Linked to a multi-state outbreak of acute kidney injury", "Seizures and psychosis", "Deaths reported in Japan and the US"],
 overdoseSigns=["Kidney pain, reduced urination", "Seizures", "Agitation, vomiting"],
 streetPrice="In spice blends ~$5–$20/pack",
 legalStatus="Schedule I (US); banned in EU/UK/Canada/Australia/Japan",
 lastUpdated="2026-09-29", sources=["DEA", "CDC", "UNODC"]),

dict(slug="5f-adb", name="5F-ADB (5F-MDMB-PINACA)", aliases=["5F-ADB", "5F-MDMB-PINACA"],
 category="cannabinoids", schedule="Schedule I (US, 2017)",
 appearance="Sprayed on plant material or soaked into paper — dominant prison 'spice' chemical",
 effects=["Extremely potent synthetic-cannabinoid high", "Rapid sedation ('spice zombies')"],
 risks=["Linked to dozens of deaths — one of the deadliest spice chemicals", "Active at sub-milligram doses; batch hotspots are common", "Seizures, heart stoppage, psychosis"],
 overdoseSigns=["Collapse, unresponsive", "Seizures", "Slow or irregular heartbeat"],
 streetPrice="~$10–$30 per soaked paper square in prisons",
 legalStatus="Schedule I (US); banned across EU/UK/Canada/Australia",
 lastUpdated="2026-09-29", sources=["DEA", "UNODC", "EMCDDA"]),

dict(slug="amb-fubinaca", name="AMB-FUBINACA", aliases=["AMB-FUBINACA", "FUB-AMB", "Zombie drug (2016 NYC)"],
 category="cannabinoids", schedule="Schedule I (US, 2017)",
 appearance="Sprayed on plant material; caused the 2016 Brooklyn 'zombie' mass overdose",
 effects=["Overwhelming synthetic-cannabinoid sedation"],
 risks=["One batch hospitalized 33 people in a single NYC day", "Profound sedation and slowed breathing", "Still found in prison spice"],
 overdoseSigns=["Zombie-like stupor", "Slow breathing", "Collapse"],
 streetPrice="In spice products ~$5–$20/pack",
 legalStatus="Schedule I (US); banned in EU/UK/Canada/Australia",
 lastUpdated="2026-09-29", sources=["DEA", "CDC", "UNODC"]),

dict(slug="ab-fubinaca", name="AB-FUBINACA", aliases=["AB-FUBINACA", "AB-FUB"],
 category="cannabinoids", schedule="Schedule I (US, 2014)",
 appearance="Sprayed on herbal blends",
 effects=["Potent synthetic-cannabinoid high"],
 risks=["Linked to fatal poisonings in Japan, Europe and the US", "Seizures and cardiac effects", "Rapid tolerance drives heavier use"],
 overdoseSigns=["Seizures", "Collapse", "Agitation, vomiting"],
 streetPrice="In spice blends ~$5–$20/pack",
 legalStatus="Schedule I (US); banned in EU/UK/Canada/Australia",
 lastUpdated="2026-09-29", sources=["DEA", "UNODC"]),

dict(slug="mdmb-4en-pinaca", name="MDMB-4en-PINACA", aliases=["MDMB-4en-PINACA", "4en-PINACA"],
 category="cannabinoids", schedule="Schedule I (US, 2021)",
 appearance="Current-generation spice chemical sprayed on plant material and paper",
 effects=["Extremely potent synthetic-cannabinoid intoxication"],
 risks=["The dominant EU street-spice molecule of the 2020s — mass-poisoning outbreaks", "Active at microgram-level doses", "Withdrawal and dependence now documented"],
 overdoseSigns=["Collapse, unresponsive", "Seizures", "Slow heartbeat, vomiting"],
 streetPrice="~$10–$30 per spice pack or paper square",
 legalStatus="Schedule I (US); banned across the EU/UK",
 lastUpdated="2026-09-29", sources=["EUDA", "UNODC", "DEA"]),

dict(slug="cbg", name="CBG (Cannabigerol)", aliases=["CBG", "Cannabigerol", "Mother cannabinoid"],
 category="cannabinoids", schedule="Hemp-derived; legal under 2018 Farm Bill (US)",
 appearance="Hemp flower, oils and gummies marketed for focus and gut health",
 effects=["Non-intoxicating; mild alert calm for some users"],
 risks=["Generally low-risk but unregulated — label accuracy is poor", "Drug-test results are unpredictable with full-spectrum products", "Interactions with medications possible"],
 overdoseSigns=["Drowsiness at very high doses", "Dry mouth", "Low blood pressure, dizziness"],
 streetPrice="~$20–$60 per product",
 legalStatus="Legal hemp derivative in the US; check local rules elsewhere",
 lastUpdated="2026-09-29", sources=["FDA", "NIDA"]),

# ---------------- TOBACCO / NICOTINE (new) ----------------
dict(slug="gutka", name="Gutka & Paan Masala", aliases=["Gutka", "Gutkha", "Paan masala", "Khaini"],
 category="tobacco", schedule="Legal (India/South Asia); banned in several Indian states",
 appearance="Foil sachets of crushed areca nut, tobacco, slaked lime and flavorings — chewed and held in the cheek",
 effects=["Fast nicotine + arecoline buzz", "Alertness, appetite suppression"],
 risks=["One of the world's biggest oral-cancer drivers — India has the highest mouth-cancer rates", "Teeth and gum destruction", "Hooked young: sachets cost pennies and are sold at school gates"],
 overdoseSigns=["Dizziness, nausea in new users", "Racing heart", "Sweating"],
 streetPrice="~$0.05–$0.30 per sachet",
 legalStatus="Food-safety bans in many Indian states; legal and widespread across South Asia and diaspora shops",
 lastUpdated="2026-09-29", sources=["WHO", "IARC", "IARC Monographs"]),

dict(slug="dokha", name="Dokha", aliases=["Dokha", "Medwakh tobacco", "Arabic pipe tobacco"],
 category="tobacco", schedule="Legal (Gulf states)",
 appearance="Very finely shredded high-nicotine tobacco smoked in a small medwakh pipe — hugely popular in the UAE and Gulf",
 effects=["Intense nicotine head-rush ('buzz')", "Light-headed euphoria lasting minutes"],
 risks=["Far higher nicotine per hit than cigarettes — dependence is fast and heavy", "Smoked unfiltered; tar and CO load is extreme", "Teen use is epidemic in Gulf schools"],
 overdoseSigns=["Dizziness, nausea", "Cold sweats", "Racing heart, tremor"],
 streetPrice="~$5–$20 per bottle of tobacco",
 legalStatus="Legal in the Gulf; restricted import elsewhere",
 lastUpdated="2026-09-29", sources=["WHO", "CDC"]),

dict(slug="iqos-htp", name="Heated Tobacco (IQOS / HEETS)", aliases=["IQOS", "HEETS", "Heat-not-burn", "glo"],
 category="tobacco", schedule="Legal, tobacco-regulated",
 appearance="Cigarette-like sticks heated (not burned) in an electronic device",
 effects=["Cigarette-like nicotine delivery with less smoke smell"],
 risks=["Still tobacco: nicotine dependence plus tobacco-specific toxins, just lower", "Marketed as 'reduced risk' — long-term data is thin", "Gateway pattern in teens who never smoked"],
 overdoseSigns=["Nicotine sickness: nausea, dizziness", "Racing heart", "Headache"],
 streetPrice="~$5–$8 per pack of sticks; device $50–$100",
 legalStatus="Regulated tobacco product; age-restricted",
 lastUpdated="2026-09-29", sources=["FDA", "WHO"]),

# ---------------- DEPRESSANTS / ALCOHOL-ADJACENT (new) ----------------
dict(slug="bootleg-alcohol", name="Bootleg & Methanol-Adulterated Alcohol", aliases=["Bootleg liquor", "Methanol poisoning", "Tainted alcohol", "Moonshine (unsafe)"],
 category="depressants", schedule="Alcohol is legal; adulterated supply is the danger",
 appearance="Cheap unbranded spirits, refill bottles, 'local gin' — common in Iran, Turkey, India, Kenya and tourist resorts",
 effects=["Same as ethanol — until the methanol hits: headache, then blindness, then organ failure"],
 risks=["Methanol mass-poisonings kill hundreds a year — as little as 10 ml can blind, 30 ml can kill", "Symptoms lag 12–24 h, so people keep drinking", "Fomepizole/ethanol antidote must start fast"],
 overdoseSigns=["Blurred or 'snowfield' vision", "Severe stomach pain, vomiting", "Rapid breathing, confusion — emergency, not a hangover"],
 streetPrice="Often half the price of licensed liquor",
 legalStatus="Unlicensed production/sale is illegal almost everywhere",
 lastUpdated="2026-09-29", sources=["WHO", "CDC", "Médecins Sans Frontières"]),

dict(slug="disulfiram", name="Disulfiram (Antabuse)", aliases=["Antabuse", "Disulfiram", "Esperal"],
 category="depressants", schedule="Prescription-only",
 appearance="Tablets taken daily to stay off alcohol",
 effects=["No high — it makes drinking alcohol cause flushing, vomiting and pounding heart within minutes"],
 risks=["The alcohol reaction can be dangerous in heart patients", "Liver toxicity in a small share of users", "Hidden alcohol (sauces, mouthwash) triggers reactions"],
 overdoseSigns=["(With alcohol) violent flushing, vomiting, chest pain", "Confusion", "Low blood pressure"],
 streetPrice="Prescription medication; rarely diverted",
 legalStatus="Prescription-only worldwide",
 lastUpdated="2026-09-29", sources=["FDA", "NIDA", "WHO"]),

dict(slug="mouthwash-abuse", name="Mouthwash & Hand-Sanitizer Drinking", aliases=["Mouthwash drinking", "Sanitizer drinking", "Listerine abuse"],
 category="depressants", schedule="Legal products — dangerous misuse",
 appearance="High-ethanol mouthwash (up to 27%) and gel sanitizers drunk when alcohol is unavailable",
 effects=["Ethanol intoxication — plus everything else in the bottle"],
 risks=["Denaturants, methanol (in some sanitizers) and essential oils poison the liver and gut", "Documented deaths during alcohol bans and in dry communities", "Signals severe alcohol dependence — needs treatment, not judgment"],
 overdoseSigns=["Alcohol-poisoning signs plus chemical burns", "Vomiting, confusion", "Slow breathing"],
 streetPrice="~$3–$8 per bottle",
 legalStatus="Legal to buy; products are denatured specifically to deter drinking",
 lastUpdated="2026-09-29", sources=["CDC", "WHO", "Poison Control data"]),

dict(slug="orphenadrine", name="Orphenadrine (Norflex) Abuse", aliases=["Norflex", "Orphenadrine citrate", "Disipal"],
 category="depressants", schedule="Prescription-only",
 appearance="Muscle-relaxant tablets; diverted in the Middle East and among opioid users",
 effects=["At high doses: euphoric, dreamy delirium", "Muscle relaxation"],
 risks=["Anticholinergic delirium and hallucinations", "Seizures and heart-rhythm problems in overdose", "Abused to boost or stretch opioid effects"],
 overdoseSigns=["Delirium, confusion", "Hot dry skin, racing heart", "Seizures"],
 streetPrice="~$0.50–$2 per tablet where diverted",
 legalStatus="Prescription-only worldwide",
 lastUpdated="2026-09-29", sources=["WHO", "INCB", "UNODC"]),
]

DRUGS_EXPANSION += [
# ---------------- HAZARDOUS / REGIONAL COMBOS (new) ----------------
dict(slug="chroming", name="Chroming (Aerosol Paint Huffing)", aliases=["Chroming", "Paint huffing", "Spray huffing", "Volatile substance misuse"],
 category="hazardous", schedule="Legal products — dangerous misuse",
 appearance="Metallic/chrome spray-paint cans inhaled through a cloth or bag — the term is big in Australia but the practice is global",
 effects=["Seconds-long dizzy euphoria", "Disinhibition, giggling"],
 risks=["Sudden sniffing death syndrome — heart stops with no warning, even the first time", "Toluene damages the brain, kidneys and hearing with repeated use", "Teen deaths keep making headlines in Australia"],
 overdoseSigns=["Collapse mid-use", "Seizures", "Blue lips, irregular heartbeat"],
 streetPrice="~$5–$10 per can",
 legalStatus="Legal to buy; several Australian states restrict spray-paint sales to minors",
 lastUpdated="2026-09-29", sources=["WHO", "Australian Institute of Health and Welfare", "NIDA"]),

dict(slug="phenacetin", name="Phenacetin (Cocaine Cutting Agent)", aliases=["Phenacetin", "Supercut", "Cocaine adulterant"],
 category="hazardous", schedule="Withdrawn pharmaceutical (banned since the 1980s)",
 appearance="White crystalline powder — the most common bulk cut in European and UK cocaine",
 effects=["No desired effect — it just bulks cocaine and adds a numbing illusion of quality"],
 risks=["Carcinogen (IARC Group 1) — banned for causing kidney cancer and failure", "Most cocaine users consume it unknowingly", "Long-term exposure is cumulative"],
 overdoseSigns=["No acute syndrome — harm is chronic (kidney damage, anemia)", "Blood in urine with heavy exposure", "Fatigue"],
 streetPrice="~$500–$2,000/kg to traffickers",
 legalStatus="Withdrawn worldwide; possession for cutting is prosecuted as drug-supply evidence",
 lastUpdated="2026-09-29", sources=["IARC", "EMCDDA", "EUDA"]),

dict(slug="benzo-dope", name="Benzo-Dope (Fentanyl + Benzodiazepine)", aliases=["Benzo dope", "Benzofentanyl", "Down (Canada)"],
 category="hazardous", schedule="Combination of controlled substances",
 appearance="Purple, pink or greenish fentanyl powder containing etizolam or other benzos — the dominant 'down' in parts of Canada",
 effects=["Opioid nod plus benzo blackout — users pass out fast and long"],
 risks=["Naloxone reverses the fentanyl but NOT the benzo — people stay unconscious after Narcan", "Overdose deaths resist standard rescue", "Withdrawal is double: opioid + benzo (seizure risk)"],
 overdoseSigns=["Unresponsive even after naloxone", "Slow breathing", "Blue lips, snoring sounds"],
 streetPrice="~$40–$100/g equivalent in Canadian street supply",
 legalStatus="Both components illegal without prescription",
 lastUpdated="2026-09-29", sources=["Health Canada", "BCCSU", "CDC"]),

dict(slug="kush-drug", name="Kush (West African Synthetic Drug)", aliases=["Kush", "Kush (Sierra Leone)", "K2-kush"],
 category="hazardous", schedule="Illegal; composition varies by batch",
 appearance="Green/brown herbal smoking mix — swept Sierra Leone, Liberia, Guinea and Gambia from 2022",
 effects=["Intense stupefying high; users freeze in unnatural poses ('zombie' videos)"],
 risks=["Lab tests found synthetic cannabinoids, nitazene opioids and even tramadol in different batches — every batch is a lottery", "Mass hospitalizations and deaths; users dying young", "Cheap and everywhere — fastest-growing drug crisis in West Africa"],
 overdoseSigns=["Frozen, unresponsive postures", "Slow breathing", "Collapse, seizures"],
 streetPrice="~$0.20–$1 per joint — priced for the poorest users",
 legalStatus="Illegal across West Africa; Sierra Leone declared a national emergency (2024)",
 lastUpdated="2026-09-29", sources=["UNODC", "BBC/AFP investigations", "Sierra Leone government"]),

dict(slug="nyaope", name="Nyaope / Whoonga (South African Street Heroin)", aliases=["Nyaope", "Whoonga", "Sugars", "Ungah"],
 category="hazardous", schedule="Heroin is illegal; additives vary",
 appearance="Brownish powder — low-grade heroin cut with anything from antiretrovirals to rat poison; smoked with cannabis in South African townships",
 effects=["Heroin-like sedation and escape", "Short duration — frequent dosing"],
 risks=["Additives are unknown batch to batch — poisonings are routine", "Smoked off foil with cannabis ('Bluetooth' myths aside, HIV/TB spread through shared pipes and survival sex)", "Violent withdrawal within hours"],
 overdoseSigns=["Slow breathing", "Pinpoint pupils", "Unresponsive"],
 streetPrice="~$1–$3 per 'cap' (straw)",
 legalStatus="Illegal; heroin is a Schedule-defining narcotic in South Africa",
 lastUpdated="2026-09-29", sources=["UNODC", "South African Medical Research Council"]),

dict(slug="paco-basuco", name="Paco / Basuco (Cocaine Paste)", aliases=["Paco", "Basuco", "PBC (pasta base)", "Oxi"],
 category="hazardous", schedule="Illegal — cocaine product",
 appearance="Dirty off-white/yellow smokable chunks — crude intermediate from cocaine production, kerosene and solvent residues included",
 effects=["Crack-like instant high, even shorter (minutes)", "Savage compulsion to redose"],
 risks=["Residual solvents (kerosene, sulfuric acid) burn lungs and brain on top of the cocaine", "Devastated poor neighborhoods in Argentina, Uruguay, Brazil and Colombia", "Psychosis and violence come fast and cheap"],
 overdoseSigns=["Seizures", "Chest pain, collapse", "Extreme paranoia, aggression"],
 streetPrice="~$0.50–$2 per rock — deliberately priced below crack",
 legalStatus="Illegal across Latin America",
 lastUpdated="2026-09-29", sources=["UNODC", "OAS/CICAD"]),

dict(slug="speedball", name="Speedball (Heroin + Cocaine)", aliases=["Speedball", "Snowball", "Powerballing"],
 category="hazardous", schedule="Combination of illegal drugs",
 appearance="Heroin and cocaine injected or snorted together (or back-to-back)",
 effects=["Cocaine rush followed by heroin's landing — users chase the overlap"],
 risks=["The classic celebrity-killer combo (Belushi, Farley, Hoffman): cocaine wears off first, leaving full opioid dose unopposed", "Today usually means fentanyl + cocaine — deadlier than ever", "Heart and lungs get opposing orders simultaneously"],
 overdoseSigns=["Slow breathing after initial agitation", "Blue lips", "Collapse"],
 streetPrice="Cost of both drugs combined",
 legalStatus="Both components illegal",
 lastUpdated="2026-09-29", sources=["NIDA", "CDC", "DEA"]),

dict(slug="goofball", name="Goofball (Meth + Heroin/Fentanyl)", aliases=["Goofball", "Meth-fent mix", "Speedball 2.0"],
 category="hazardous", schedule="Combination of illegal drugs",
 appearance="Methamphetamine and heroin/fentanyl used together — increasingly one powder sold pre-mixed",
 effects=["Meth's drive plus opioid's nod — users feel 'balanced'"],
 risks=["Now the most common polysubstance pattern in US overdose deaths", "Meth masks fentanyl sedation until breathing stops", "No naloxone effect on the meth side — stimulation continues after rescue"],
 overdoseSigns=["Slow breathing with agitation before collapse", "Blue lips", "Seizures possible"],
 streetPrice="~$40–$80/g for pre-mixed product",
 legalStatus="Both components illegal",
 lastUpdated="2026-09-29", sources=["CDC", "NIDA", "DEA"]),

dict(slug="bath-salts", name="'Bath Salts' (Synthetic Cathinone Umbrella)", aliases=["Bath salts", "Plant food", "Jewelry cleaner", "Ivory Wave"],
 category="hazardous", schedule="Most core chemicals are Schedule I (US) and banned in EU/UK",
 appearance="White/brown powders sold as 'bath salts', 'plant food' or 'research chemicals' — contents are synthetic cathinones (MDPV, mephedrone, PVP-family)",
 effects=["Meth/cocaine-like stimulation, euphoria", "Long duration, brutal comedown"],
 risks=["The label is a lie — contents change batch to batch", "Excited delirium: superhuman agitation, overheating, police encounters", "Psychosis can outlast the drug by days"],
 overdoseSigns=["Extreme agitation, superhuman strength", "Overheating, profuse sweating", "Paranoia, hallucinations"],
 streetPrice="~$20–$50/g",
 legalStatus="Core cathinones banned in the US, UK and EU; analog laws cover the rest",
 lastUpdated="2026-09-29", sources=["DEA", "NIDA", "EMCDDA"]),

dict(slug="paracetamol", name="Paracetamol / Acetaminophen Overdose", aliases=["Paracetamol", "Acetaminophen", "Tylenol", "Panadol", "APAP"],
 category="hazardous", schedule="OTC — the danger is the dose",
 appearance="The world's most common painkiller — in everything from Tylenol to cold remedies to Percocet",
 effects=["Pain and fever relief at normal doses; no high"],
 risks=["Leading cause of acute liver failure in the US, UK and Australia — the lethal dose is only ~2–3× the max daily dose", "Hidden in combination products — people double-dose without knowing", "Staggered overdoses (a few extra tablets for days) are just as deadly"],
 overdoseSigns=["Often NOTHING for 24–48 h, then: nausea, right-side abdominal pain", "Yellowing skin/eyes (jaundice)", "Confusion — by then the liver is failing; NAC antidote works only if given early"],
 streetPrice="~$3–$8 per pack",
 legalStatus="OTC; pack sizes restricted in the UK to limit impulsive overdose",
 lastUpdated="2026-09-29", sources=["FDA", "NHS", "WHO"]),

dict(slug="ether-abuse", name="Diethyl Ether Drinking & Huffing", aliases=["Ether", "Ethyl ether", "Ether drinking (Eastern Europe)"],
 category="hazardous", schedule="Legal solvent — restricted as a drug precursor",
 appearance="Highly volatile solvent; drunk or inhaled in parts of Eastern/Central Europe ('eter' drinking culture)",
 effects=["Fast drunk-like intoxication", "Brief euphoria, then heavy sedation"],
 risks=["Explosively flammable — burns and fires during use", "Severe stomach damage when drunk", "Repeated use causes brain and liver damage"],
 overdoseSigns=["Unconsciousness", "Slow breathing", "Vomiting while sedated"],
 streetPrice="~$5–$15 per bottle where sold",
 legalStatus="Legal solvent but precursor-controlled (UN Table I); sale for consumption is illegal",
 lastUpdated="2026-09-29", sources=["WHO", "INCB", "EMCDDA"]),

# ---------------- SEXUAL HEALTH (new) ----------------
dict(slug="rhino-pills", name="Gas-Station Sex Pills ('Rhino' & Knockoffs)", aliases=["Rhino pills", "Black Mamba", "Gas station boner pills", "Honey packs"],
 category="sexual-health", schedule="Sold as 'supplements' — FDA warns they are adulterated drugs",
 appearance="Single-serve capsules and honey packets at gas stations, smoke shops and online",
 effects=["Erections — because they secretly contain sildenafil/tadalafil analogs at random doses"],
 risks=["FDA has issued hundreds of warnings: hidden drug doses can crash blood pressure, especially with nitrates or heart meds", "Analogs are untested — some cause days-long painful erections (priapism = emergency)", "No quality control; doses vary pill to pill in the same pack"],
 overdoseSigns=["Pounding headache, flushing", "Dangerous blood-pressure drop (with nitrates)", "Erection lasting 4+ hours — go to ER"],
 streetPrice="~$5–$15 per pill/pack",
 legalStatus="Illegal to sell as supplements (undeclared drugs); FDA seizes shipments regularly",
 lastUpdated="2026-09-29", sources=["FDA", "NIDA"]),

# ---------------- WEIGHT LOSS (new) ----------------
dict(slug="dnp", name="DNP (2,4-Dinitrophenol)", aliases=["DNP", "Dinitrophenol", "Dinosan"],
 category="weight-loss", schedule="Banned for human use everywhere; sold online as 'fat burner'",
 appearance="Yellow powder or capsules sold on bodybuilding forums",
 effects=["Literally uncouples cellular energy — fat burns off as pure heat"],
 risks=["The deadliest 'diet pill' in circulation: no antidote, cooking-from-inside hyperthermia kills", "Narrow margin — a few extra capsules can be fatal; deaths every year in the UK/US", "Cataracts and nerve damage with repeated use"],
 overdoseSigns=["Profuse sweating, feeling unbearably hot", "Racing heart, rapid breathing", "Confusion — call emergency; cooling and ICU support only"],
 streetPrice="~$30–$80 per 100 capsules online",
 legalStatus="Illegal to sell for human consumption in the US, UK, EU and Australia",
 lastUpdated="2026-09-29", sources=["FDA", "NHS", "WHO", "UK FSA"]),

dict(slug="synephrine", name="Synephrine (Bitter Orange)", aliases=["Bitter orange", "p-Synephrine", "Citrus aurantium"],
 category="weight-loss", schedule="Legal supplement; banned by WADA-adjacent lists in sport",
 appearance="Fat-burner and pre-workout ingredient, often stacked with caffeine",
 effects=["Mild ephedra-like stimulation", "Appetite suppression"],
 risks=["Replaced ephedra after its ban — heart-attack and stroke case reports followed", "Stacked with caffeine the blood-pressure spike multiplies", "Dose on the label is often wrong"],
 overdoseSigns=["Chest pain, pounding heart", "Headache, high blood pressure", "Anxiety, tremor"],
 streetPrice="~$15–$40 per bottle",
 legalStatus="Legal supplement; prohibited in tested sport",
 lastUpdated="2026-09-29", sources=["FDA", "NCCIH", "WADA"]),

dict(slug="5-amino-1mq", name="5-Amino-1MQ", aliases=["5-Amino-1MQ", "NNMT inhibitor", "5A1MQ"],
 category="weight-loss", schedule="Unscheduled research compound — not approved anywhere",
 appearance="Capsules and injectables sold by peptide vendors for 'metabolic enhancement'",
 effects=["Blocks the NNMT enzyme — marketed for fat loss and endurance; human evidence is essentially zero"],
 risks=["No approved human trials — dosing is guesswork from rodent studies", "Sold injectable: infection and sterility risks", "Long-term effects completely unknown"],
 overdoseSigns=["Unknown — no human overdose data", "Injection-site reactions", "Reported: headache, nausea"],
 streetPrice="~$40–$100 per vial/bottle",
 legalStatus="Research chemical — not for human use; selling it as a supplement is illegal in the US",
 lastUpdated="2026-09-29", sources=["FDA", "PubMed (preclinical literature)"]),

# ---------------- PERFORMANCE / DOPING (new) ----------------
dict(slug="epo-doping", name="EPO (Erythropoietin) Doping", aliases=["EPO", "Eprex", "Procrit", "Blood booster"],
 category="performance", schedule="Prescription-only; banned in sport",
 appearance="Injectable anemia drug abused by endurance athletes",
 effects=["More red blood cells = more oxygen = superhuman endurance"],
 risks=["Thick blood clots: strokes, heart attacks and pulmonary embolisms — the 1990s cycling deaths", "Blood pressure spikes", "Immune reactions (pure red-cell aplasia) with some formulations"],
 overdoseSigns=["Severe headache, high blood pressure", "Chest pain", "Signs of stroke or clot"],
 streetPrice="~$100–$500 per course diverted",
 legalStatus="Prescription-only; WADA-prohibited",
 lastUpdated="2026-09-29", sources=["WADA", "FDA", "UCI historical inquiries"]),

dict(slug="meldonium", name="Meldonium (Mildronate)", aliases=["Mildronate", "Meldonium", "Sharapova drug"],
 category="performance", schedule="Prescription-only (Eastern Europe); banned in sport since 2016",
 appearance="Capsules and injection; popular in Russia/Eastern Europe as a 'heart vitamin'",
 effects=["Shifts energy metabolism — marketed for endurance and recovery"],
 risks=["The Sharapova ban made it famous — hundreds of athletes tested positive after 2016", "Genuine cardiac patients need it; healthy users get unknown long-term effects", "Gray-market supply is counterfeited heavily"],
 overdoseSigns=["Low blood pressure", "Racing heart", "Headache, dizziness"],
 streetPrice="~$20–$50 per pack online",
 legalStatus="Prescription-only in Eastern Europe; not approved in the US; WADA-prohibited",
 lastUpdated="2026-09-29", sources=["WADA", "EMA"]),

dict(slug="diuretics-abuse", name="Diuretic Abuse (Weight-Cut & Eating-Disorder)", aliases=["Water pills", "Furosemide", "Lasix", "Hydrochlorothiazide"],
 category="performance", schedule="Prescription-only; banned in sport (masking agents)",
 appearance="Tablets abused for rapid 'weight loss', boxing/MMA weight cuts, and to mask doping",
 effects=["Rapid water loss — several kg on the scale in a day"],
 risks=["Dehydration collapses kidneys and stops hearts — multiple combat-sports deaths from weight cuts", "Potassium crash causes fatal arrhythmias", "Eating-disorder misuse hides as 'debloating'"],
 overdoseSigns=["Dizziness, fainting", "Muscle cramps, weakness", "Irregular heartbeat — emergency"],
 streetPrice="~$0.10–$1 per tablet diverted",
 legalStatus="Prescription-only; WADA-prohibited as masking agents",
 lastUpdated="2026-09-29", sources=["WADA", "FDA", "NHS"]),
]
