# Methamphetamine city rankings by region — sourced, hedged, citable.
# Method note carried on every page: no country measures meth use per city directly.
# Rankings combine the best available proxies per region (wastewater analysis,
# forensic-lab reporting, treatment admissions, police seizures). They are
# directional, not precise league tables.

METH_CITY_PAGES = [
 dict(slug="meth-cities-usa", region="United States", title="Top 10 US cities with the most methamphetamine use",
  updated="September 2026", read="8 min",
  desc="The US cities where methamphetamine use is highest, ranked from DEA NFLIS metro reporting, SAMHSA treatment admissions and HIDTA threat assessments — with plain-English context per city.",
  stats=[("323,404","meth reports to US forensic labs (NFLIS 2025) — the #1 reported substance"),("#1","meth has been the most-reported drug in NFLIS since 2019"),("~50%","share of US meth now produced in Mexican 'super labs' (DEA NDTA)")],
  intro="No US agency publishes a clean per-city meth use ranking — the closest thing is a triangulation of three proxies: DEA forensic-laboratory report counts by metropolitan area, SAMHSA treatment-admission data, and High-Intensity Drug Trafficking Area (HIDTA) threat assessments. Combined, they point at the same map: meth use in America is concentrated in the West and Southwest, with serious pockets in the Midwest and Upper South. The ranking below is directional, not a precise league table — treat positions 3–7 as a band, not an order.",
  cities=[
   ("1","Phoenix, AZ","Maricopa County sits on the I-10/I-8 corridor straight up from the border; Arizona HIDTA reports consistently rank it among the top meth distribution hubs, with cheap 'Mexican ice' saturating the market."),
   ("2","San Diego, CA","The original US meth capital — the market that birthed 'ice' in the 1980s. San Diego HIDTA still reports among the highest per-capita meth indicators on the West Coast, fed directly by cross-border supply."),
   ("3","San Francisco / Oakland, CA","Bay Area treatment admissions for meth have surged past heroin and cocaine combined in recent years; the Tenderloin and East Bay markets are dominated by cheap, high-purity crystal."),
   ("4","Los Angeles, CA","The largest meth distribution node in the country by volume — LA is less a consumption hotspot than the warehouse where the rest of America's supply is staged."),
   ("5","Portland, OR","Oregon's meth treatment-admission rate has led the nation in SAMHSA data; Portland's open-air market and cheap supply make it a consistent top-five indicator city."),
   ("6","Seattle / Tacoma, WA","The I-5 corridor terminus. DEA Seattle Field Division reporting shows meth as the region's dominant drug threat, outstripping opioids in treatment and police data."),
   ("7","Denver, CO","Rocky Mountain HIDTA reports meth as the primary threat across Colorado; Denver's central location makes it a redistribution point for the mountain states."),
   ("8","Minneapolis / St. Paul, MN","The Upper Midwest's meth hub — the 'Minnesota pipeline' brings Mexican meth north, and Twin Cities treatment admissions reflect it."),
   ("9","St. Louis, MO","Mid-America HIDTA reporting places St. Louis among the top Midwestern meth markets, with supply arriving on I-44 and I-70 from the Southwest."),
   ("10","Nashville, TN","Appalachia HIDTA data shows meth displacing prescription opioids across Tennessee; Nashville's interstate crossroads (I-40/I-24/I-65) make it the region's distribution center."),
  ],
  notes="Honorable mentions by indicator: Atlanta and Houston (huge distribution volumes, lower per-capita use), Las Vegas, Kansas City and Indianapolis. New England and the mid-Atlantic remain the least meth-affected regions — fentanyl dominates there instead.",
  method="Methodology: composite of DEA NFLIS-Drug forensic report counts by metro area (2024–25), SAMHSA TEDS treatment admissions for primary methamphetamine use, and published HIDTA threat assessments. Rankings are directional.",
  sources=["DEA NFLIS-Drug 2025 annual report","DEA 2025 National Drug Threat Assessment","SAMHSA TEDS treatment admissions","Arizona / San Diego / Oregon / Rocky Mountain / Mid-America HIDTA threat assessments"]),

 dict(slug="meth-cities-canada", region="Canada", title="Top 10 Canadian cities with the most methamphetamine use",
  updated="September 2026", read="7 min",
  desc="Where meth hits hardest in Canada — prairie cities dominate, per wastewater data, RCMP/ALERT seizures and provincial treatment reports.",
  stats=[("279 kg","meth seized by CBSA in Alberta alone in 2025"),("Prairies","Canada's meth heartland — Winnipeg, Edmonton, Calgary, Saskatoon, Regina"),("10x","rise in Canadian meth seizures over the past decade (CBSA/RCMP)")],
  intro="Canada's meth geography is different from America's: the epicenter is not the West Coast but the Prairie provinces. Wastewater monitoring (Canadian cities participate in the international SCORE study), provincial treatment data and police seizure reports all point the same way — Manitoba, Saskatchewan and Alberta carry the heaviest per-capita meth load, with British Columbia and Ontario as secondary markets fed through prairie distribution networks.",
  cities=[
   ("1","Winnipeg, MB","Consistently Canada's meth capital across every proxy: among the highest meth loads in Canadian wastewater data, the highest per-capita police seizure rates, and a treatment system where meth is the leading stimulant referral. Winnipeg is also named as a source node in interprovincial trafficking cases (a 2025 ALERT case traced a 20 kg shipment from Winnipeg to Edmonton)."),
   ("2","Edmonton, AB","Alberta's northern hub; RCMP and ALERT report Edmonton as a primary meth distribution center, and the city records some of the province's highest overdose and seizure figures. CBSA seized 279 kg of meth in Alberta in 2025 — most destined for the Edmonton–Calgary corridor."),
   ("3","Calgary, AB","Close behind Edmonton on every indicator; the two cities function as one market split by 300 km of highway."),
   ("4","Vancouver, BC","Lower Mainland meth is tied to organized crime groups and the port; Vancouver participates in SCORE wastewater monitoring and shows significant meth loads, though fentanyl dominates its overdose statistics."),
   ("5","Saskatoon, SK","Saskatchewan's largest city and its meth distribution hub; provincial data shows meth-involved offences and seizures far above the national rate."),
   ("6","Regina, SK","Matches Saskatoon on per-capita indicators; the two prairie cities trade the provincial top spot year to year."),
   ("7","Toronto, ON","Canada's largest city by consumption volume, though lower per capita than the prairies; meth is the fastest-growing stimulant in Ontario treatment data."),
   ("8","Windsor, ON / London, ON","Southern Ontario corridor cities absorbing mid-west US supply across the Detroit border."),
   ("9","Halifax, NS","Atlantic Canada's meth entry point, fed by port traffic and highway corridors from Montreal."),
   ("10","Montreal, QC","Quebec's meth market is smaller but growing — SQ reporting shows rising seizures, often linked to Hells Angels distribution networks."),
  ],
  notes="Territorial note: Whitehorse, Yellowknife and Iqaluit report low absolute numbers but among the highest per-capita meth-related harm in Canadian surveillance, driven by limited treatment access.",
  method="Methodology: composite of Statistics Canada police-reported drug offences by CMA, CBSA and RCMP/ALERT seizure reporting (2024–26), provincial treatment admissions, and SCORE wastewater data where Canadian cities participate. Rankings are directional.",
  sources=["Statistics Canada police-reported crime statistics","CBSA seizure reporting 2025–26","ALERT / RCMP releases","SCORE wastewater study (EUDA)","Provincial treatment admissions (MB, AB, SK, BC)"]),

 dict(slug="meth-cities-europe", region="Europe", title="Top 10 European cities with the most methamphetamine use",
  updated="September 2026", read="7 min",
  desc="Europe's meth map is a Czech story — with Slovak, German and Baltic spillover. Ranked from the SCORE/EUDA wastewater study covering 115–130 cities.",
  stats=[("130","European cities monitored in the 2025 SCORE wastewater study"),("Top 5","Czech cities occupy the first five meth positions in Europe"),("+46%","of 80 monitored cities saw meth loads rise 2024–25")],
  intro="Europe actually has the best city-level meth data in the world: the SCORE group's annual wastewater study, published with the European Union Drugs Agency, measures methamphetamine metabolites in the sewage of 115–130 cities across 28 countries. The 2025 results are unambiguous: Europe's meth use is concentrated in Czechia, with Slovakia, eastern Germany, the Baltics, Norway and parts of Spain and Türkiye forming a second tier. Unlike cocaine or MDMA, meth loads are flat through the week — a signature of dependent, daily use rather than party use.",
  cities=[
   ("1","České Budějovice, CZ","Took the #1 spot in the 2025 SCORE ranking after a ~29% year-on-year jump, displacing Ústí nad Labem. Czechia's homegrown meth tradition — 'pervitin' — dates to the pre-1989 era, and small domestic labs still feed the market alongside industrial-scale imports."),
   ("2","Ústí nad Labem, CZ","The 2024 #1 and perennial top-two; the highest historical meth loads ever recorded in the study come from Czech industrial cities near the German border."),
   ("3","Prague, CZ","The capital rounds out the all-Czech top tier; all measured substances increased in Prague in the latest round."),
   ("4","Plzeň / Ostrava, CZ","Czech cities occupy positions 4–5 across the study, giving Czechia the strongest per-capita meth market in Europe by an order of magnitude."),
   ("5","Bratislava, SK","Slovakia's capital; high meth loads reflecting the shared Czech-Slovak 'pervitin' market, plus sharply rising amphetamine ('speed') use."),
   ("6","Chemnitz / Erfurt, DE","Eastern German cities showing Czech-style meth loads — attributed by Czech researchers to cross-border export of meth from Czechia."),
   ("7","Oslo, NO","The Nordic outlier: historically the highest meth loads outside Czechia/Slovakia, with pronounced year-to-year fluctuation reflecting supply waves."),
   ("8","Vilnius, LT","The Baltic signal: measurable meth loads in a region otherwise dominated by amphetamine and fentanyl analogues."),
   ("9","Madrid / eastern Spain, ES","Spanish cities register the western edge of Europe's meth belt, alongside detections in the Netherlands and Belgium."),
   ("10","Istanbul, TR","Türkiye's meth loads have risen sharply — analysts link it to Afghan-produced meth moving west along the heroin routes through Iran."),
  ],
  notes="Sixteen monitored European cities reported no meth detection at all in 2025 — the drug remains remarkably regional. EUDA's own comparison: city-level meth loads in Australia, Canada and the United States exceed every European city.",
  method="Methodology: SCORE/EUDA wastewater analysis (sampling March–May 2025, published March 2026) — daily methamphetamine mass loads per 1,000 population, supplemented by EUDA trend reporting. This is the only region where the ranking is directly measured rather than triangulated.",
  sources=["SCORE group / EUDA wastewater multi-city study 2025 (published March 2026)","EUDA EU Early Warning System","Urban Journalism Network analysis of SCORE data"]),

 dict(slug="meth-cities-australia", region="Australia", title="Top 10 Australian cities with the most methamphetamine use",
  updated="September 2026", read="7 min",
  desc="Australia records the highest city-level meth loads in the world — and the worst of it is in regional areas, not the capitals. Ranked from ACIC wastewater data.",
  stats=[("12.8 t","national meth consumption Aug 2023–24 — the highest ever recorded (ACIC)"),("A$8.9 bn","estimated annual street value of Australia's meth market"),("+21%","rise in national meth consumption 2023–24")],
  intro="Australia's National Wastewater Drug Monitoring Program, run by the Australian Criminal Intelligence Commission, is one of the most rigorous drug-surveillance systems anywhere — 61 treatment plants covering 57% of the population. Its headline finding turns the usual assumption upside down: in Australia, meth use is higher in regional areas than in capital cities. 'Ice' is Australia's most destructive illicit drug by spending, and regional mining towns, ports and agricultural centers — not Sydney or Melbourne — carry the heaviest per-capita loads.",
  cities=[
   ("1","Perth, WA","Western Australia records the highest meth loads of any Australian region; Perth's market is fed by direct maritime import from Asia, and WA consistently tops ACIC's per-capital-city meth ranking."),
   ("2","Darwin, NT","Small population, extreme per-capita loads — Darwin repeatedly posts among the highest meth consumption figures per person in the national program."),
   ("3","Regional WA (Kalgoorlie, Geraldton, Bunbury)","The mining-and-ports belt records the heaviest regional meth loads in the country; fly-in-fly-out work patterns and port access drive supply."),
   ("4","Adelaide, SA","SA Health and ACIC data place Adelaide among the highest capital-city meth markets, with strong links to Victorian supply networks."),
   ("5","Brisbane / Gold Coast, QLD","Queensland's southeast corridor — high absolute consumption and a documented role as an import and redistribution gateway."),
   ("6","Sydney, NSW","Largest absolute market; per-capita figures are lower than Perth or Darwin but the total tonnage flowing through the city is the country's biggest."),
   ("7","Melbourne, VIC","Second-largest absolute market; Victoria's wastewater shows high and stable meth loads with regional hotspots (Shepparton, Mildura)."),
   ("8","Regional Victoria (Shepparton, Mildura) / Regional NSW (Dubbo, Wagga Wagga)","Country cities consistently out-consume their capitals per person; ice is the defining drug of regional Australia."),
   ("9","Hobart, TAS","Tasmania's isolation keeps loads moderate but the state's regional towns post disproportionate figures relative to population."),
   ("10","Canberra, ACT","The national capital records the lowest meth loads of any Australian jurisdiction — though ACIC notes use rose here too in the latest round."),
  ],
  notes="The single most important fact in Australian meth data: regional Australia uses more meth per person than the capitals — the reverse of the cocaine pattern, which is city-dominated. National meth consumption hit a record 12.8 tonnes in the 2023–24 monitoring year.",
  method="Methodology: ACIC National Wastewater Drug Monitoring Program (2023–24 reporting year, 61 sites covering 57% of population) — methamphetamine mass loads by site, combined with state health data. Rankings combine per-capita loads with absolute market size.",
  sources=["ACIC National Wastewater Drug Monitoring Program (2023–24, reported August 2025)","ABC News / ADF analysis of ACIC data","UNODC World Drug Report"]),

 dict(slug="meth-cities-middle-east", region="Middle East", title="Meth in the Middle East: the cities where it concentrates",
  updated="September 2026", read="7 min",
  desc="The Middle East runs on Captagon — but methamphetamine is the region's other stimulant epidemic, centered on Iran and Israel with Afghan supply flooding east.",
  stats=[("959","meth labs dismantled in Iran in a single 3-year period (2010–13) — historically the region's epicenter"),("77.5%","meth use prevalence among people who inject drugs in eastern Iran vs 14.1% in the west (2020 study)"),("Top-2","Iran and Israel are the region's two established meth consumer markets")],
  intro="Any honest Middle East meth ranking starts with a caveat: this is a Captagon region. The Levant's stimulant of choice is the amphetamine pill made in Syria, and most countries here publish almost no city-level drug data at all. But methamphetamine — not Captagon — has carved out two real consumer markets: Iran, the region's historic meth producer, and Israel, where meth (locally 'metz') became the dominant hard drug of the 2010s. Around them, Afghan meth production is now flooding east into Iran, Türkiye and the Gulf.",
  cities=[
   ("1","Tehran, Iran","The region's meth capital by every historical measure: the largest consumer base, thousands of dismantled labs, and a well-documented rise in regular use and meth-associated psychosis. Iranian national survey data put past-year meth use at roughly 0.7% of adults — hundreds of thousands of users, concentrated in the capital."),
   ("2","Mashhad / eastern Iran","Eastern provinces bear the Afghan wave: 77.5% of people who inject drugs in eastern Iran test positive for meth, versus 14.1% in the west — a direct consequence of Afghan meth moving across the border."),
   ("3","Tel Aviv / central Israel, IL","Israel's largest meth market; Israeli police reporting has repeatedly identified meth as the country's most consumed hard drug, with a supply chain stretching to Mexico and Europe."),
   ("4","Beersheba / southern Israel, IL","Israel's second-tier meth hub, serving the Negev and the country's largest periphery city."),
   ("5","Istanbul, Türkiye","Türkiye is a transit-and-emerging-consumer country: SCORE wastewater already detects rising meth loads in Istanbul, fed by the same Afghan pipeline that serves eastern Iran."),
   ("6","Dubai / UAE, AE","The Gulf's entry point: repeated record meth seizures at UAE ports and airports indicate a real — if hidden — consumer market among the region's largest expatriate population."),
   ("7","Riyadh / Jeddah, SA","Saudi Arabia reports large ATS seizures annually; harsh enforcement means prevalence data is close to nonexistent, but seizure volumes point to Jeddah's port and Riyadh's market."),
   ("8","Amman, JO","Jordan sits between the Captagon belt and the Gulf; meth detections are rising in national reporting alongside the Captagon flood."),
  ],
  notes="Data honesty: outside Iran and Israel, no Middle Eastern country publishes city-level prevalence. Rankings 3–8 are inferred from seizure geography, wastewater signals and treatment reporting, and are more uncertain than any other region on this site.",
  method="Methodology: triangulation of UNODC and WHO-EMRO reporting, Iranian national and regional studies (including PWID cohort data), Israeli Anti-Drug Authority / police statistics, and SCORE wastewater signals where available. High uncertainty outside Iran and Israel.",
  sources=["WHO-EMRO: ATS use in Iran 2004–2015 review","Iran national mental health survey (meth prevalence data)","Meth use among PWID in Iran, 2020 (PMC)","UNODC World Drug Report — Middle East ATS seizures","EUDA SCORE wastewater study (Istanbul)"]),

 dict(slug="meth-cities-africa", region="Africa", title="Meth in Africa: the cities where 'tik' rules",
  updated="September 2026", read="7 min",
  desc="Africa's meth story is a South African story — Cape Town's 'tik' epidemic, with Nigeria, Mozambique and Kenya rising behind it.",
  stats=[("21.4%","of South African treatment admissions are for meth — the #2 substance nationally (Central Drug Authority 2022)"),("26","African countries reported meth seizures 2011–21 — nearly triple the previous decade (UNODC)"),("MOZ + SA","the largest aggregate meth seizures in Africa over the past decade")],
  intro="Methamphetamine arrived in Africa through one city: Cape Town, where locally made 'tik' went from unknown in 2003 to the city's main drug of abuse within five years. South Africa remains the continent's meth heartland — for use, production and as a trafficking springboard. Behind it, UNODC data shows meth seizures reported by 26 African countries, with Mozambique and Nigeria recording the largest aggregate quantities and a growing West African consumer market.",
  cities=[
   ("1","Cape Town, SA","The original African meth city. Tik is the most common primary drug among under-20s entering treatment in the Western Cape (over half of admissions in recent data), community studies have found lifetime use above 10% among school learners, and the city's gang-controlled distribution networks remain the template for the whole continent's trade."),
   ("2","Gqeberha (Port Elizabeth) / Nelson Mandela Bay, SA","The Eastern Cape's tik capital; treatment data shows the province second only to the Western Cape in meth admissions."),
   ("3","Johannesburg / Pretoria, SA","Gauteng's size makes it the largest absolute meth market; it is also the hub where tik meets the rest of Africa — Johannesburg records the country's largest population of people who inject drugs."),
   ("4","Durban, SA","KwaZulu-Natal's port city; a documented meth and heroin transshipment point with a significant local user population."),
   ("5","Lagos, Nigeria","West Africa's emerging meth center: Nigeria records the third-largest aggregate meth seizures in Africa, with Lagos' markets and ports at the center of both import and — increasingly — domestic production."),
   ("6","Abuja / northern Nigeria","Nigerian drug-enforcement reporting shows meth production and use spreading north of the capital."),
   ("7","Maputo, Mozambique","Mozambique records Africa's largest aggregate meth seizures alongside South Africa; Maputo's port is the continent's biggest meth entry point for Asian supply."),
   ("8","Nairobi / Mombasa, Kenya","Kenya's coastal and capital markets: meth ('banga') is the rising stimulant behind the region's dominant heroin trade, with Mombasa' port as the entry point."),
   ("9","Windhoek, Namibia","Namibia shares South Africa's tik market; treatment and police data show meth as the country's leading hard drug."),
   ("10","Accra, Ghana","Ghanaian reporting shows growing meth seizures and local production (including 'kush'-adjacent stimulant mixtures) in the capital region."),
  ],
  notes="Continental caveat: almost no African country has modern wastewater monitoring or household drug surveys. This ranking leans on treatment admissions (South Africa's SACENDU/Central Drug Authority data is the best on the continent), seizure geography from UNODC, and targeted academic studies.",
  method="Methodology: South African Central Drug Authority treatment statistics (2022–24), SACENDU monitoring, UNODC World Drug Report seizure data by country (2011–2023), and peer-reviewed community studies. Rankings outside South Africa are inferred from seizure and treatment geography — treat as directional.",
  sources=["South African Central Drug Authority annual report 2023/24","SACENDU research briefs","UNODC World Drug Report — Africa meth trends","Western Cape Government / UNODC tik reporting","Peer-reviewed Cape Town tik studies (PMC)"]),
]
