# Crack cocaine city rankings by region — same sourced, hedged, citable formula.
# Method note: no country measures crack use per city directly; rankings combine
# treatment admissions, surveys, hospital data and police/seizure reporting.

CRACK_CITY_PAGES = [
 dict(slug="crack-cities-usa", region="United States", title="Top 10 US cities with the most crack cocaine use",
  updated="September 2026", read="8 min",   desc="Four decades after the epidemic began, crack remains entrenched in America's hardest-hit neighborhoods — Philadelphia, Baltimore, Detroit and the cities treatment data keeps naming.",
  stats=[("~500k","Americans used crack in the past year (NSDUH)"),("4×","crack-involved overdose deaths have roughly quadrupled since 2015 — now usually fentanyl-involved"),("1985→","crack has been a US street fixture for over 40 years")],
  intro="Crack is America's oldest ongoing urban drug crisis. It never left — it faded from headlines as opioids took over, but treatment admissions, emergency-department data and police reporting show a stable, aging, deeply entrenched user base concentrated in the same neighborhoods the 1980s–90s epidemic hit hardest. The modern danger is different: today's crack supply increasingly shares a market with fentanyl, and stimulant-opioid co-use now drives crack-involved deaths. This ranking triangulates SAMHSA treatment admissions (TEDS), ED reporting and city-level drug-market assessments.",
  cities=[
   ("1","Philadelphia, PA","America's most visible open-air drug market (Kensington). Crack is deeply entrenched alongside the fentanyl/tranq crisis, and Philly consistently posts among the highest stimulant-involved death rates of any big city."),
   ("2","Baltimore, MD","A four-decade crack and heroin city — Baltimore's treatment system reports crack cocaine among its top admission substances, and the market remains highly visible."),
   ("3","Detroit, MI","One of the original epicenters of the 1980s crack trade; Detroit's treatment admissions and seizure data keep it in the top tier today."),
   ("4","New York City, NY","The biggest absolute market — NYC's crack trade began the national epidemic, and crack/cocaine remains a top-3 treatment admission substance across the boroughs."),
   ("5","Chicago, IL","The West and South Side open-air markets are among America's largest; Chicago posts top-tier cocaine/crack ED and admission numbers."),
   ("6","Los Angeles, CA","Skid Row is the West Coast's most concentrated drug market; crack has been its backbone since the 1980s, now competing with meth and fentanyl."),
   ("7","Washington, DC","The city the 1980s epidemic nearly broke — DC retains one of the country's highest per-capita cocaine/crack use rates (cocaine overall ~3.7% past-year)."),
   ("8","Houston, TX","The South's largest crack market — Houston's treatment admissions for cocaine (primarily crack) lead Texas by a wide margin."),
   ("9","Atlanta, GA","The Southeast's distribution and consumption hub; crack markets concentrate in the city's westside neighborhoods."),
   ("10","New Orleans, LA","Per-capita, one of America's heaviest crack cities — a small city with outsized treatment-admission and arrest numbers."),
  ],
  notes="The critical modern context: crack users are dying of fentanyl, not crack. Most crack-involved overdose deaths now involve opioids — either intentional co-use (speedballing/goofballing) or a contaminated supply. Anyone using crack in 2026 needs to know the stimulant supply can carry fentanyl, and naloxone should be in reach.",
  method="Methodology: SAMHSA TEDS treatment admissions by metro, DAWN-style ED reporting, HIDTA market assessments, and city health-department data (2023–26). Rankings are directional.",
  sources=["SAMHSA Treatment Episode Data Set (TEDS)","SAMHSA NSDUH 2023–24","CDC overdose surveillance","HIDTA market assessments 2025"]),

 dict(slug="crack-cities-canada", region="Canada", title="Top 10 Canadian cities with the most crack cocaine use",
  updated="September 2026", read="6 min",   desc="Vancouver's Downtown Eastside, Toronto and Winnipeg lead Canada's crack map — a market now entangled with the fentanyl crisis.",
  stats=[("DTES","Vancouver's Downtown Eastside is Canada's most studied open drug market"),("Rising","stimulant-opioid co-use deaths across Canada since 2016"),("$10","a typical crack rock price in Canadian street markets")],
  intro="Canada's crack market is concentrated and visible: Vancouver's Downtown Eastside has been the country's ground zero for three decades, with Toronto, Winnipeg and Montreal behind. As in the US, the crisis has merged with fentanyl — British Columbia's coroners report stimulants detected in a large share of opioid toxicity deaths. This ranking triangulates treatment data, shelter/outreach reporting and police assessments.",
  cities=[
   ("1","Vancouver, BC","The Downtown Eastside is Canada's most concentrated crack and injection market — three decades of supervised-consumption sites, and still the country's benchmark for open drug-market severity."),
   ("2","Toronto, ON","Canada's largest absolute crack market — concentrated in the downtown east corridor, with the country's biggest supervised-consumption network."),
   ("3","Winnipeg, MB","The prairies' crisis city — Winnipeg's crack and meth markets overlap heavily, and per-capita indicators are among Canada's worst."),
   ("4","Montreal, QC","Quebec's largest market — the Village/downtown east corridor has visible crack and injection scenes."),
   ("5","Edmonton, AB","Alberta's hardest-hit city per capita — the inner-city market combines crack, meth and fentanyl."),
   ("6","Calgary, AB","Pairs with Edmonton — a large, visible downtown market."),
   ("7","Ottawa, ON","The capital's ByWard Market corridor concentrates the city's crack trade."),
   ("8","Hamilton, ON","Ontario's secondary industrial-city market — steady treatment admissions for crack cocaine."),
   ("9","Halifax, NS","Atlantic Canada's largest market — small in absolute terms, significant per capita."),
   ("10","London, ON","Southwestern Ontario's hub — one of Canada's first cities to pilot safer-supply programs in response to its crisis."),
  ],
  notes="Canadian particularity: several cities ran supervised-consumption sites and safer-supply pilots specifically because the crack/fentanyl overlap made the market so lethal. Political changes have closed some sites since 2024 — check current local availability.",
  method="Methodology: provincial treatment data, BC Coroners Service reporting, shelter/outreach system data, police assessments (2023–26). Rankings are directional.",
  sources=["BC Coroners Service illicit-drug death reports","Canadian Centre on Substance Use and Addiction","Toronto/Vancouver public-health reporting","Statistics Canada"]),

 dict(slug="crack-cities-europe", region="Europe", title="Top 10 European cities with the most crack cocaine use",
  updated="September 2026", read="7 min",   desc="Crack in Europe is a British and Irish story first — London, Birmingham and Dublin lead, with Paris and Antwerp's open scenes rising fast.",
  stats=[("UK #1","England & Wales have Europe's largest crack market by treatment numbers"),("Rising","crack treatment admissions across Western Europe for a decade straight"),("Paris","opened its first supervised consumption rooms partly in response to open crack scenes")],
  intro="European crack is not evenly spread: the UK and Ireland have deep, established markets going back to the 1990s, while France and Belgium have newer, fast-growing open scenes (Paris's 'Colline du crack', Antwerp's station district). Cocaine's record purity and falling prices have pushed crack conversion into new markets. This ranking triangulates EMCDDA treatment data, national reporting and city-level assessments.",
  cities=[
   ("1","London, UK","Europe's largest crack market — England's treatment system reports tens of thousands of crack users (most combined with heroin), and London holds the biggest share."),
   ("2","Birmingham, UK","The UK's second city has its second-largest crack market — treatment admissions and open-market policing both rank it top-tier."),
   ("3","Liverpool, UK","A historic port-city market — Merseyside posts among England's highest per-capita crack indicators."),
   ("4","Manchester, UK","The northwest's second hub — a large, established market with strong treatment-system visibility."),
   ("5","Dublin, IE","Ireland's crack market has grown sharply — Dublin's treatment services report crack among their fastest-growing presentation drugs."),
   ("6","Paris, FR","France's most visible crack crisis — the open scenes of northeast Paris (Porte de la Chapelle, 'Colline du crack') drove the city to open supervised consumption rooms."),
   ("7","Antwerp, BE","The cocaine gateway's local spillover — crack use around the station district has grown with record port seizures; the city runs consumption rooms."),
   ("8","Amsterdam, NL","An old, stable market — Amsterdam has had a visible crack scene since the 1990s, smaller relative to the city's size than the UK's."),
   ("9","Glasgow, UK","Scotland's largest market — Glasgow's drug-crisis profile (Europe's highest drug-death rates) includes a significant crack component."),
   ("10","Frankfurt, DE","Germany's most famous open drug scene (Bahnhofsviertel) — crack and heroin dominate its consumption rooms."),
  ],
  notes="The European crack story is really three stories: the UK's entrenched heroin-crack pairing ('brown and white'), Ireland's rapid growth, and the new open scenes in France and Belgium fed by record cocaine supply. Spain and Portugal have smaller, older markets (Barcelona's narco-pisos).",
  method="Methodology: EMCDDA/EUDA treatment-demand indicator, national treatment data (UK OHID, France OFDT), city reporting (Paris, Antwerp, Frankfurt). Rankings are directional.",
  sources=["EUDA European Drug Report 2025","UK OHID treatment statistics","OFDT (France) reporting","Dublin/Paris/Antwerp city health reporting"]),

 dict(slug="crack-cities-australia", region="Australia", title="Crack cocaine in Australian cities — an honest ranking",
  updated="September 2026", read="6 min",   desc="Australia is one of the few rich countries where crack never took hold — Sydney and Melbourne have small markets, and that's the story.",
  stats=[("Rare","crack remains a niche drug in Australia — cocaine is overwhelmingly snorted powder"),("Price wall","cocaine at ~$300/g keeps Australia's market affluent; crack economics never landed"),("Sydney","hosts most of what crack market exists")],
  intro="An honest page: Australia is the outlier among wealthy countries — crack cocaine never established a mass market here. High cocaine prices (3–5× US/European street prices), geographic isolation, and a methamphetamine-dominated stimulant market meant the crack epidemic skipped Australia. What crack market exists is small and concentrated in Sydney and Melbourne's inner-city street scenes. This ranking is short and hedged by design.",
  cities=[
   ("1","Sydney, NSW","Most of Australia's visible crack market — inner-city street scenes (Kings Cross, Redfern) account for the majority of crack-related service contacts."),
   ("2","Melbourne, VIC","Victoria's small market — concentrated in the inner north and CBD street economy."),
   ("3","Brisbane, QLD","A marginal market — occasional treatment presentations, no open scene."),
   ("4","Perth, WA","Minimal — Perth's stimulant crisis is meth, by a very wide margin."),
   ("5","Adelaide, SA","Minimal — same pattern: meth dominates."),
   ("6","Darwin, NT","Minimal — alcohol and meth dominate NT's drug harms."),
  ],
  notes="Why this matters: Australia's drug harms concentrate in meth, alcohol and opioids — crack is a footnote. If you're researching Australian stimulant markets, the meth-cities page is the one that reflects reality.",
  method="Methodology: AIHW treatment-episode data (cocaine/smoked-cocaine presentations), Needle & Syringe Program surveys, state health reporting. Small numbers — rankings are indicative only.",
  sources=["AIHW Alcohol and Other Drug Treatment Services","Australian Needle and Syringe Program Survey","ACIC wastewater program (cocaine, not crack-specific)"]),

 dict(slug="crack-cities-middle-east", region="Middle East", title="Crack cocaine in Middle East cities — an honest ranking",
  updated="September 2026", read="5 min",   desc="Crack is nearly absent from the Middle East — the region's stimulant story is Captagon, and this page says so honestly rather than inventing a ranking.",
  stats=[("Minimal","no Middle East country reports a significant crack market"),("Captagon","is the region's actual stimulant crisis — millions of pills, not rocks"),("Transit ≠ use","cocaine transits the region; local crack markets barely exist")],
  intro="An honest page: the Middle East has no meaningful crack cocaine market. Cocaine transits the region (via the Gulf and East Africa routes) and a small powder market exists in wealthy nightlife cities, but crack — a cheap, smokable, mass-market form — has never established itself. The region's stimulant crisis is Captagon, and its smokable-drug crises are meth (Iran, Iraq) and hashish. Rather than fabricate a top-10, this page lists the only cities with any reported crack presence.",
  cities=[
   ("1","Tehran, IR","Iran is the regional exception: alongside a large meth market, treatment services report small numbers of crack ('crack-e Irani') presentations — though the Iranian term often refers to condensed heroin, not cocaine."),
   ("2","Tel Aviv, IL","Israel's street-drug scene includes a small crack market alongside cocaine powder, mostly in south Tel Aviv's marginalized communities."),
   ("3","Beirut, LB","A tiny market within Lebanon's broader polysubstance economy."),
   ("4","Dubai, AE","Effectively zero local market — strict enforcement and an affluent powder-cocaine niche instead."),
  ],
  notes="If you're researching Middle East drug markets, the meaningful pages are Captagon (the Gulf's stimulant epidemic), meth (Iran/Iraq) and tramadol. This page exists to be honest about absence rather than to inflate a ranking.",
  method="Methodology: UNODC regional assessments, national treatment reporting (Iran Darius Institute, Israel), seizure data. Evidence of absence is the finding here.",
  sources=["UNODC World Drug Report 2025","Iran national treatment reporting","Israeli anti-drug authority data","Gulf customs reporting"]),

 dict(slug="crack-cities-africa", region="Africa", title="Top African cities for crack cocaine use",
  updated="September 2026", read="6 min",   desc="Crack's African footprint is small but real — Johannesburg, Cape Town and Lagos lead a market growing on the back of record cocaine transshipment.",
  stats=[("Growing","Africa's cocaine supply hit records — local crack markets follow the transit routes"),("ZA leads","South Africa has the continent's most established crack market ('rocks')"),("Corridor logic","crack appears where cocaine transships: Lagos, Nairobi, the SA ports")],
  intro="Africa's crack story follows its cocaine corridors: as the continent became a major transit zone between South America and Europe/Asia, local consumption markets grew along the routes. South Africa has the oldest and largest market (crack 'rocks' have been sold in Cape Town and Johannesburg since the 1990s), with Nigeria, Kenya and Mozambique developing visible markets in transit cities. Data is thin — treat positions as bands.",
  cities=[
   ("1","Johannesburg, ZA","Africa's largest crack market — 'rocks' have been entrenched in Joburg's inner city (Hillbrow) since the 1990s; SACENDU reporting consistently ranks smoked cocaine high in treatment admissions."),
   ("2","Cape Town, ZA","The twin hub — Cape Town's crack market overlaps with its meth ('tik') crisis, and treatment data shows both stimulants at scale."),
   ("3","Durban, ZA","The port city — cocaine lands here, and the local market follows."),
   ("4","Lagos, NG","West Africa's hub — Lagos's cocaine market (powder and base) is the region's largest, fed by direct Brazil–Nigeria routes."),
   ("5","Nairobi, KE","East Africa's transit-to-consumption story — Kenyan seizures have grown, and Nairobi's street markets now include smokable cocaine."),
   ("6","Maputo, MZ","Mozambique's capital is a key landing point for the 'southern route' — local use has followed transshipment."),
   ("7","Abidjan, CI","West Africa's secondary hub — Côte d'Ivoire's record seizures (2022's 2-ton bust) track with a growing local market."),
   ("8","Dakar, SN","Senegal's capital sits on the Atlantic transshipment route; local consumption indicators are rising."),
  ],
  notes="Context matters: in most of Africa, crack is a secondary market behind the bigger crises — kush in Sierra Leone/Liberia, tramadol in the Sahel and West Africa, meth (tik) in South Africa, nyaope in the townships. But every record cocaine seizure year pushes the local markets up.",
  method="Methodology: UNODC World Drug Report, SACENDU (South Africa) treatment data, national seizure reporting, ENACT organized-crime research. Rankings are hedged bands.",
  sources=["UNODC World Drug Report 2025","SACENDU treatment reporting","ENACT Africa observatory","National seizure reporting 2024–26"]),
]
