# Cocaine city rankings by region — same sourced, hedged, citable formula as the meth pages.
# Method note: no country measures cocaine use per city directly; rankings combine
# wastewater analysis, forensic-lab reporting, treatment admissions and police seizures.

COCAINE_CITY_PAGES = [
 dict(slug="cocaine-cities-usa", region="United States", title="Top 10 US cities with the most cocaine use",
  updated="September 2026", read="8 min", image="https://plugreports.com/media/drugs/cocaine.jpeg",
  desc="The US cities where cocaine use is highest, ranked from state-level survey data, DEA NFLIS forensic reporting and market intelligence — with plain-English context per city.",
  stats=[("195,317","cocaine reports to US forensic labs (NFLIS 2025) — the #2 reported substance"),("5.2 M","Americans used cocaine in the past year (NSDUH)"),("3.7%","past-year cocaine use in Washington DC — the highest rate in the country")],
  intro="No US agency publishes a clean per-city cocaine ranking. The closest proxies are SAMHSA's state-level past-year use estimates (Colorado, Vermont, Rhode Island, Massachusetts, California, New York and DC lead the country), DEA NFLIS forensic-lab report counts by metro area, and drug-market reporting on distribution hubs. Combined they draw a consistent map: the biggest cocaine markets are the Northeast corridor, South Florida, and the Southwest border metros — with Colorado and the Pacific Northwest as the highest per-capita user states. Positions 4–8 should be read as a band, not an exact order.",
  cities=[
   ("1","New York City, NY","The largest cocaine market in America by consumption volume. New York State sits in the top tier of past-year use (~2.4% of adults, ~364,000 users), and NYC's nightlife economy, finance-sector demand and port/airport entry points make it the Northeast's undisputed hub."),
   ("2","Miami, FL","The historical gateway — Miami has been the US cocaine entry point since the 1980s, and South Florida HIDTA reporting still places it among the top import-and-consumption metros, fed by Caribbean and maritime routes."),
   ("3","Los Angeles, CA","California has the largest cocaine user population of any state (~754,000 past-year users), and LA is its center — a huge consumer market that also stages distribution for the whole West."),
   ("4","Washington, DC","The highest per-capita cocaine use in the country: ~3.7% of DC adults used cocaine in the past year — more than double the national average of 1.76%."),
   ("5","Chicago, IL","The Midwest's cocaine capital — Illinois posts high per-capita use (~2.2%), and Chicago's role as the region's distribution crossroads keeps its market large and visible in NFLIS metro reporting."),
   ("6","Houston, TX","Texas reports the largest cocaine user base in the South (~318,000), and Houston's port, border proximity and size make it the state's dominant market."),
   ("7","Denver, CO","Colorado leads the nation in per-capita cocaine use (~3.1% of adults past-year) — Denver's young, affluent, nightlife-heavy demographics drive the country's highest consumption rate outside DC."),
   ("8","Boston, MA","Massachusetts ranks #4 nationally for per-capita use (~2.6%); Boston anchors the New England market, which surveys consistently place in the country's top tier."),
   ("9","Phoenix, AZ","Survey data places Phoenix at or near the top of US cities for lifetime cocaine use (over 20% of residents report having tried it), and the I-10 border corridor keeps supply cheap and constant."),
   ("10","Atlanta, GA","The Southeast's distribution hub — Georgia's user numbers are lower per capita, but Atlanta's interstate crossroads (I-75/I-85/I-20) make it the region's cocaine logistics center."),
  ],
  notes="Honorable mentions: San Francisco/Oakland and Seattle (Pacific states rank high per capita), Las Vegas (tourism-driven market), and Dallas. Note the pattern: cocaine in America is a big-city, weekend drug — unlike meth, it concentrates in the largest metros, not rural areas.",
  method="Methodology: composite of SAMHSA NSDUH state-level past-year cocaine use estimates (2023–24), DEA NFLIS-Drug forensic report counts by metro area, and HIDTA / drug-market reporting. State-level rates are mapped to their dominant cities. Rankings are directional.",
  sources=["SAMHSA National Survey on Drug Use and Health (state estimates 2023–24)","DEA NFLIS-Drug 2025 annual report","DEA 2025 National Drug Threat Assessment","HIDTA threat assessments (NY/NJ, South Florida, Southwest Border)"]),

 dict(slug="cocaine-cities-canada", region="Canada", title="Top 10 Canadian cities with the most cocaine use",
  updated="September 2026", read="7 min", image="https://plugreports.com/media/busts/vancouver-cocaine-328kg-tshirts.jpeg",
  desc="Where cocaine hits hardest in Canada — Toronto, Vancouver and Montreal lead, with the prairies rising. Ranked from wastewater data, CBSA seizures and police-reported offences.",
  stats=[("328 kg","single largest cocaine seizure in Vancouver police history (2026)"),("~2.5%","past-year cocaine use among Canadian adults (Health Canada survey)"),("Top-3","Toronto, Vancouver, Montreal dominate every Canadian cocaine indicator")],
  intro="Canada's cocaine map is a big-city story: the three largest metros — Toronto, Vancouver, Montreal — dominate every indicator from wastewater loads to seizure volumes to treatment admissions. Unlike meth (a prairie problem), cocaine concentrates where the money and the ports are. Wastewater comparisons published by the EUDA show Canadian cities posting cocaine metabolite loads similar to or higher than Europe's top cities.",
  cities=[
   ("1","Toronto, ON","Canada's largest cocaine market by every measure — the biggest user base, the busiest distribution networks, and the destination for most supply entering through southern Ontario."),
   ("2","Vancouver, BC","The import capital: cocaine arrives through the Port of Vancouver and the US border, and the Lower Mainland's organized-crime networks redistribute it nationally. The 328 kg T-shirt-container seizure of 2026 — the largest in VPD history — underlines the scale."),
   ("3","Montreal, QC","The East Coast gateway: the Port of Montreal is a documented cocaine entry point from the Caribbean and South America, and Montreal's market serves Quebec and the Maritimes."),
   ("4","Calgary, AB","Alberta's largest city and its cocaine center — affluent demographics and oil-industry income have long made Calgary a high-consumption market."),
   ("5","Edmonton, AB","Pairs with Calgary as Alberta's twin market; ALERT seizure reporting shows steady cocaine flow up the Edmonton–Calgary corridor."),
   ("6","Ottawa, ON","The capital posts consistently high cocaine indicators — Ottawa police list cocaine among the city's most-seized drugs, and the Ottawa Valley corridor links Toronto and Montreal supply."),
   ("7","Winnipeg, MB","The prairies' distribution hub — Winnipeg feeds Manitoba and northwestern Ontario, and while meth dominates its harm statistics, cocaine seizures are large and steady."),
   ("8","Halifax, NS","Atlantic Canada's entry point — the Port of Halifax is a documented cocaine gateway (multi-hundred-kilo seizures), serving the region's market."),
   ("9","Hamilton / Niagara, ON","Southern Ontario's secondary market, sitting on the Toronto–US border corridor."),
   ("10","Quebec City, QC","Quebec's second market, supplied through Montreal networks."),
  ],
  notes="Pattern to note: Canadian cocaine follows ports and money — Toronto (finance), Vancouver and Montreal (ports), Calgary (oil income). The prairies that dominate meth statistics sit far lower on cocaine.",
  method="Methodology: composite of Statistics Canada police-reported drug offences by CMA, CBSA and RCMP/ALERT seizure reporting (2024–26), EUDA international wastewater comparisons, and provincial treatment data. Rankings are directional.",
  sources=["Statistics Canada police-reported crime statistics","CBSA seizure reporting 2025–26","Vancouver Police Department (2026 record seizure)","EUDA international wastewater comparison","Health Canada Canadian Drug Use Survey"]),

 dict(slug="cocaine-cities-europe", region="Europe", title="Top 10 European cities with the most cocaine use",
  updated="September 2026", read="7 min", image="https://plugreports.com/media/drugs/cocaine-purity-and-cuts.jpeg",
  desc="Europe's cocaine capitals measured in sewage: Antwerp, Amsterdam, Zurich and Barcelona lead the SCORE/EUDA wastewater ranking — use rose 22% in a single year.",
  stats=[("+22%","rise in cocaine metabolite loads across European cities, 2024–25"),("130","cities in 28 countries measured in the 2025 SCORE study"),("1,722 mg","benzoylecgonine per 1,000 people per day in Antwerp (2023) — Europe's record")],
  intro="Europe has the world's best city-level cocaine data: the SCORE group's annual wastewater study measures benzoylecgonine (cocaine's main metabolite) in the sewage of 130 cities across 28 countries. The 2025 results show record consumption — up 22% in one year — concentrated in the west and south: Belgium, the Netherlands, Switzerland and Spain dominate, with the UK, Germany and France behind them and eastern Europe rising from a low base. Weekend spikes in more than 75% of cities confirm cocaine's recreational, nightlife-driven pattern.",
  cities=[
   ("1","Antwerp, BE","Europe's cocaine capital — 1,722 mg of benzoylecgonine per 1,000 people per day in 2023, the highest ever recorded in the study. The Port of Antwerp is the continent's main cocaine gateway (record multi-ton seizures annually), and local consumption matches the transshipment scale."),
   ("2","Amsterdam, NL","Consistently top-three: ~1,210 mg/1,000/day in recent rounds. The Netherlands' port cities combine gateway status with high domestic use."),
   ("3","Zurich, CH","Switzerland's financial capital posts Europe's highest non-port loads — affluent, nightlife-driven consumption that has held top-five positions for a decade."),
   ("4","Barcelona, ES","The steepest riser: +185% year-on-year in the 2025 study, putting Catalonia's capital firmly in Europe's top tier alongside Tarragona (1,464 mg in 2023) and Lleida (+100%)."),
   ("5","Rotterdam, NL","Europe's largest port and Antwerp's twin gateway — 1,088 mg/1,000/day in 2023, with consumption tracking the port's import volumes."),
   ("6","Brussels, BE","Belgium's capital joins Antwerp in the top band — Belgium now posts multiple cities in Europe's top 20."),
   ("7","Geneva, CH","Switzerland's second entry in the top 20 — international-organization demographics and cross-border French supply."),
   ("8","London, UK","The UK's largest market; UK cities measured in the study (Middlesbrough, Bristol in 2025) show loads comparable to Europe's top tier, and London's consumption volume is the country's biggest by far."),
   ("9","Madrid, ES","Spain's capital rounds out the Iberian cluster — Spain's cities dominate the southern-Europe cocaine belt."),
   ("10","Paris, FR","France's largest market; French wastewater and survey data show cocaine use at record levels, concentrated in the capital region."),
  ],
  notes="The weekend signature: over 75% of measured cities show higher cocaine metabolite loads Friday-to-Monday than midweek — the clearest recreational-use fingerprint of any drug in the study. Eastern Europe (Warsaw, Prague, Bratislava) remains low but is rising every year.",
  method="Methodology: SCORE/EUDA wastewater analysis (sampling Jan–May 2025, published March 2026) — daily benzoylecgonine mass loads per 1,000 population, supplemented by EUDA trend reporting. This is the only region where the ranking is directly measured rather than triangulated.",
  sources=["SCORE group / EUDA wastewater multi-city study 2025 (published March 2026)","EUDA European Drug Report","Urban Journalism Network analysis of SCORE data","Statista/EUDA city rankings 2023"]),

 dict(slug="cocaine-cities-australia", region="Australia", title="Top 10 Australian cities with the most cocaine use",
  updated="September 2026", read="7 min", image="https://plugreports.com/media/drugs/4-fluorococaine.jpeg",
  desc="Australia's cocaine map is the reverse of its meth map: the capitals out-consume the regions, and Sydney, Melbourne and Darwin lead. Ranked from ACIC wastewater data.",
  stats=[("Record","capital-city cocaine consumption hit an all-time high in October 2025 (ACIC)"),("+69%","rise in national cocaine consumption in a single year (2023–24)"),("A$14.3 bn","record street value of Australia's four-drug illicit market, year 9 of wastewater testing")],
  intro="Australia's National Wastewater Drug Monitoring Program (ACIC) tracks cocaine through its metabolite benzoylecgonine at 64 treatment plants covering 57% of the population. Its cocaine finding is the mirror image of meth: capital cities out-consume regional Australia. Sydney, Melbourne and Darwin lead the capital rankings, regional NSW and Queensland lead the regions, and national consumption hit record highs in late 2025 — cocaine is Australia's fastest-growing illicit drug market.",
  cities=[
   ("1","Sydney, NSW","Australia's cocaine capital — consistently the highest consumption sites in the national program, the largest market by volume, and the entry point through Port Botany and Sydney Airport. NSW outpaces the rest of the nation on cocaine, meth, MDMA and heroin combined."),
   ("2","Melbourne, VIC","Tied with Sydney at the top of the capital-city rankings in the latest reporting period; Victoria's ports and nightlife economy sustain the country's second market."),
   ("3","Darwin, NT","The surprise leader: Darwin posts among the highest per-capita cocaine consumption of any capital — small population, outsized loads."),
   ("4","Brisbane / Gold Coast, QLD","Queensland's southeast corridor — high and rising consumption, with regional Queensland sites also near the national top."),
   ("5","Perth, WA","WA's mining wealth drives a solid cocaine market, though per-capita loads sit below Sydney/Melbourne — Perth's drug of choice remains meth."),
   ("6","Canberra, ACT","The national capital's affluent, young-professional demographics produce high per-capita cocaine loads relative to its size."),
   ("7","Adelaide, SA","Mid-table nationally; SA sites run below the eastern capitals but show the same rising trend."),
   ("8","Hobart, TAS","Tasmania's small market is growing; Hobart's loads remain below the mainland capitals."),
   ("9","Regional NSW (Newcastle, Wollongong, Byron)","The strongest regional cocaine consumption in the country — coastal NSW towns track close to capital-city levels."),
   ("10","Regional QLD (Cairns, Townsville)","Queensland's regional sites post the second-highest regional loads, fed by tourism and port access."),
  ],
  notes="The ACIC's own framing: regional Australia runs on meth, the capitals run on cocaine. Capital-city cocaine consumption set an all-time record in October 2025, and the ACIC flags 'potential for further increases' as its top forward trend.",
  method="Methodology: ACIC National Wastewater Drug Monitoring Program (Year 9, December 2024–October 2025, 64 sites covering 57% of population) — benzoylecgonine loads by site, combined with state reporting. Rankings combine per-capita loads with absolute market size.",
  sources=["ACIC National Wastewater Drug Monitoring Program Report 25 (Year 9)","Law Society Journal analysis of ACIC data (2026)","Australian Institute of Health and Welfare wastewater reporting"]),

 dict(slug="cocaine-cities-middle-east", region="Middle East", title="Cocaine in the Middle East: the cities where it concentrates",
  updated="September 2026", read="6 min", image="https://plugreports.com/media/drugs/cocaine-nasal-spray.jpg",
  desc="A small but fast-growing market: Beirut, Dubai and Tel Aviv anchor the Middle East's cocaine map, with Gulf seizures setting records.",
  stats=[("Record","Gulf states posted record cocaine seizures in 2024–25"),("Beirut","the region's historic cocaine capital since the 1990s"),("Transit","the Middle East is shifting from destination to transit corridor for Europe-bound cocaine")],
  intro="Cocaine in the Middle East is a boutique market compared to Europe or the Americas — but it is growing fast, and it clusters tightly: Beirut's long-established scene, the Gulf's wealth-driven cities, and Israel's club economy. UNODC reporting shows the region increasingly used as a transit corridor between South America and Europe/Africa, and record seizures at Gulf ports suggest consumption is following the trade.",
  cities=[
   ("1","Beirut, LB","The region's historic cocaine capital — Lebanon's party economy and banking-elite demand have sustained the Middle East's most visible cocaine scene since the 1990s, despite the economic collapse pushing prices out of reach for most."),
   ("2","Dubai, AE","The Gulf's largest market: expatriate wealth, nightlife and the region's busiest port/airport hub. UAE authorities report record cocaine seizures, and Dubai serves as both destination and redistribution point."),
   ("3","Tel Aviv, IL","Israel's club capital — cocaine is the established drug of the Tel Aviv nightlife scene, with Israeli reporting consistently placing it behind only cannabis and MDMA in urban use."),
   ("4","Riyadh, SA","Saudi Arabia's growing market — rising seizures and a young, wealthy urban population; strict enforcement keeps the scene invisible but interdiction volumes keep climbing."),
   ("5","Jeddah, SA","The Kingdom's port gateway — most cocaine entering Saudi Arabia comes through Jeddah's port or nearby airports."),
   ("6","Doha, QA","Qatar's post-World-Cup market — small but wealthy, with rising seizure reports."),
   ("7","Kuwait City, KW","Regular multi-kilo seizures at Kuwait's airport and ports point to an established consumer base."),
   ("8","Amman, JO","Jordan sits on the Captagon corridor but cocaine detections are rising in step with Gulf demand."),
  ],
  notes="Data honesty: no Middle Eastern country publishes city-level prevalence. This ranking is inferred from seizure geography, nightlife-market reporting and UNODC regional assessments — it is the most uncertain ranking on this site. The dominant stimulant across most of the region remains Captagon, not cocaine.",
  method="Methodology: triangulation of UNODC regional reporting, national seizure announcements (UAE, Saudi Arabia, Kuwait, Lebanon), and drug-market journalism. High uncertainty — treat as directional.",
  sources=["UNODC World Drug Report — Middle East & Gulf chapters","UNODC regional programme reporting","National seizure announcements (UAE MoI, Saudi GDNC, Lebanese ISF)","InSight Crime cocaine seizure round-up 2024"]),

 dict(slug="cocaine-cities-africa", region="Africa", title="Cocaine in Africa: the cities where it lands and sells",
  updated="September 2026", read="7 min", image="https://plugreports.com/media/drugs/bust-river-grove-cocaine.png",
  desc="Africa is the world's fastest-growing cocaine corridor — West African ports land it, South African cities consume it. Lagos, Johannesburg and Cape Town lead.",
  stats=[("35–40 t","seized from a single cargo ship linked to Freetown, Sierra Leone (2024)"),("300 t","cocaine seized globally with UN facilitation in 2024 — African corridors growing fastest"),("West + South","the two African cocaine poles: West African transit, South African consumption")],
  intro="Africa's cocaine story has two halves. West Africa is the world's fastest-growing transit corridor — South American cocaine lands in the ports of Nigeria, Ghana, Sierra Leone, Senegal and Côte d'Ivoire for re-export to Europe, and a growing share stays for local consumption. Southern Africa is the consumption pole — South Africa's cities have had established cocaine markets for decades. Seizure data from UNODC and national agencies maps both halves clearly.",
  cities=[
   ("1","Lagos, NG","West Africa's cocaine capital: Nigeria records the region's largest seizures and its biggest consumer market. Lagos' ports (Apapa, Tin Can) are documented entry points, and the city's wealth gap mirrors its market — elite consumption up top, crack ('rocks') at the bottom."),
   ("2","Johannesburg, SA","Africa's largest consumer market by value — Gauteng's finance and nightlife economy sustains the continent's most mature cocaine scene, supplied through Durban's port and OR Tambo airport."),
   ("3","Cape Town, SA","South Africa's second market — cocaine and 'cocaine rocks' are established in Cape Town's gang economy alongside the dominant tik trade."),
   ("4","Durban, SA","The entry point: Durban's port is Southern Africa's main cocaine gateway — most of what Johannesburg and Cape Town consume lands here first."),
   ("5","Accra, GH","Ghana's capital is a rising transit-and-consumption hub — Kotoka airport and Tema port feature regularly in multi-hundred-kilo seizures."),
   ("6","Freetown, SL","Put on the map by the 2024 seizure of 35–40 tonnes from a cargo ship linked to the port — one of the largest single cocaine hauls in African history."),
   ("7","Abidjan, CI","Côte d'Ivoire's commercial capital — a growing West African transshipment point with rising local use."),
   ("8","Dakar, SN","Senegal's capital anchors the northern end of the West African corridor, with regular seizures at Dakar's port and airport."),
   ("9","Nairobi, KE","East Africa's hub — Nairobi's airport and Mombasa's port serve a growing Kenyan market and re-export routes to Asia."),
   ("10","Luanda, AO","Angola's Portuguese-language link to Brazil makes Luanda a natural South Atlantic landing point — Brazilian crime groups (PCC) are documented using the route."),
  ],
  notes="The trend that matters: UNODC data shows West Africa shifting from pure transit to transit-plus-consumption — local markets in Lagos, Accra and Dakar are growing on the back of the Europe-bound flow. Treatment systems built for cannabis and heroin are not prepared for cocaine dependence.",
  method="Methodology: UNODC World Drug Report seizure and transit data (2019–2025), national enforcement reporting (Nigeria NDLEA, South Africa SAPS, Ghana NACOC), and InSight Crime corridor analysis. Consumption rankings outside South Africa are inferred — treat as directional.",
  sources=["UNODC World Drug Report — Africa cocaine trends","UN News: UN-facilitated seizures 2024","InSight Crime 2024 cocaine seizure round-up","Nigeria NDLEA / Ghana NACOC seizure reporting","Sierra Leone Freetown cargo-ship seizure reporting (2024)"]),
]
