# Spanish (es) translations — batch 1: home hero, hotlines, top-10 drug profiles.
# Fields not translated here stay English on /es/ pages until batch 2.

ES_CATS = {
 "opioids":"Opioides","stimulants":"Estimulantes","benzodiazepines":"Benzodiacepinas",
 "sedatives":"Sedantes e hipnóticos","depressants":"GHB / GBL","dissociatives":"Disociativos",
 "empathogens":"Empatógenos","psychedelics":"Psicodélicos","cannabinoids":"Cannabinoides sintéticos",
 "performance":"Rendimiento y farmacia gris","hazardous":"Sustancias peligrosas"}

ES_HOME = {
 "kicker":"Biblioteca de reducción de riesgos · 92 sustancias · 5 regiones",
 "h1":"Conoce la droga.<br>Conoce el <span class=\"mark\">riesgo</span>.<br>Conoce la salida.",
 "lede":"plugreports es un directorio visual de drogas de calle, adulterantes, líneas de ayuda, incautaciones y ayuda verificada — para que cualquier persona encuentre información clara, rápida y que salva vidas.",
 "btn1":"Ayuda ahora","btn2":"Explorar la biblioteca","btn3":"Dejarlo, día a día",
 "st1":"perfiles de drogas","st2":"categorías","st3":"líneas verificadas","st4":"guías y cronogramas",
 "hl_kicker":"Ayuda","hl_h2":"Líneas de ayuda por región",
 "hl_p":"Números verificados en EE. UU., Canadá, Europa, Australia y África.",
 "hl_btn":"Directorio completo de líneas de ayuda"}

ES_REGIONS = {"USA":"EE. UU.","Canada":"Canadá","Europe":"Europa","Australia":"Australia","Africa":"África"}

ES_HOTLINES = {
 "USA":[
  ["Emergencias — sobredosis, llama siempre","Bomberos/EMS llevan naloxona; las leyes del buen samaritano protegen a quien llama en la mayoría de estados."],
  ["Línea nacional SAMHSA","Gratuita, 24/7, referencias confidenciales de tratamiento (español/inglés)."],
  ["Línea 988 de suicidio y crisis","Llama o envía un mensaje al 988 — apoyo en crisis 24/7."],
  ["Control de envenenamiento","Evaluación 24/7 de envenenamientos y sobredosis."],
  ["Never Use Alone","Llama mientras consumes — un operador permanece en la línea y avisa si pierdes el conocimiento."],
  ["Línea de texto en crisis","Envía HOME al 741741 — apoyo gratuito 24/7 por mensaje."]],
 "Canada":[
  ["Emergencias","Peligro inmediato para la vida — llama primero siempre."],
  ["Línea de crisis 9-8-8","Llama o envía un mensaje al 9-8-8, 24/7."],
  ["ConnexOntario","Línea de ayuda para consumo de sustancias, 24/7, gratuita."],
  ["Teléfono de la Ayuda Infantil","Apoyo para jóvenes, llama o envía un mensaje."]],
 "Europe":[
  ["Número de emergencia de la UE","Funciona en todos los países miembros, gratuito, 24/7."],
  ["FRANK (Reino Unido)","Información y consejo sobre drogas, 24/7, confidencial."],
  ["Drogues Info Service (Francia)","Información gratuita y anónima sobre drogas."],
  ["Línea federal de drogas (Alemania)","Línea nacional de adicciones y drogas."],
  ["Jellinek (Países Bajos)","Línea de asesoría en adicciones."]],
 "Australia":[
  ["Emergencias","Ambulancia, policía, bomberos."],
  ["Línea nacional de alcohol y otras drogas","Consejería y referencias gratuitas 24/7."],
  ["Lifeline","Apoyo en crisis 24/7 y prevención del suicidio."],
  ["DirectLine (Victoria)","Consejería gratuita 24/7 y referencias."]],
 "Africa":[
  ["SADAG (Sudáfrica)","Línea de salud mental con apoyo para consumo de sustancias."],
  ["SANCA (Sudáfrica)","Red de referencias de tratamiento en provincias sudafricanas."],
  ["Línea NACADA (Kenia)","Línea gratuita del gobierno para el control de drogas."],
  ["Emergencias del hospital más cercano","Donde no hay líneas dedicadas, los hospitales son la vía más rápida."]]}

ES_DRUGS = {
 "fentanyl":dict(schedule="Lista II (EE. UU., uso farmacéutico)",
  appearance="Polvo blanco, pastillas prensadas, oxicodona falsificada — a menudo invisible cuando se mezcla con otras drogas",
  effects=["Euforia extrema","Somnolencia","Alivio del dolor"],
  risks=["Depresión respiratoria","Adicción en días","2 mg (~unos pocos granos) pueden ser fatales"],
  overdoseSigns=["Pupilas puntiformes (miosis)","Respiración lenta o detenida","Labios azulados, cuerpo flácido"],
  streetPrice="~$20–$40 por píldora falsificada",
  legalStatus="Delito grave en todos los estados de EE. UU.; los análogos se persiguen bajo la Ley Federal de Análogos"),
 "heroin":dict(schedule="Lista I (EE. UU.)",
  appearance="Polvo blanco/marrón ('base', 'sugar brown'); 'black tar' (México)",
  effects=["Euforia intensa ('rush')","Calor, pesadez en las extremidades","Alivio del dolor, somnolencia ('nodding')"],
  risks=["Altamente adictiva — dependencia en semanas","Sobredosis: la respiración se detiene","Potencia desconocida + contaminación con fentanilo"],
  overdoseSigns=["Inconsciente, pupilas puntiformes","Respiración lenta (<8/min) o ronquidos","Labios y uñas azulados/grisáceos"],
  streetPrice="~$10–$40 por bolsa; varía según la región",
  legalStatus="Ilegal — Lista I en EE. UU.; Clase A (RU); controlada en todas las regiones"),
 "cocaine":dict(schedule="Lista II (EE. UU.)",
  appearance="Polvo cristalino blanco (clorhidrato) o 'base'/crack; 'fishscale' = alta pureza",
  effects=["Euforia, confianza, energía","Anestesia local (adormecimiento)","Suprime el apetito y el sueño"],
  risks=["Infarto o derrame cerebral incluso en jóvenes","Adicción severa — ciclo de ansias","Adulterantes: levamisol (carne podrida), fentanilo (sobredosis)"],
  overdoseSigns=["Dolor en el pecho, palpitaciones","Convulsiones","Agitación extrema, sobrecalentamiento"],
  streetPrice="~$60–$120 por gramo (EE. UU.); varía mucho",
  legalStatus="Lista II (EE. UU.); Clase A (RU); ilegal sin fines médicos"),
 "methamphetamine":dict(schedule="Lista II (EE. UU.)",
  appearance="Cristales blancos/transparentes ('ice'), polvo o pastillas",
  effects=["Euforia intensa, energía y concentración 6–12 h","Suprime apetito y sueño","Confianza, hipersexualidad"],
  risks=["Adicción — una de las drogas más adictivas que existen","'Boca de met', heridas en la piel, psicosis","Sobredosis: derrame cerebral, paro cardíaco, sobrecalentamiento"],
  overdoseSigns=["Dolor en el pecho, arritmia","Agitación extrema, paranoia","Fiebre alta, convulsiones"],
  streetPrice="~$20–$100 por gramo (EE. UU.)",
  legalStatus="Lista II (EE. UU.); Clase A (RU); ilegal sin receta"),
 "mdma":dict(schedule="Lista I (EE. UU.)",
  appearance="Cristales o polvo blanco ('Molly'); pastillas prensadas con logos ('XTC')",
  effects=["Euforia, empatía, cercanía emocional","Energía, sentidos amplificados","La música y el ambiente se sienten mejores"],
  risks=["Sobrecalentamiento + deshidratación (o intoxicación por agua)","Bajón por agotamiento de serotonina","Las pastillas a menudo contienen PMA/PMMA (mortales)"],
  overdoseSigns=["Sobrecalentamiento, confusión","Palpitaciones, convulsiones","Bruxismo, alucinaciones"],
  streetPrice="~$10–$40 por pastilla; ~$30–$80 por gramo",
  legalStatus="Lista I (EE. UU.); Clase A (RU); controlada en todas las regiones"),
 "xylazine":dict(schedule="No es droga controlada — anestésico veterinario, adulterante",
  appearance="Sin forma propia en la calle — se encuentra mezclado con fentanilo/hheroína (polvo blanco/beige) o en pastillas",
  effects=["Sedación intensa, respiración lenta","Pérdida de conocimiento por horas","Heridas cutáneas graves (escaras)"],
  risks=["No es opioide — la naloxona NO lo revierte, aunque deja de respirar","Heridas que pudren la carne y llevan a amputación","Abstinencia doble encima de la de opioides"],
  overdoseSigns=["Inconsciente con respiración lenta","Piel azul-gris","Hipotensión severa (presión muy baja)"],
  streetPrice="Se vende como parte de bolsas de fentanilo/hheroína (~$10–$40)",
  legalStatus="Anestésico veterinario de uso recetado; uso humano ilegal"),
 "alprazolam":dict(schedule="Lista IV (EE. UU.)",
  appearance="Barras blancas de 2 mg (largas, ranuradas); tabletas azules/blancas/amarillas según la dosis",
  effects=["Alivio rápido de la ansiedad","Calma sedante","Relajación muscular"],
  risks=["Dependencia en semanas; abstinencia brutal (riesgo de convulsiones)","Las barras falsificadas contienen fentanilo o bromazolam","Amnesia y conductas riesgosas"],
  overdoseSigns=["Somnolencia extrema","Habla arrastrada","Respiración lenta — mortal con opioides o alcohol"],
  streetPrice="~$2–$10 por barra de 2 mg; falsificadas ~$1–$5",
  legalStatus="Solo con receta, Lista IV; delito sin receta"),
 "ketamine":dict(schedule="Lista III (EE. UU.)",
  appearance="Polvo cristalino blanco; viales de líquido claro (Ketalar)",
  effects=["Disociación (fuera del cuerpo), euforia","Alivio del dolor","Sedante a dosis altas"],
  risks=["Daño vesical (cistitis por ketamina) con uso regular","'K-holes' y accidentes bajo los efectos","Dependencia con uso intensivo"],
  overdoseSigns=["Inconsciente con los ojos abiertos","Respiración lenta (raramente mortal por sí sola)","Vómito durante la sedación"],
  streetPrice="~$20–$60 por gramo; viales $30–$100",
  legalStatus="Solo con receta, Lista III (EE. UU.); Clase B (RU)"),
 "oxycodone":dict(schedule="Lista II (EE. UU.)",
  appearance="Tabletas azules de 30 mg de liberación inmediata ('Roxy', '30s', 'blues')",
  effects=["Euforia, alivio del dolor, energía y luego sedación"],
  risks=["Altamente adictiva — puente hacia la heroína y el fentanilo","Las 'azules' falsificadas casi siempre son fentanilo"],
  overdoseSigns=["Pupilas puntiformes","Respiración lenta","Labios azules"],
  streetPrice="~$15–$40 por tableta de 30 mg (desviada); falsificadas $3–$15",
  legalStatus="Solo con receta, Lista II; delito sin receta"),
 "adderall":dict(schedule="Lista II (EE. UU.)",
  appearance="Tabletas redondas azules/durazno (5–30 mg, marca 'AD')",
  effects=["Concentración, vigilia, euforia leve"],
  risks=["Dependencia y tolerancia","Carga cardiovascular","Las falsificadas contienen metanfetamina o cafeína"],
  overdoseSigns=["Palpitaciones, dolor en el pecho","Pánico, agresión","Sobrecalentamiento"],
  streetPrice="~$3–$15 por tableta de 30 mg (desviada)",
  legalStatus="Solo con receta, Lista II; delito sin receta"),
}

# ---- BATCH 2 (2026-09-17): youth-relevant + high-search compounds ----
ES_DRUGS.update({
 "weed": dict(schedule="Lista I (EE. UU. federal) — legal o despenalizada en muchos estados y países",
  appearance="Cogollos verdes/marrones secos; hachís; aceites y ceras (concentrados); comestibles; cartuchos de vapeo",
  effects=["Relajación, euforia ('colocón')", "Sentidos alterados, percepción del tiempo", "Aumento del apetito ('monchis')"],
  risks=["Ansiedad, ataques de pánico, paranoia — sobre todo con cepas altas en THC y concentrados", "Memoria, coordinación y conducción afectadas durante horas", "Dependencia con uso diario intenso (~10–30% de usuarios)", "Los concentrados potentes se vinculan a episodios psicóticos", "La marihuana del mercado ilegal puede tener moho o estar adulterada"],
  overdoseSigns=["No hay sobredosis mortal conocida — el cannabis solo no detiene la respiración", "Ataque de pánico severo, paranoia, corazón acelerado", "Síndrome de hiperémesis cannabinoide: vómitos incontrolables", "Desmayo o sedación extrema mezclado con alcohol u otras drogas"],
  streetPrice="~$10–$20 por gramo (EE. UU.); mucho más barato donde es legal",
  legalStatus="Varía mucho: legal (Canadá, Uruguay, muchos estados de EE. UU.), despenalizada o ilegal — verifica la ley local. El cannabis natural NO es lo mismo que los cannabinoides sintéticos ('Spice')."),
 "poppers": dict(schedule="Legal poseer (RU, gran parte de la UE); amilo de uso médico solo con receta en EE. UU.",
  appearance="Botellitas ámbar/azules de 10–30 mL de líquido volátil; se vende como 'ambientador' o 'limpiador de cuero'",
  effects=["Efusión de calor y euforia instantánea (10–30 segundos)", "Relajación muscular", "Mayor sensibilidad en la piel; desinhibición"],
  risks=["Caída MORTAL de la presión arterial mezclado con Viagra/Cialis — la combinación clásica mortal", "Metahemoglobinemia con uso repetido — la sangre deja de transportar oxígeno (labios azules)", "Quemaduras en piel, nariz y boca", "Máculopatía por poppers — daño visual documentado, a veces permanente", "Mareo, desmayos, náuseas"],
  overdoseSigns=["Labios y piel azulados/grisáceos", "Desmayo, mareo extremo", "Corazón acelerado y luego colapso", "Dificultad para respirar"],
  streetPrice="~$5–$20 por botella",
  legalStatus="Poseer es legal en muchos países; la venta para consumo humano está prohibida en algunos lugares — se vende como 'limpiador'."),
 "nitrous-oxide": dict(schedule="Legal poseer; la venta como droga psicoactiva está prohibida en el Reino Unido (2023)",
  appearance="Cargadores plateados de 8g, grandes tanques de 500–640g ('Galaxy Gas'), globos",
  effects=["Euforia de 30–60 segundos, risas, sensación de flotar", "Disociación, distorsión del sonido", "Entumecimiento breve"],
  risks=["DESTRUYE LA VITAMINA B12 — la señal de daño: entumecimiento, hormigueo, debilidad y, en usuarios intensos, DAÑO NERVIOSO PERMANENTE ('pie caído', imposibilidad de caminar)", "Falta de oxígeno — el gas desplaza el aire; inconsciencia y muerte", "Quemaduras por frío en labios y pulmones", "Dependencia psicológica", "La ola Galaxy Gas: tanques baratos con sabores dirigidos a jóvenes"],
  overdoseSigns=["Labios/azulados (falta de oxígeno)", "Inconsciente, no se despierta", "Convulsiones", "Dolor en el pecho, latidos irregulares"],
  streetPrice="~$1–$3 por cargador; tanques Galaxy Gas $25–$60",
  legalStatus="Producto legal; prohibida la venta como psicoactivo en el RU (2023); varios estados de EE. UU. restringen sabores a menores."),
 "tianeptine": dict(schedule="No federalmente listada (EE. UU.) — advertencias de la FDA; prohibida en varios estados",
  appearance="Cápsulas o 'shots' vendidos en gasolineras y vape shops como 'suplemento' (ZaZa, Tiana, Neptune's Fix)",
  effects=["Euforia tipo opioide, calor, relajación a dosis altas"],
  risks=["'La heroína de la gasolinera' — produce dependencia y abstinencia TAN severa como la oxicodona", "FDA: vinculado a coma, depresión respiratoria, convulsiones y MUERTE", "No aparece en pruebas estándar de drogas", "Contaminación: el Neptune's Fix de 2024 llevaba cannabinoides sintéticos", "Se vende abiertamente a adolescentes — sin receta ni control"],
  overdoseSigns=["Depresión respiratoria (respiración lenta o detenida)", "Coma", "Convulsiones", "Pupilas puntiformes, labios azules"],
  streetPrice="~$15–$40 por botella",
  legalStatus="No listada federalmente (aún); prohibida en Alabama, Tennessee, Georgia, Ohio, Florida y otros estados."),
 "kratom": dict(schedule="No listada federalmente (EE. UU.); ilegal en 6+ estados; prohibida en varios países",
  appearance="Polvo verde, cápsulas, extractos y 'shots' en smoke shops",
  effects=["Dosis bajas: energía y concentración estimulantes", "Dosis altas: sedación y alivio del dolor tipo opioide"],
  risks=["Dependencia y abstinencia tipo opioide (insomnio, dolores, irritabilidad)", "La FDA lo vincula a convulsiones, daño hepático y alucinaciones", "Contaminación por salmonella — brotes documentados", "La naloxona SÍ revierte la sobredosis de kratom (actúa en receptores opioides)"],
  overdoseSigns=["Convulsiones", "Depresión respiratoria (dosis altas)", "Signos de daño hepático (ictericia, orina oscura)", "Alucinaciones, confusión"],
  streetPrice="~$10–$30 por onza de polvo; shots $8–$15",
  legalStatus="No listada federalmente; ilegal en Alabama, Arkansas, Indiana, Rhode Island, Vermont y Wisconsin; la FDA desaconseja su uso."),
 "suboxone": dict(schedule="Lista III (EE. UU.)",
  appearance="Películas sublinguales naranjas (8/2 mg) o tabletas hexagonales",
  effects=["Detiene la abstinencia y los antojos; efecto 'techo' limita la depresión respiratoria"],
  risks=["Dependencia (más leve que los opioides completos)", "Precipita abstinencia si se toma demasiado pronto tras otros opioides", "Sobredosis rara sola; sedación + depresión respiratoria mezclado con benzos o alcohol"],
  overdoseSigns=["Raro en solitario; sedación y respiración lenta en combinación"],
  streetPrice="~$10–$25 por película de 8 mg (desviada)",
  legalStatus="Solo con receta, Lista III; amplio uso en tratamiento."),
 "diazepam-drug": dict(schedule="Lista IV (EE. UU.)",
  appearance="Tabletas de 2–10 mg (amarillas/azules/blancas); viales inyectables",
  effects=["Calma, relajación muscular, antiansiedad, sedación"],
  risks=["Dependencia en 2–4 semanas de uso diario", "Abstinencia peligrosa (convulsiones) — nunca dejar de golpe", "Mezclado con opioides o alcohol puede detener la respiración", "Las tabletas falsificadas son comunes"],
  overdoseSigns=["Somnolencia extrema", "Confusión", "Respiración lenta (sobre todo con otros depresores)"],
  streetPrice="~$1–$10 por tableta de 10 mg; falsificadas comunes",
  legalStatus="Solo con receta, Lista IV; delito sin receta."),
 "clonazepam": dict(schedule="Lista IV (EE. UU.)",
  appearance="Tabletas blancas/naranjas ranuradas (0.5–2 mg); Rivotril común en UE y Latinoamérica",
  effects=["Calma de larga duración, antiansiedad, anticonvulsivo"],
  risks=["Semivida larga — la dependencia crece en silencio", "La abstinencia puede durar meses", "Sedación extrema y caídas en adultos mayores"],
  overdoseSigns=["Somnolencia extrema", "Respiración lenta en mezclas", "Falta de coordinación"],
  streetPrice="~$1–$5 por tableta de 2 mg",
  legalStatus="Solo con receta, Lista IV; delito sin receta."),
 "oxycontin": dict(schedule="Lista II (EE. UU.)",
  appearance="Tabletas de liberación prolongada (OC); reformulada en 2010 para disuadir el triturado",
  effects=["Alivio prolongado del dolor y euforia"],
  risks=["Dependencia; las formulaciones pre-2010 aún se trituran en el mercado ilegal", "Sobredosis por liberación completa si se tritura o disuelve"],
  overdoseSigns=["Pupilas puntiformes", "Depresión respiratoria", "Sedación"],
  streetPrice="~$20–$80 por tableta de 80 mg (desviada)",
  legalStatus="Solo con receta, Lista II; delito sin receta."),
 "sildenafil": dict(schedule="Solo con receta — no es droga controlada",
  appearance="Tabletas azules de 25/50/100 mg; todo color y forma en el mercado gris; geles orales",
  effects=["Facilita la erección con excitación (inhibidor de la PDE5, 30–60 min)", "Dura ~4–5 horas"],
  risks=["LA clase de medicamentos más falsificada del mundo — las pastillas falsas son un canal de fentanilo en algunas regiones", "Caída peligrosa de la presión con nitratos (medicamentos cardiacos) — combinación potencialmente fatal", "Priapismo (erección >4 horas) = emergencia médica", "Cambios de visión (tono azulado)"],
  overdoseSigns=["Erección prolongada >4 horas — emergencia", "Mareo severo, desmayo (caída de presión)", "Pérdida de visión o audición — rara, urgente"],
  streetPrice="~$1–$15 por tableta (genéricos grises vs farmacia)",
  legalStatus="Solo con receta; enorme comercio de falsificaciones y genéricos grises."),
 "xtc-pills": dict(schedule="Lista I (EE. UU.)",
  appearance="Tabletas prensadas de todos los colores y logos (Superman, Tesla, calaveras)",
  effects=["Euforia, empatía, energía durante 4–6 horas"],
  risks=["Píldoras de dosis altas (200–300+ mg) causan toxicidad severa", "Las copias con PMA/PMMA matan — tardan en hacer efecto y llevan a re-dosificar", "Sobrecalentamiento + deshidratación (o intoxicación por agua)"],
  overdoseSigns=["Temperatura corporal >40°C / 104°F", "Convulsiones, rigidez muscular", "Confusión, alucinaciones"],
  streetPrice="~$10–$40 por píldora",
  legalStatus="Lista I (EE. UU.); Clase A (RU); controlada en todas las regiones."),
 "thc-edibles": dict(schedule="Sigue la ley local del cannabis; mercado sin regular donde es ilegal",
  appearance="Gominolas, chocolates, repostería, bebidas; dosis etiquetadas (5–10 mg) en mercado legal, sin etiquetar en el ilegal",
  effects=["Inicio lento (30 min–2 h), duración larga (4–8 h)", "Colocón más corporal que fumando"],
  risks=["LA sobredosis clásica: la gente toma más cuando 'no hace efecto' — el retraso de 2–3 h apila dosis", "Niños y mascotas que comen gominolas — picos de llamadas a centros de toxicología", "Contenido de THC sin etiquetar en el mercado negro"],
  overdoseSigns=["Sin sobredosis mortal", "Ansiedad extrema, paranoia, alucinaciones", "Vómitos, incapacidad para mantenerse de pie"],
  streetPrice="Mercado legal: $2–$5 por dosis de 10 mg; gominolas grises $5–$20",
  legalStatus="Legal donde el cannabis es legal con normas de etiquetado; ilegal en otros lugares — pero disponible en todas partes."),
 "purple-drank": dict(schedule="Lista V (jarabe de codeína, solo con receta)",
  appearance="Jarabe púrpura/rosa (codeína + prometazina) mezclado con refresco y dulces",
  effects=["Euforia sedante, percepción enlentecida, cuerpo 'inclinado'"],
  risks=["DEPRESIÓN RESPIRATORIA — la mezcla frena la respiración; muertes documentadas de artistas", "La prometazina potencia el peligro respiratorio de la codeína", "Conducir con lean es mortal", "La cultura musical lo glamuriza para jóvenes"],
  overdoseSigns=["Respiración lenta o superficial", "Labios azules, inconsciente", "Pupilas puntiformes", "Convulsiones"],
  streetPrice="Botella con receta desviada $50–$300; por taza $30–$100",
  legalStatus="Solo con receta; posesión ilegal sin ella."),
 "ghb": dict(schedule="Lista I/III (EE. UU. — el GHB ilícito es Lista I)",
  appearance="Líquido transparente con sabor salado/jabonoso; polvo blanco; cápsulas",
  effects=["Euforia, desinhibición, sociabilidad; sueño a dosis altas"],
  risks=["La curva de dosis es de navaja — 1 mL de más = coma", "El uso diario crea la abstinencia MÁS peligrosa de cualquier droga recreativa — suspender de golpe puede ser letal (convulsiones, delirio)", "Vinculado a agresiones con drogas facilitadas"],
  overdoseSigns=["Sueño profundo, no se despierta", "Vómitos mientras está inconsciente", "Respiración lenta e irregular"],
  streetPrice="~$5–$20 por dosis",
  legalStatus="Lista I (ilícito) en EE. UU.; ilegal sin receta en todas las regiones."),
})
