# Spanish (es) translations — batch 1: home hero, hotlines, top-10 drug profiles.
# Fields not translated here stay English on /es/ pages until batch 2.

ES_CATS = {
 "opioids":"Opioides","stimulants":"Estimulantes","benzodiazepines":"Benzodiacepinas",
 "sedatives":"Sedantes e hipnóticos","depressants":"GHB / GBL","dissociatives":"Disociativos",
 "empathogens":"Empatógenos","psychedelics":"Psicodélicos","cannabinoids":"Cannabinoides sintéticos",
 "performance":"Rendimiento y farmacia gris","hazardous":"Sustancias peligrosas"}

ES_HOME = {
 "kicker":"Biblioteca de reducción de riesgos · 92 sustancias · 5 regiones",
 "h1":"Conoce la droga.<br>Conoce el <span class=\"mark\">riesgo</span>.<br>Conoce la salida.",
 "lede":"plugreports es un directorio visual de drogas de calle, adulterantes, líneas de ayuda, incautaciones y ayuda verificada — para que cualquier persona encuentre información clara, rápida y que salva vidas.",
 "btn1":"Ayuda ahora","btn2":"Explorar la biblioteca","btn3":"Dejarlo, día a día",
 "st1":"perfiles de drogas","st2":"categorías","st3":"líneas verificadas","st4":"guías y cronogramas",
 "hl_kicker":"Ayuda","hl_h2":"Líneas de ayuda por región",
 "hl_p":"Números verificados en EE. UU., Canadá, Europa, Australia y África.",
 "hl_btn":"Directorio completo de líneas de ayuda"}

ES_REGIONS = {"USA":"EE. UU.","Canada":"Canadá","Europe":"Europa","Australia":"Australia","Africa":"África"}

ES_HOTLINES = {
 "USA":[
  ["Emergencias — sobredosis, llama siempre","Bomberos/EMS llevan naloxona; las leyes del buen samaritano protegen a quien llama en la mayoría de estados."],
  ["Línea nacional SAMHSA","Gratuita, 24/7, referencias confidenciales de tratamiento (español/inglés)."],
  ["Línea 988 de suicidio y crisis","Llama o envía un mensaje al 988 — apoyo en crisis 24/7."],
  ["Control de envenenamiento","Evaluación 24/7 de envenenamientos y sobredosis."],
  ["Never Use Alone","Llama mientras consumes — un operador permanece en la línea y avisa si pierdes el conocimiento."],
  ["Línea de texto en crisis","Envía HOME al 741741 — apoyo gratuito 24/7 por mensaje."]],
 "Canada":[
  ["Emergencias","Peligro inmediato para la vida — llama primero siempre."],
  ["Línea de crisis 9-8-8","Llama o envía un mensaje al 9-8-8, 24/7."],
  ["ConnexOntario","Línea de ayuda para consumo de sustancias, 24/7, gratuita."],
  ["Teléfono de la Ayuda Infantil","Apoyo para jóvenes, llama o envía un mensaje."]],
 "Europe":[
  ["Número de emergencia de la UE","Funciona en todos los países miembros, gratuito, 24/7."],
  ["FRANK (Reino Unido)","Información y consejo sobre drogas, 24/7, confidencial."],
  ["Drogues Info Service (Francia)","Información gratuita y anónima sobre drogas."],
  ["Línea federal de drogas (Alemania)","Línea nacional de adicciones y drogas."],
  ["Jellinek (Países Bajos)","Línea de asesoría en adicciones."]],
 "Australia":[
  ["Emergencias","Ambulancia, policía, bomberos."],
  ["Línea nacional de alcohol y otras drogas","Consejería y referencias gratuitas 24/7."],
  ["Lifeline","Apoyo en crisis 24/7 y prevención del suicidio."],
  ["DirectLine (Victoria)","Consejería gratuita 24/7 y referencias."]],
 "Africa":[
  ["SADAG (Sudáfrica)","Línea de salud mental con apoyo para consumo de sustancias."],
  ["SANCA (Sudáfrica)","Red de referencias de tratamiento en provincias sudafricanas."],
  ["Línea NACADA (Kenia)","Línea gratuita del gobierno para el control de drogas."],
  ["Emergencias del hospital más cercano","Donde no hay líneas dedicadas, los hospitales son la vía más rápida."]]}

ES_DRUGS = {
 "fentanyl":dict(schedule="Lista II (EE. UU., uso farmacéutico)",
  appearance="Polvo blanco, pastillas prensadas, oxicodona falsificada — a menudo invisible cuando se mezcla con otras drogas",
  effects=["Euforia extrema","Somnolencia","Alivio del dolor"],
  risks=["Depresión respiratoria","Adicción en días","2 mg (~unos pocos granos) pueden ser fatales"],
  overdoseSigns=["Pupilas puntiformes (miosis)","Respiración lenta o detenida","Labios azulados, cuerpo flácido"],
  streetPrice="~$20–$40 por píldora falsificada",
  legalStatus="Delito grave en todos los estados de EE. UU.; los análogos se persiguen bajo la Ley Federal de Análogos"),
 "heroin":dict(schedule="Lista I (EE. UU.)",
  appearance="Polvo blanco/marrón ('base', 'sugar brown'); 'black tar' (México)",
  effects=["Euforia intensa ('rush')","Calor, pesadez en las extremidades","Alivio del dolor, somnolencia ('nodding')"],
  risks=["Altamente adictiva — dependencia en semanas","Sobredosis: la respiración se detiene","Potencia desconocida + contaminación con fentanilo"],
  overdoseSigns=["Inconsciente, pupilas puntiformes","Respiración lenta (<8/min) o ronquidos","Labios y uñas azulados/grisáceos"],
  streetPrice="~$10–$40 por bolsa; varía según la región",
  legalStatus="Ilegal — Lista I en EE. UU.; Clase A (RU); controlada en todas las regiones"),
 "cocaine":dict(schedule="Lista II (EE. UU.)",
  appearance="Polvo cristalino blanco (clorhidrato) o 'base'/crack; 'fishscale' = alta pureza",
  effects=["Euforia, confianza, energía","Anestesia local (adormecimiento)","Suprime el apetito y el sueño"],
  risks=["Infarto o derrame cerebral incluso en jóvenes","Adicción severa — ciclo de ansias","Adulterantes: levamisol (carne podrida), fentanilo (sobredosis)"],
  overdoseSigns=["Dolor en el pecho, palpitaciones","Convulsiones","Agitación extrema, sobrecalentamiento"],
  streetPrice="~$60–$120 por gramo (EE. UU.); varía mucho",
  legalStatus="Lista II (EE. UU.); Clase A (RU); ilegal sin fines médicos"),
 "methamphetamine":dict(schedule="Lista II (EE. UU.)",
  appearance="Cristales blancos/transparentes ('ice'), polvo o pastillas",
  effects=["Euforia intensa, energía y concentración 6–12 h","Suprime apetito y sueño","Confianza, hipersexualidad"],
  risks=["Adicción — una de las drogas más adictivas que existen","'Boca de met', heridas en la piel, psicosis","Sobredosis: derrame cerebral, paro cardíaco, sobrecalentamiento"],
  overdoseSigns=["Dolor en el pecho, arritmia","Agitación extrema, paranoia","Fiebre alta, convulsiones"],
  streetPrice="~$20–$100 por gramo (EE. UU.)",
  legalStatus="Lista II (EE. UU.); Clase A (RU); ilegal sin receta"),
 "mdma":dict(schedule="Lista I (EE. UU.)",
  appearance="Cristales o polvo blanco ('Molly'); pastillas prensadas con logos ('XTC')",
  effects=["Euforia, empatía, cercanía emocional","Energía, sentidos amplificados","La música y el ambiente se sienten mejores"],
  risks=["Sobrecalentamiento + deshidratación (o intoxicación por agua)","Bajón por agotamiento de serotonina","Las pastillas a menudo contienen PMA/PMMA (mortales)"],
  overdoseSigns=["Sobrecalentamiento, confusión","Palpitaciones, convulsiones","Bruxismo, alucinaciones"],
  streetPrice="~$10–$40 por pastilla; ~$30–$80 por gramo",
  legalStatus="Lista I (EE. UU.); Clase A (RU); controlada en todas las regiones"),
 "xylazine":dict(schedule="No es droga controlada — anestésico veterinario, adulterante",
  appearance="Sin forma propia en la calle — se encuentra mezclado con fentanilo/hheroína (polvo blanco/beige) o en pastillas",
  effects=["Sedación intensa, respiración lenta","Pérdida de conocimiento por horas","Heridas cutáneas graves (escaras)"],
  risks=["No es opioide — la naloxona NO lo revierte, aunque deja de respirar","Heridas que pudren la carne y llevan a amputación","Abstinencia doble encima de la de opioides"],
  overdoseSigns=["Inconsciente con respiración lenta","Piel azul-gris","Hipotensión severa (presión muy baja)"],
  streetPrice="Se vende como parte de bolsas de fentanilo/hheroína (~$10–$40)",
  legalStatus="Anestésico veterinario de uso recetado; uso humano ilegal"),
 "alprazolam":dict(schedule="Lista IV (EE. UU.)",
  appearance="Barras blancas de 2 mg (largas, ranuradas); tabletas azules/blancas/amarillas según la dosis",
  effects=["Alivio rápido de la ansiedad","Calma sedante","Relajación muscular"],
  risks=["Dependencia en semanas; abstinencia brutal (riesgo de convulsiones)","Las barras falsificadas contienen fentanilo o bromazolam","Amnesia y conductas riesgosas"],
  overdoseSigns=["Somnolencia extrema","Habla arrastrada","Respiración lenta — mortal con opioides o alcohol"],
  streetPrice="~$2–$10 por barra de 2 mg; falsificadas ~$1–$5",
  legalStatus="Solo con receta, Lista IV; delito sin receta"),
 "ketamine":dict(schedule="Lista III (EE. UU.)",
  appearance="Polvo cristalino blanco; viales de líquido claro (Ketalar)",
  effects=["Disociación (fuera del cuerpo), euforia","Alivio del dolor","Sedante a dosis altas"],
  risks=["Daño vesical (cistitis por ketamina) con uso regular","'K-holes' y accidentes bajo los efectos","Dependencia con uso intensivo"],
  overdoseSigns=["Inconsciente con los ojos abiertos","Respiración lenta (raramente mortal por sí sola)","Vómito durante la sedación"],
  streetPrice="~$20–$60 por gramo; viales $30–$100",
  legalStatus="Solo con receta, Lista III (EE. UU.); Clase B (RU)"),
 "oxycodone":dict(schedule="Lista II (EE. UU.)",
  appearance="Tabletas azules de 30 mg de liberación inmediata ('Roxy', '30s', 'blues')",
  effects=["Euforia, alivio del dolor, energía y luego sedación"],
  risks=["Altamente adictiva — puente hacia la heroína y el fentanilo","Las 'azules' falsificadas casi siempre son fentanilo"],
  overdoseSigns=["Pupilas puntiformes","Respiración lenta","Labios azules"],
  streetPrice="~$15–$40 por tableta de 30 mg (desviada); falsificadas $3–$15",
  legalStatus="Solo con receta, Lista II; delito sin receta"),
 "adderall":dict(schedule="Lista II (EE. UU.)",
  appearance="Tabletas redondas azules/durazno (5–30 mg, marca 'AD')",
  effects=["Concentración, vigilia, euforia leve"],
  risks=["Dependencia y tolerancia","Carga cardiovascular","Las falsificadas contienen metanfetamina o cafeína"],
  overdoseSigns=["Palpitaciones, dolor en el pecho","Pánico, agresión","Sobrecalentamiento"],
  streetPrice="~$3–$15 por tableta de 30 mg (desviada)",
  legalStatus="Solo con receta, Lista II; delito sin receta"),
}
