# Nicotine vaping city rankings by region — sourced, hedged, citable.
# Method note carried on every page: no country measures vaping per city
# directly. Rankings combine the best available proxies per region (national
# surveys, market data, seizure figures, retail density). They are
# directional, not precise league tables.

VAPE_CITY_PAGES = [
 dict(slug="vape-cities-usa", region="United States", title="Top 10 US cities with the most vaping",
  updated="October 2026", read="8 min",
  desc="The US cities where vaping is most common — ranked from CDC BRFSS state surveys, FDA enforcement data and market reports, from Oklahoma City's top-rate status to the Appalachian vape belt.",
  stats=[("6.7%","Oklahoma's adult vaping rate — the highest ever measured in CDC BRFSS state data"),("1.6M","US middle- and high-school students still reporting current e-cigarette use (FDA/CDC NYTS 2024) — down from a 5.4M peak in 2019"),("#1","e-cigarettes have been the most-used tobacco product among US teens every year since 2014")],
  intro="No US agency measures vaping city by city, so this ranking triangulates three proxies: CDC BRFSS state-level adult vaping rates (which consistently put Oklahoma, West Virginia, Kentucky, Tennessee, Arkansas, Louisiana, Ohio, Nevada, Wyoming and Arizona at the top), FDA/CDC youth survey patterns, and retail-plus-enforcement data. The map they draw is clear: US vaping tracks the old smoking belt — Appalachia and the South — plus Oklahoma's outlier market. City positions within states are estimated from metro populations and retail density; treat the whole list as a band.",
  cities=[
   ("1","Oklahoma City, OK","Oklahoma recorded the highest adult e-cigarette rate ever measured in BRFSS state data (6.7% current use, 7.9% among men) — and OKC, with weak retail restrictions and cheap disposables, is the market's center of gravity."),
   ("2","Tulsa, OK","Shares Oklahoma's nation-leading numbers; state survey breakdowns put Tulsa's metro essentially level with OKC."),
   ("3","Charleston / Huntington, WV","West Virginia is America's smoking capital (roughly one in four adults in older BRFSS waves) and vaping followed the same map — the state's young-adult vaping rates are among the nation's highest, concentrated in its two small metros."),
   ("4","Louisville / Lexington, KY","Kentucky pairs top-tier smoking with top-tier vaping in federal survey data, and its two cities anchor the state's market. Louisville's vape-shop density is among the highest in the South."),
   ("5","Nashville / Memphis, TN","Tennessee appears in the top vaping tier of every BRFSS wave, and Nashville's boomtown demographics (young, nightlife-heavy) amplify it."),
   ("6","New Orleans, LA","Louisiana rounds out the Southern top tier; New Orleans' 24-hour hospitality economy drives both cigarette and vape volume well above state averages."),
   ("7","Indianapolis, IN","Indiana sits in the second-highest vaping tier nationally; Indianapolis is the Midwest's biggest vape market after Columbus, with high youth uptake in state surveys."),
   ("8","Columbus, OH","Ohio posts some of the highest female adult vaping rates in BRFSS data; Columbus's huge student population (Ohio State) concentrates the state's young-adult use."),
   ("9","Las Vegas, NV","Nevada's top-tier vaping rate meets the tourist economy — the Strip's vape and smoke shops do volumes that skew the state's per-capita numbers upward."),
   ("10","Phoenix / Tucson, AZ","Arizona holds a consistent spot in the top ten states for adult vaping; Phoenix's size makes it the Southwest's largest vape market."),
  ],
  notes="The paradox cities: San Francisco — birthplace of Juul — banned e-cigarette retail sales in 2019, and New York, Chicago and Boston run flavor bans, yet their illicit and border markets keep big-city use alive. The national story is decline among teens (from 5.4 million users in 2019 to ~1.6 million in 2024) but persistence among young adults, driven by flavored disposables the FDA has largely failed to keep off shelves.",
  method="Methodology: CDC BRFSS state adult e-cigarette prevalence (most recent comparable waves), FDA/CDC National Youth Tobacco Survey, state health-department surveys, and FDA enforcement/retail data. No city-level use survey exists; city ranks within top states are estimated. Rankings are directional.",
  sources=["CDC BRFSS state e-cigarette prevalence","FDA/CDC National Youth Tobacco Survey 2024","CDC state tobacco-use pattern studies","Truth Initiative market analyses"]),

 dict(slug="vape-cities-europe", region="Europe", title="Top 10 European cities with the most vaping",
  updated="October 2026", read="8 min",
  desc="Europe's vaping capitals — Britain vapes more than anyone else in Europe, with London, Manchester and Glasgow leading 5.5 million UK vapers, per ASH and national survey data.",
  stats=[("5.5M","adult vapers in Great Britain — about 10.3% of adults (ASH, 2026)"),("June 2025","the UK banned single-use disposable vapes — Europe's biggest market intervention so far"),("43.6% → 29.4%","collapse in the disposable share of UK adult vaping between Jan 2024 and Jan 2025, even before the ban")],
  intro="Europe's vaping map is lopsided: the United Kingdom embraced e-cigarettes as a smoking-cessation tool and built the continent's biggest market by far — 5.5 million vapers, roughly one in ten adults — while most of the EU regulates vaping as a consumer product with tighter nicotine caps (20 mg/mL under the TPD) and, increasingly, flavor and disposable bans. No European agency measures vaping per city, so this ranking combines ASH's GB surveys, national tobacco surveys, and market data. UK cities dominate by volume; continental entries reflect each country's survey leaders. Treat positions as a band.",
  cities=[
   ("1","London, UK","Europe's largest vape market in absolute terms: London's share of Britain's 5.5 million vapers, thousands of dedicated vape shops, and the country's most visible disposable-litter problem before the June 2025 ban."),
   ("2","Manchester, UK","The Northwest consistently posts some of England's highest vaping (and smoking) rates in ASH and ONS breakdowns — Manchester's young demographics amplify it."),
   ("3","Birmingham, UK","Britain's second city tracks Manchester closely; the Midlands' above-average smoking rates have converted into above-average vaping as smokers switch."),
   ("4","Glasgow, UK","Scotland's largest city: Scottish health surveys show some of the UK's highest smoking and vaping rates, and Glasgow's vape-shop density is the highest in Scotland."),
   ("5","Liverpool, UK","Merseyside rounds out England's high-prevalence northwest cluster; trading-standards raids on illicit vapes here are among the most frequent in the country."),
   ("6","Paris, FR","France counts several million vapers (OFDT surveys put experimentation near half of young adults), and Paris is the continent's largest non-UK market — though France banned disposables in February 2025."),
   ("7","Berlin, DE","Germany's vape market is the EU's second largest; Berlin's nightlife districts drove the disposable boom, and German youth surveys showed some of Europe's fastest rises pre-2024."),
   ("8","Prague, CZ","Czechia's liberal nicotine market (plus a booming nicotine-pouch scene) makes Prague Central Europe's vaping capital by survey rates."),
   ("9","Warsaw, PL","Poland's large market skews young — Polish teen vaping rates have ranked among the EU's highest in ESPAD school surveys — and Warsaw concentrates it."),
   ("10","Madrid, ES","Spain's market grew fast on disposables among teenagers (a major policy flashpoint in 2023–24), with Madrid and Barcelona as the twin hubs."),
  ],
  notes="Just outside: Brussels (Belgium banned disposables in January 2025 — a first in the EU), Amsterdam, Rome and Stockholm (where snus and nicotine pouches suppress vaping). The continental trend is restriction — disposable bans in Belgium, France and the UK, flavor limits spreading — while Britain alone still officially promotes vaping as a quit-smoking tool, even as it tightens youth access.",
  method="Methodology: ASH Smokefree GB adult and youth surveys (2024–2026), ONS adult smoking/vaping breakdowns, OFDT (France), national tobacco surveys, and market reporting. No city-level measurement exists; city ranks within countries are estimated from regional survey patterns and retail data. Rankings are directional.",
  sources=["ASH — use of e-cigarettes among adults in Great Britain (2025/2026)","ONS adult smoking and vaping statistics","OFDT (French Monitoring Centre for Drugs and Drug Addiction)","ESPAD European school survey"]),

 dict(slug="vape-cities-canada", region="Canada", title="Top 10 Canadian cities with the most vaping",
  updated="October 2026", read="7 min",
  desc="Where Canadians vape the most — youth rates near 30% in senior high-school grades make Canada's vaping map a young one, per Health Canada and StatCan surveys.",
  stats=[("~29%","of Canadian students in grades 10–12 reported past-30-day vaping in national student surveys"),("21.3%","of Canadians aged 15–17 vaped in the past 30 days — nearly 4× the rate of 12–14-year-olds (StatCan)"),("20 mg/mL","Canada's national nicotine cap for vapes since 2021 — with flavor bans layered on by several provinces")],
  intro="Canada publishes no city-level vaping data, but its provincial and student surveys draw a recognizable map: vaping is a young person's habit everywhere, highest where youth populations and lax retail intersect, and shaped provincially by flavor bans (Quebec, Nova Scotia, PEI and others ban most flavors; Ontario and Alberta largely don't). This ranking combines Health Canada's Canadian Student Tobacco, Alcohol and Drugs Survey, StatCan health surveys, and provincial retail patterns. Every city position is an estimate — read the list as 'Canada's biggest, youngest vape markets'.",
  cities=[
   ("1","Toronto, ON","Canada's largest vape market in absolute terms: Ontario has no provincial flavor ban, Toronto's convenience stores and vape shops number in the thousands, and the metro holds the country's biggest population of 15–29-year-olds — the peak vaping demographic."),
   ("2","Montreal, QC","Quebec's 2023 flavor ban pushed its vape market into tobacco-flavored products and a thriving illicit flavored trade — Montreal's student population (four universities) keeps volumes high regardless."),
   ("3","Vancouver, BC","BC taxes vapes at 20% and caps retail, but Vancouver's young, dense core sustains one of the country's biggest per-capita markets — and its harm-reduction culture treats vaping as the lesser evil."),
   ("4","Calgary, AB","Alberta has among the fewest restrictions in Canada (no flavor ban, no provincial vape tax until the federal coordination), and Calgary's young median age makes it the West's growth market."),
   ("5","Ottawa, ON","The capital's huge student and young-civil-service population puts it consistently near the top of Ontario's regional survey breakdowns."),
   ("6","Halifax, NS","Nova Scotia was the first province to ban flavors (2020) — yet Halifax's five universities keep it Atlantic Canada's vaping capital, with survey rates that stayed high post-ban."),
   ("7","Edmonton, AB","Shares Alberta's permissive market; Edmonton and Calgary are statistically inseparable in provincial surveys."),
   ("8","Winnipeg, MB","Manitoba's surveys show above-average youth vaping; Winnipeg concentrates the province's young population and its retail."),
   ("9","Victoria, BC","A student-and-service-economy city in a high-tax province — mid-table provincially but young-demographic driven, like Halifax."),
   ("10","Saskatoon / Regina, SK","Saskatchewan posts some of the highest youth vaping rates in the student survey's provincial tables; its two small metros split the market."),
  ],
  notes="The national story: Canada capped nicotine at 20 mg/mL (2021) and added a federal excise tax (2022, doubled in 2024), while flavor bans spread province by province — but youth past-30-day vaping, after falling from its 2019 peak, has plateaued rather than collapsed. Health Canada frames vaping as a cessation tool for adults and a failure for teens; the data shows both at once.",
  method="Methodology: Health Canada Canadian Student Tobacco, Alcohol and Drugs Survey, StatCan Canadian Community Health Survey vaping modules, provincial flavor-ban and tax policy tracking. No city-level measurement exists; city ranks are estimated from provincial data and demographics. Rankings are directional.",
  sources=["Health Canada — Canadian Student Tobacco, Alcohol and Drugs Survey","Statistics Canada — correlates of vaping among adolescents","Provincial vaping policy and tax records","StatCan Canadian Community Health Survey"]),

 dict(slug="vape-cities-australia", region="Australia", title="Top 10 Australian cities with the most vaping",
  updated="October 2026", read="7 min",
  desc="Vaping in Australia — a prescription-only legal market drowned by a billion-dollar black market, from Sydney's vape-shop raids to the Gold Coast's teen crisis, per ABF seizure data.",
  stats=[("13.2M","illicit vapes seized at the Australian border in the 2025–26 financial year — up 112% on the year before (ABF)"),("A$1B+","street value of the 20 million-plus illegal vapes seized since the national crackdown began"),("Rx-only","Australia is the only Western country where nicotine vapes are legally a pharmacy-only, therapeutic product")],
  intro="Australia is the world's strangest vape market: since October 2021, buying a nicotine vape legally has required a doctor's prescription, and since 2024 vapes are supposed to be sold only in pharmacies as quitting aids — plain packaging, three flavors. In practice, a black market worth billions flooded the country with flavored disposables sold openly in convenience stores, and enforcement statistics now tell the story: 13.2 million vapes seized at the border in 2025–26 alone. No official city-level use data exists, so this ranking combines seizure geography, state health surveys and market reporting. Treat it as a map of where the illicit market is biggest.",
  cities=[
   ("1","Sydney, NSW","The epicenter of the black market: NSW health surveys found the country's highest teen vaping rates, Sydney's convenience-store vape trade operated near-openly for years, and the state now runs the most retail prosecutions — plus the most firebombings, as organized crime fights over the trade."),
   ("2","Melbourne, VIC","Victoria's illicit-tobacco and vape war is the country's most violent — dozens of arson attacks on shops since 2023 — because Melbourne is the second-biggest market and the first to get a state licensing scheme."),
   ("3","Brisbane / Gold Coast, QLD","Queensland's southeast is Australia's teen-vaping flashpoint: school surveys and principals' reporting made the Gold Coast the national symbol of the youth crisis, and border-force seizures at the Port of Brisbane are among the largest."),
   ("4","Perth, WA","WA's isolation didn't protect it — Perth's black market is supplied through Fremantle port, and state surveys show adult vaping rates tracking the east coast."),
   ("5","Adelaide, SA","A smaller but well-documented market; SA Health's surveys captured some of the earliest steep rises in young-adult vaping in the country."),
   ("6","Darwin, NT","The Territory's frontier retail (vapes sold from car yards and grocers, per ABC reporting of ABF raids) makes Darwin's per-capita illicit trade arguably the country's most brazen."),
   ("7","Canberra, ACT","The capital's market is small and young — ANU's campus surveys made national news — but enforcement is the country's tightest."),
   ("8","Hobart, TAS","Tasmania's vape trade follows its older nicotine patterns: smaller volumes, high per-capita nicotine use in wastewater, and a steady convenience-store market."),
   ("9","Newcastle / Wollongong, NSW","Sydney's satellite cities share NSW's top-tier survey rates and its enforcement crackdown."),
   ("10","Cairns / Townsville, QLD","Regional Queensland's youth vaping rates in state school surveys match the southeast — the black market reached the far north fast."),
  ],
  notes="The policy experiment to watch: Australia's 2024–25 reforms (pharmacy-only sales, then prescription-free-but-pharmacist-mediated supply for adults) are the most restrictive legal framework in the Western world, running against a black market that seizure data suggests is still growing. Whether the illicit market shrinks or the legal one bends is the defining question of the next few years — and the arson wars in Melbourne and Sydney show what's at stake.",
  method="Methodology: Australian Border Force seizure statistics (FY2024–26), Illicit Tobacco and E-cigarette Commissioner reporting, state health-department surveys, and ACIC wastewater nicotine data. No city-level use measurement exists; ranks are estimated from seizure geography and survey patterns. Rankings are directional.",
  sources=["Australian Border Force seizure reports (2025–26)","Illicit Tobacco and E-cigarette Commissioner Report 2024–25","State health department vaping surveys (NSW, QLD, VIC)","ACIC National Wastewater Drug Monitoring Program (nicotine)"]),

 dict(slug="vape-cities-middle-east", region="Middle East", title="Top 10 Middle Eastern cities with the most vaping",
  updated="October 2026", read="7 min",
  desc="Vaping in the Middle East — Dubai's regulated mega-market, Jordan's smoking-belt cities, and Egypt's post-2022 boom, mapped from market and survey data.",
  stats=[("2019","the UAE legalized e-cigarette sales — the Gulf's first regulated vape market, now its biggest"),("2022","Egypt ended its de-facto ban and regulated vape sales — unlocking the Arab world's largest consumer market"),("#1","Jordan has posted the world's highest smoking rates in WHO comparisons — and vaping followed the same map")],
  intro="The Middle East split in two on vaping: the UAE (2019), Bahrain and Egypt (2022) built regulated legal markets, while Saudi Arabia taxes and tolerates, and Iran and others ban outright. No government publishes city-level data, so this ranking combines market research, trade data and national surveys. The headline: Dubai turned vaping into a retail spectacle (mall mega-stores, vape expos), Cairo's legalization unlocked the region's biggest population, and Amman's world-beating smoking rates made it a natural conversion market. Every position is an estimate.",
  cities=[
   ("1","Dubai, AE","The region's vape capital by a wide margin: legal since 2019, home to the World Vape Show, hundreds of dedicated retailers, and a huge expatriate demand base. Dubai Duty Free even sells devices to transit passengers."),
   ("2","Abu Dhabi, AE","The UAE's second market — same federal rules, slightly more conservative retail, growing fast."),
   ("3","Cairo, EG","Egypt's 2022 regulation legitimized an enormous existing gray market; Cairo's 20 million people make it the region's largest consumer base in absolute terms, with vape shops spreading through every middle-class district."),
   ("4","Riyadh, SA","Saudi Arabia legalized and taxes vapes (100% excise, matching tobacco); Riyadh's young, increasingly social-liberalizing population drives the kingdom's market."),
   ("5","Amman, JO","Jordan's smoking rates have ranked among the world's very highest (WHO-linked studies put male smoking near 50%+); vaping and heated tobacco converted a slice of that, and Amman's youth drive it."),
   ("6","Jeddah, SA","The kingdom's more relaxed second city tracks Riyadh closely, with a dense corniche retail scene."),
   ("7","Beirut, LB","Lebanon's economic collapse made imported disposables a luxury, but Beirut's nightlife culture sustains a visible vape scene — and local e-liquid mixing filled the import gap."),
   ("8","Kuwait City, KW","Kuwait's market sits in legal gray (sales formally restricted, possession tolerated) — which never stopped one of the Gulf's wealthiest consumer bases."),
   ("9","Tel Aviv, IL","Israel regulates vapes like tobacco (2019 law, flavor and marketing rules tightening); Tel Aviv's market is the region's most Western in structure."),
   ("10","Doha, QA","Qatar formally bans e-cigarette sales — yet surveys find use among residents, supplied by travel and gray channels; Doha ranks here as the region's largest illicit market."),
  ],
  notes="The structural trend is regulation following reality: every Gulf state except Qatar and Oman has now legalized and taxed vaping rather than lose the market to smuggling. Iran maintains a ban with a visible black market in Tehran. Youth uptake is the emerging policy fight — school surveys in the UAE and Egypt show the same teen-disposable pattern that drove bans in Europe.",
  method="Methodology: national regulatory timelines, market-research estimates, WHO tobacco surveys (Jordan, Egypt), and trade/retail reporting. No city-level use measurement exists anywhere in the region. Rankings are directional estimates.",
  sources=["UAE/GCC vape regulation timelines and market reports","WHO tobacco prevalence surveys (Eastern Mediterranean)","Egypt 2022 vape regulation reporting","Regional market research (MENA e-cigarette trade)"]),

 dict(slug="vape-cities-africa", region="Africa", title="Top 10 African cities with the most vaping",
  updated="October 2026", read="7 min",
  desc="Africa's vaping map — South Africa's R1.5-billion legal market leads the continent, from Cape Town's vape lounges to Lagos's youth boom, per market and survey data.",
  stats=[("R3.29/ml","South Africa's excise duty on vape liquid in 2026 — Africa's first dedicated vape tax, introduced June 2023 at R2.90"),(">25%","of South African high-school seniors report using vapes (University of Cape Town study)"),("~$168M","South Africa's vape market size in 2024 — forecast to grow ~15% a year this decade")],
  intro="African vaping is really two stories: South Africa — a formal, taxed, retail-driven market worth over R3 billion and home to the continent's only dedicated vape tax — and everywhere else, where cheap disposables spread through informal trade faster than regulators can react. No African country publishes city-level vaping data, so this ranking combines market research, the University of Cape Town's youth studies, and national policy reporting. The pattern: English-speaking, middle-class, urban Africa vapes; the market follows the money. Every position is an estimate.",
  cities=[
   ("1","Cape Town, ZA","The continent's vaping capital: the densest concentration of dedicated vape shops in Africa, a visible lounge and 'cloud' culture, and the university studies (UCT) that documented the youth boom — over a quarter of high-school seniors vaping."),
   ("2","Johannesburg, ZA","South Africa's biggest market by volume — Gauteng's malls and townships carry the trade, and Joburg hosts the continent's biggest vape expos."),
   ("3","Durban, ZA","The third South African hub: port-city supply, a young coastal market, and the same R2.90→R3.29/ml tax regime that reshaped legal retail nationwide."),
   ("4","Pretoria, ZA","Gauteng's second pole — civil-service salaries and student populations (Tuks) keep it level with Durban."),
   ("5","Lagos, NG","West Africa's biggest market: Nigeria has no comprehensive vape law, and cheap Chinese disposables poured into Lagos's informal retail from 2021 — youth surveys in the city show fast-rising experimentation."),
   ("6","Nairobi, KE","Kenya regulates vapes under its tobacco law (taxed, 18+) but enforcement is thin; Nairobi's middle-class youth market is East Africa's largest, supplied through Jomo Kenyatta's cargo terminals."),
   ("7","Accra, GH","Ghana's FDA classifies vapes as tobacco products; Accra's young professionals drove West Africa's second formal retail scene before disposables undercut it."),
   ("8","Casablanca, MA","Morocco's market grew through tobacconists and gray imports; Casablanca's French-influenced cafe culture adopted vaping early by African standards."),
   ("9","Kampala, UG","Uganda debated an outright ban while Kampala's kiosks kept selling — the classic African pattern of law chasing trade."),
   ("10","Lusaka / Harare","Zambia and Zimbabwe's capitals round out the list: small formal markets, big informal ones, and the region's tobacco-growing economies watching vaping eat their cigarette future."),
  ],
  notes="The continental wildcard is taxation: South Africa's excise (raised every year since 2023) is pushing price-sensitive buyers toward the same illicit networks that captured over half the country's cigarette market — a warning for every finance ministry on the continent. Meanwhile the tobacco industry's pivot (BAT's Johannesburg R&D, heated-tobacco launches) signals where Big Tobacco thinks African nicotine is heading.",
  method="Methodology: market-research estimates, University of Cape Town youth vaping studies, South African Revenue Service excise policy records, and national regulatory reporting. No city-level use measurement exists on the continent. Rankings are directional estimates.",
  sources=["SARS vaping excise duty records (2023–2026)","University of Cape Town youth vaping studies","African market research on e-cigarette trade","WHO AFRO tobacco control reporting"]),
]
